#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_ProductionOrders.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "73815E4892CD32DE003836A6ADA01DDD94DD818B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__ProductionOrders_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__ProductionOrders_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_ProductionOrders.cshtml", 0, 8, true);

WriteLiteral("<section");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 0, 8, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8, 28, true);

WriteLiteral(" id=\"view-production-orders\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8, 28, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 36, 28, true);

WriteLiteral(" class=\"view-section hidden\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 36, 28, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 64, 8, true);

WriteLiteral(">\n  <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 64, 8, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 72, 36, true);

WriteLiteral(" class=\"production-orders-container\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 72, 36, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 108, 145, true);

WriteLiteral(" style=\"padding: 24px; background: var(--bg-secondary); border-radius: 16px; bord" +
"er: 1px solid var(--border-color); margin: 24px; margin-top: 0;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 108, 145, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 253, 34, true);

WriteLiteral(">\n    \n    <!-- Title -->\n    <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 253, 34, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 287, 100, true);

WriteLiteral(" style=\"margin-bottom: 20px; border-bottom: 1px solid rgba(255,255,255,0.05); pad" +
"ding-bottom: 10px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 287, 100, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 387, 11, true);

WriteLiteral(">\n      <h2");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 387, 11, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 398, 93, true);

WriteLiteral(" style=\"margin: 0; font-size: 1.25rem; font-weight: 700; color: #fff; letter-spac" +
"ing: 0.5px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 398, 93, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 491, 100, true);

WriteLiteral(">QUẢN LÝ LỆNH SẢN XUẤT</h2>\n    </div>\n\n    <!-- Top Block: Setup Production Orde" +
"r Form -->\n    <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 491, 100, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 591, 179, true);

WriteLiteral(" style=\"background: rgba(255,255,255,0.01); border: 1px solid var(--border-color)" +
"; border-radius: 16px; padding: 20px; margin-bottom: 24px; display: flex; flex-d" +
"irection: column;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 591, 179, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 770, 11, true);

WriteLiteral(">\n      <h3");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 770, 11, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 781, 91, true);

WriteLiteral(" style=\"margin-top: 0; margin-bottom: 15px; font-size: 1.05rem; color: var(--acce" +
"nt-blue);\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 781, 91, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 872, 47, true);

WriteLiteral(">THIẾT LẬP LỆNH SẢN XUẤT</h3>\n      \n      <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 872, 47, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 919, 19, true);

WriteLiteral(" class=\"order-form\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 919, 19, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 938, 107, true);

WriteLiteral(" style=\"display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-b" +
"ottom: 10px; width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 938, 107, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1045, 36, true);

WriteLiteral(">\n        <!-- Date -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1045, 36, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1081, 57, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1081, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1138, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1138, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1155, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1155, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1230, 39, true);

WriteLiteral(">Ngày tạo lệnh:</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1230, 39, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1269, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1269, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1281, 22, true);

WriteLiteral(" id=\"order-input-date\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1281, 22, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1303, 33, true);

WriteLiteral(" class=\"date-picker-input-custom\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1303, 33, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1336, 31, true);

WriteLiteral(" placeholder=\"Chọn ngày tạo...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1336, 31, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1367, 174, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1367, 174, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1541, 64, true);

WriteLiteral(">\n        </div>\n        \n        <!-- Order No -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1541, 64, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1605, 57, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1605, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1662, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1662, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1679, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1679, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1754, 42, true);

WriteLiteral(">Số Lệnh sản xuất:</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1754, 42, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1796, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1796, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1808, 20, true);

WriteLiteral(" id=\"order-input-no\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1808, 20, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1828, 28, true);

WriteLiteral(" list=\"order-no-suggestions\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1828, 28, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1856, 33, true);

WriteLiteral(" placeholder=\"LSX-YYYYMMDD-NN...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1856, 33, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 1889, 174, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 1889, 174, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2063, 21, true);

WriteLiteral(">\n          <datalist");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2063, 21, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2084, 26, true);

WriteLiteral(" id=\"order-no-suggestions\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2084, 26, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2110, 71, true);

WriteLiteral("></datalist>\n        </div>\n\n        <!-- Product Code -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2110, 71, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2181, 57, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2181, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2238, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2238, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2255, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2255, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2330, 37, true);

WriteLiteral(">Mã sản phẩm:</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2330, 37, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2367, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2367, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2379, 26, true);

WriteLiteral(" id=\"order-input-prodcode\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2379, 26, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2405, 34, true);

WriteLiteral(" placeholder=\"Nhập mã sản phẩm...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2405, 34, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2439, 174, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2439, 174, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2613, 60, true);

WriteLiteral(">\n        </div>\n\n        <!-- Product Name -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2613, 60, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2673, 57, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2673, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2730, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2730, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2747, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2747, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2822, 38, true);

WriteLiteral(">Tên sản phẩm:</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2822, 38, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2860, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2860, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2872, 26, true);

WriteLiteral(" id=\"order-input-prodname\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2872, 26, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2898, 35, true);

WriteLiteral(" placeholder=\"Nhập tên sản phẩm...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2898, 35, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 2933, 174, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 2933, 174, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3107, 71, true);

WriteLiteral(">\n        </div>\n\n        <!-- Assign Machine Dropdown -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3107, 71, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3178, 57, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3178, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3235, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3235, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3252, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3252, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3327, 38, true);

WriteLiteral(">Máy chỉ định:</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3327, 38, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3365, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3365, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3377, 25, true);

WriteLiteral(" id=\"order-input-machine\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3377, 25, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3402, 27, true);

WriteLiteral(" list=\"machine-suggestions\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3402, 27, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3429, 36, true);

WriteLiteral(" placeholder=\"Nhập hoặc chọn máy...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3429, 36, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3465, 193, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"font-weight: bold; width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3465, 193, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3658, 21, true);

WriteLiteral(">\n          <datalist");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3658, 21, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3679, 25, true);

WriteLiteral(" id=\"machine-suggestions\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3679, 25, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3704, 64, true);

WriteLiteral("></datalist>\n        </div>\n\n        <!-- Stage -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3704, 64, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3768, 57, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3768, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3825, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3825, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3842, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3842, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3917, 44, true);

WriteLiteral(">Công đoạn sản xuất:</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3917, 44, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3961, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3961, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3973, 23, true);

WriteLiteral(" id=\"order-input-stage\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3973, 23, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 3996, 25, true);

WriteLiteral(" list=\"stage-suggestions\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 3996, 25, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4021, 42, true);

WriteLiteral(" placeholder=\"Nhập hoặc chọn công đoạn...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4021, 42, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4063, 193, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"font-weight: bold; width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4063, 193, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4256, 21, true);

WriteLiteral(">\n          <datalist");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4256, 21, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4277, 23, true);

WriteLiteral(" id=\"stage-suggestions\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4277, 23, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4300, 21, true);

WriteLiteral(">\n            <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4300, 21, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4321, 22, true);

WriteLiteral(" value=\"Dập định hình\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4321, 22, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4343, 30, true);

WriteLiteral("></option>\n            <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4343, 30, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4373, 20, true);

WriteLiteral(" value=\"Đấm đầu vít\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4373, 20, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4393, 30, true);

WriteLiteral("></option>\n            <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4393, 30, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4423, 20, true);

WriteLiteral(" value=\"Cán ren vít\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4423, 20, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4443, 89, true);

WriteLiteral("></option>\n          </datalist>\n        </div>\n\n        <!-- Target Qty -->\n    " +
"    <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4443, 89, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4532, 77, true);

WriteLiteral(" style=\"display: flex; flex-direction: column; gap: 4px; position: relative;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4532, 77, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4609, 17, true);

WriteLiteral(">\n          <span");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4609, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4626, 75, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary); font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4626, 75, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4701, 49, true);

WriteLiteral(">Số lượng kế hoạch (PCS):</span>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4701, 49, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4750, 14, true);

WriteLiteral(" type=\"number\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4750, 14, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4764, 21, true);

WriteLiteral(" id=\"order-input-qty\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4764, 21, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4785, 31, true);

WriteLiteral(" placeholder=\"Nhập số lượng...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4785, 31, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4816, 174, true);

WriteLiteral(" style=\"padding: 10px; background: var(--bg-primary); border: 1px solid var(--bor" +
"der-color); border-radius: 8px; color: #fff; outline: none; font-size: 0.85rem; " +
"width: 100%;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4816, 174, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 4990, 16, true);

WriteLiteral(">\n          <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 4990, 16, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5006, 26, true);

WriteLiteral(" id=\"inherited-order-hint\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5006, 26, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5032, 292, true);

WriteLiteral(@" style=""display: none; position: absolute; top: 100%; left: 0; right: 0; background: rgba(0, 230, 118, 0.15); border: 1px solid rgba(0, 230, 118, 0.3); border-radius: 6px; padding: 4px 8px; margin-top: 4px; font-size: 0.72rem; color: #00e676; z-index: 10; font-weight: 600; text-align: left;""");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5032, 292, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5324, 82, true);

WriteLiteral("></div>\n        </div>\n\n        <!-- Form Actions (Lưu, Xuất PDF) -->\n        <di" +
"v");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5324, 82, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5406, 57, true);

WriteLiteral(" style=\"display: flex; gap: 12px; align-items: flex-end;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5406, 57, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5463, 19, true);

WriteLiteral(">\n          <button");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5463, 19, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5482, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5482, 14, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5496, 31, true);

WriteLiteral(" id=\"btn-save-production-order\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5496, 31, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5527, 303, true);

WriteLiteral(@" style=""flex: 1; padding: 10px; background: var(--accent-blue); border: none; border-radius: 8px; color: #fff; font-weight: 700; cursor: pointer; transition: all 0.2s; font-size: 0.8rem; height: 38px; display: flex; align-items: center; justify-content: center; text-align: center; white-space: nowrap;""");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5527, 303, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5830, 63, true);

WriteLiteral(">\n            LƯU LỆNH SX\n          </button>\n          <button");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5830, 63, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5893, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5893, 14, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5907, 27, true);

WriteLiteral(" id=\"btn-export-pdf-ticket\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5907, 27, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5934, 9, true);

WriteLiteral(" disabled");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5934, 9, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 5943, 342, true);

WriteLiteral(@" style=""flex: 1; padding: 10px; background: rgba(0, 230, 118, 0.1); border: 1px solid rgba(0, 230, 118, 0.3); border-radius: 8px; color: #00e676; font-weight: 700; cursor: not-allowed; transition: all 0.2s; font-size: 0.8rem; height: 38px; display: flex; align-items: center; justify-content: center; text-align: center; white-space: nowrap;""");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 5943, 342, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6285, 158, true);

WriteLiteral(">\n            XUẤT PDF\n          </button>\n        </div>\n      </div>\n    </div>" +
"\n\n    <!-- Bottom Block: Query / Search & List Production Orders -->\n    <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6285, 158, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6443, 158, true);

WriteLiteral(" style=\"background: rgba(255,255,255,0.01); border: 1px solid var(--border-color)" +
"; border-radius: 16px; padding: 20px; display: flex; flex-direction: column;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6443, 158, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6601, 11, true);

WriteLiteral(">\n      <h3");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6601, 11, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6612, 91, true);

WriteLiteral(" style=\"margin-top: 0; margin-bottom: 15px; font-size: 1.05rem; color: var(--acce" +
"nt-blue);\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6612, 91, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6703, 78, true);

WriteLiteral(">DANH SÁCH LỆNH SẢN XUẤT</h3>\n      \n      <!-- Filter Controls -->\n      <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6703, 78, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6781, 93, true);

WriteLiteral(" style=\"display: flex; gap: 12px; margin-bottom: 20px; align-items: center; flex-" +
"wrap: wrap;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6781, 93, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6874, 42, true);

WriteLiteral(">\n        <!-- Search box -->\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6874, 42, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6916, 27, true);

WriteLiteral(" class=\"search-box-wrapper\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6916, 27, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6943, 53, true);

WriteLiteral(" style=\"flex: 1; min-width: 250px; margin-bottom: 0;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6943, 53, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 6996, 16, true);

WriteLiteral(">\n          <svg");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 6996, 16, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7012, 20, true);

WriteLiteral(" class=\"search-icon\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7012, 20, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7032, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7032, 20, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7052, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7052, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7064, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7064, 22, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7086, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7086, 17, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7103, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7103, 23, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7126, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7126, 24, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7150, 21, true);

WriteLiteral(">\n            <circle");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7150, 21, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7171, 8, true);

WriteLiteral(" cx=\"11\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7171, 8, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7179, 8, true);

WriteLiteral(" cy=\"11\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7179, 8, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7187, 6, true);

WriteLiteral(" r=\"8\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7187, 6, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7193, 28, true);

WriteLiteral("></circle>\n            <line");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7193, 28, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7221, 8, true);

WriteLiteral(" x1=\"21\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7221, 8, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7229, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7229, 8, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7237, 11, true);

WriteLiteral(" x2=\"16.65\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7237, 11, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7248, 11, true);

WriteLiteral(" y2=\"16.65\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7248, 11, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7259, 42, true);

WriteLiteral("></line>\n          </svg>\n          <input");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7259, 42, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7301, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7301, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7313, 24, true);

WriteLiteral(" id=\"order-search-input\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7313, 24, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7337, 45, true);

WriteLiteral(" placeholder=\"Tìm theo tên lệnh, sản phẩm...\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7337, 45, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7382, 71, true);

WriteLiteral(">\n        </div>\n\n        <!-- Status filter select -->\n        <select");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7382, 71, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7453, 25, true);

WriteLiteral(" id=\"order-status-filter\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7453, 25, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7478, 218, true);

WriteLiteral(" style=\"background: var(--bg-primary); border: 1px solid var(--border-color); bor" +
"der-radius: 8px; color: #fff; padding: 10px 16px; font-size: 0.9rem; outline: no" +
"ne; cursor: pointer; min-width: 150px; font-weight: 600;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7478, 218, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7696, 19, true);

WriteLiteral(">\n          <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7696, 19, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7715, 12, true);

WriteLiteral(" value=\"all\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7715, 12, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7727, 45, true);

WriteLiteral(">Tất cả trạng thái</option>\n          <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7727, 45, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7772, 16, true);

WriteLiteral(" value=\"running\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7772, 16, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7788, 41, true);

WriteLiteral(">Đang thực thi</option>\n          <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7788, 41, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7829, 16, true);

WriteLiteral(" value=\"pending\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7829, 16, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7845, 41, true);

WriteLiteral(">Đang chờ chạy</option>\n          <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7845, 41, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7886, 18, true);

WriteLiteral(" value=\"completed\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7886, 18, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7904, 38, true);

WriteLiteral(">Hoàn thành</option>\n          <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7904, 38, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7942, 16, true);

WriteLiteral(" value=\"stopped\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7942, 16, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7958, 36, true);

WriteLiteral(">Tạm dừng</option>\n          <option");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7958, 36, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 7994, 18, true);

WriteLiteral(" value=\"cancelled\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 7994, 18, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8012, 87, true);

WriteLiteral(">Đã hủy</option>\n        </select>\n      </div>\n\n      <!-- Orders Table -->\n    " +
"  <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8012, 87, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8099, 29, true);

WriteLiteral(" class=\"orders-table-wrapper\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8099, 29, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8128, 54, true);

WriteLiteral(" style=\"overflow-x: auto; flex: 1; min-height: 400px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8128, 54, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8182, 16, true);

WriteLiteral(">\n        <table");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8182, 16, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8198, 22, true);

WriteLiteral(" class=\"history-table\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8198, 22, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8220, 66, true);

WriteLiteral(" style=\"width: 100%; border-collapse: collapse; text-align: left;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8220, 66, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8286, 35, true);

WriteLiteral(">\n          <thead>\n            <tr");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8286, 35, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8321, 130, true);

WriteLiteral(" style=\"border-bottom: 1px solid var(--border-color); font-size: 0.8rem; color: v" +
"ar(--text-secondary); text-transform: uppercase;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8321, 130, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8451, 19, true);

WriteLiteral(">\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8451, 19, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8470, 45, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8470, 45, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8515, 31, true);

WriteLiteral(">Mã Lệnh</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8515, 31, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8546, 45, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8546, 45, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8591, 32, true);

WriteLiteral(">Sản phẩm</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8591, 32, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8623, 45, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8623, 45, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8668, 33, true);

WriteLiteral(">Công đoạn</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8668, 33, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8701, 45, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8701, 45, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8746, 32, true);

WriteLiteral(">Thiết bị</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8746, 32, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8778, 64, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700; text-align: right;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8778, 64, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8842, 32, true);

WriteLiteral(">Kế hoạch</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8842, 32, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8874, 64, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700; text-align: right;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8874, 64, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8938, 31, true);

WriteLiteral(">Thực tế</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8938, 31, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 8969, 79, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700; text-align: center; width: 120px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 8969, 79, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9048, 31, true);

WriteLiteral(">Tiến độ</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9048, 31, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9079, 65, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700; text-align: center;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9079, 65, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9144, 34, true);

WriteLiteral(">Trạng thái</th>\n              <th");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9144, 34, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9178, 65, true);

WriteLiteral(" style=\"padding: 12px 8px; font-weight: 700; text-align: center;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9178, 65, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9243, 68, true);

WriteLiteral(">Thao tác</th>\n            </tr>\n          </thead>\n          <tbody");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9243, 68, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9311, 34, true);

WriteLiteral(" id=\"production-orders-table-body\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9311, 34, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9345, 144, true);

WriteLiteral(">\n            <!-- Dynamically populated via JS -->\n          </tbody>\n        </" +
"table>\n      </div>\n      <!-- Footer Pagination -->\n      <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9345, 144, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9489, 159, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: center; margi" +
"n-top: 20px; border-top: 1px solid rgba(255,255,255,0.05); padding-top: 15px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9489, 159, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9648, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9648, 14, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9662, 76, true);

WriteLiteral(" style=\"font-size: 0.85rem; color: var(--text-secondary); font-weight: 500;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9662, 76, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9738, 33, true);

WriteLiteral(" id=\"production-orders-page-info\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9738, 33, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9771, 67, true);

WriteLiteral(">\n          Hiển thị 0 - 0 trong 0 lệnh\n        </div>\n        <div");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9771, 67, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9838, 19, true);

WriteLiteral(" class=\"pagination\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9838, 19, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9857, 34, true);

WriteLiteral(" id=\"production-orders-pagination\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9857, 34, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9891, 33, true);

WriteLiteral(" style=\"display: flex; gap: 8px;\"");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9891, 33, true);

BeginContext("~/Views/Home/_ProductionOrders.cshtml", 9924, 112, true);

WriteLiteral(">\n          <!-- JS dynamic pagination controls -->\n        </div>\n      </div>\n " +
"   </div>\n\n  </div>\n</section>\n");

EndContext("~/Views/Home/_ProductionOrders.cshtml", 9924, 112, true);

        }
    }
}
