#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_History.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5BA9B7FEAE50255D72F6FEA15C56E7FCE8265392"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__History_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__History_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_History.cshtml", 0, 8, true);

WriteLiteral("<section");

EndContext("~/Views/Home/_History.cshtml", 0, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8, 18, true);

WriteLiteral(" id=\"view-history\"");

EndContext("~/Views/Home/_History.cshtml", 8, 18, true);

BeginContext("~/Views/Home/_History.cshtml", 26, 28, true);

WriteLiteral(" class=\"view-section hidden\"");

EndContext("~/Views/Home/_History.cshtml", 26, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 54, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_History.cshtml", 54, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 71, 23, true);

WriteLiteral(" class=\"history-layout\"");

EndContext("~/Views/Home/_History.cshtml", 71, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 94, 61, true);

WriteLiteral(">\r\n            <!-- Row 1: 4 KPI Cards -->\r\n             <div");

EndContext("~/Views/Home/_History.cshtml", 94, 61, true);

BeginContext("~/Views/Home/_History.cshtml", 155, 24, true);

WriteLiteral(" class=\"history-kpi-row\"");

EndContext("~/Views/Home/_History.cshtml", 155, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 179, 56, true);

WriteLiteral(">\r\n              <!-- KPI Card 1 -->\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 179, 56, true);

BeginContext("~/Views/Home/_History.cshtml", 235, 31, true);

WriteLiteral(" class=\"h-kpi-card accent-blue\"");

EndContext("~/Views/Home/_History.cshtml", 235, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 266, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 266, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 290, 20, true);

WriteLiteral(" class=\"h-kpi-label\"");

EndContext("~/Views/Home/_History.cshtml", 290, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 310, 39, true);

WriteLiteral(" data-i18n=\"history_kpi_day_efficiency\"");

EndContext("~/Views/Home/_History.cshtml", 310, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 349, 60, true);

WriteLiteral(">THỜI GIAN SẢN XUẤT TRONG NGÀY</span>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 349, 60, true);

BeginContext("~/Views/Home/_History.cshtml", 409, 20, true);

WriteLiteral(" class=\"h-kpi-value\"");

EndContext("~/Views/Home/_History.cshtml", 409, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 429, 25, true);

WriteLiteral(" id=\"history-kpi-day-val\"");

EndContext("~/Views/Home/_History.cshtml", 429, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 454, 38, true);

WriteLiteral(">06:50:00</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 454, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 492, 29, true);

WriteLiteral(" class=\"h-kpi-trend trend-up\"");

EndContext("~/Views/Home/_History.cshtml", 492, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 521, 27, true);

WriteLiteral(" id=\"history-kpi-day-trend\"");

EndContext("~/Views/Home/_History.cshtml", 521, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 548, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 548, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 573, 25, true);

WriteLiteral(" class=\"trend-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 573, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 598, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 598, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 618, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 618, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 630, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 630, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 652, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_History.cshtml", 652, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 671, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 671, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 694, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 694, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 718, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 718, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 746, 7, true);

WriteLiteral(" x1=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 746, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 753, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 753, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 761, 8, true);

WriteLiteral(" x2=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 761, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 769, 7, true);

WriteLiteral(" y2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 769, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 776, 39, true);

WriteLiteral("></line>\r\n                    <polyline");

EndContext("~/Views/Home/_History.cshtml", 776, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 815, 24, true);

WriteLiteral(" points=\"7 7 17 7 17 17\"");

EndContext("~/Views/Home/_History.cshtml", 815, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 839, 75, true);

WriteLiteral("></polyline>\r\n                  </svg>\r\n                  <span>+2.1% <span");

EndContext("~/Views/Home/_History.cshtml", 839, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 914, 42, true);

WriteLiteral(" data-i18n=\"history_kpi_total_strokes_sub\"");

EndContext("~/Views/Home/_History.cshtml", 914, 42, true);

BeginContext("~/Views/Home/_History.cshtml", 956, 132, true);

WriteLiteral(">so với hôm qua</span></span>\r\n                </div>\r\n              </div>\r\n\r\n  " +
"            <!-- KPI Card 2 -->\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 956, 132, true);

BeginContext("~/Views/Home/_History.cshtml", 1088, 31, true);

WriteLiteral(" class=\"h-kpi-card accent-grey\"");

EndContext("~/Views/Home/_History.cshtml", 1088, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 1119, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 1119, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 1143, 20, true);

WriteLiteral(" class=\"h-kpi-label\"");

EndContext("~/Views/Home/_History.cshtml", 1143, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 1163, 40, true);

WriteLiteral(" data-i18n=\"history_kpi_week_efficiency\"");

EndContext("~/Views/Home/_History.cshtml", 1163, 40, true);

BeginContext("~/Views/Home/_History.cshtml", 1203, 60, true);

WriteLiteral(">THỜI GIAN SẢN XUẤT TRONG TUẦN</span>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 1203, 60, true);

BeginContext("~/Views/Home/_History.cshtml", 1263, 20, true);

WriteLiteral(" class=\"h-kpi-value\"");

EndContext("~/Views/Home/_History.cshtml", 1263, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 1283, 26, true);

WriteLiteral(" id=\"history-kpi-week-val\"");

EndContext("~/Views/Home/_History.cshtml", 1283, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 1309, 38, true);

WriteLiteral(">48:20:00</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 1309, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 1347, 29, true);

WriteLiteral(" class=\"h-kpi-trend trend-up\"");

EndContext("~/Views/Home/_History.cshtml", 1347, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 1376, 28, true);

WriteLiteral(" id=\"history-kpi-week-trend\"");

EndContext("~/Views/Home/_History.cshtml", 1376, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 1404, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 1404, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 1429, 25, true);

WriteLiteral(" class=\"trend-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 1429, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 1454, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 1454, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 1474, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 1474, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 1486, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 1486, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 1508, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_History.cshtml", 1508, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 1527, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 1527, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 1550, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 1550, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 1574, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 1574, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 1602, 7, true);

WriteLiteral(" x1=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 1602, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 1609, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 1609, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 1617, 8, true);

WriteLiteral(" x2=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 1617, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 1625, 7, true);

WriteLiteral(" y2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 1625, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 1632, 39, true);

WriteLiteral("></line>\r\n                    <polyline");

EndContext("~/Views/Home/_History.cshtml", 1632, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 1671, 24, true);

WriteLiteral(" points=\"7 7 17 7 17 17\"");

EndContext("~/Views/Home/_History.cshtml", 1671, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 1695, 75, true);

WriteLiteral("></polyline>\r\n                  </svg>\r\n                  <span>+1.5% <span");

EndContext("~/Views/Home/_History.cshtml", 1695, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 1770, 35, true);

WriteLiteral(" data-i18n=\"history_kpi_uptime_sub\"");

EndContext("~/Views/Home/_History.cshtml", 1770, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 1805, 135, true);

WriteLiteral(">so với tuần trước</span></span>\r\n                </div>\r\n              </div>\r\n\r" +
"\n              <!-- KPI Card 3 -->\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 1805, 135, true);

BeginContext("~/Views/Home/_History.cshtml", 1940, 31, true);

WriteLiteral(" class=\"h-kpi-card accent-blue\"");

EndContext("~/Views/Home/_History.cshtml", 1940, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 1971, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 1971, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 1995, 20, true);

WriteLiteral(" class=\"h-kpi-label\"");

EndContext("~/Views/Home/_History.cshtml", 1995, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 2015, 41, true);

WriteLiteral(" data-i18n=\"history_kpi_month_efficiency\"");

EndContext("~/Views/Home/_History.cshtml", 2015, 41, true);

BeginContext("~/Views/Home/_History.cshtml", 2056, 61, true);

WriteLiteral(">THỜI GIAN SẢN XUẤT TRONG THÁNG</span>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 2056, 61, true);

BeginContext("~/Views/Home/_History.cshtml", 2117, 20, true);

WriteLiteral(" class=\"h-kpi-value\"");

EndContext("~/Views/Home/_History.cshtml", 2117, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 2137, 27, true);

WriteLiteral(" id=\"history-kpi-month-val\"");

EndContext("~/Views/Home/_History.cshtml", 2137, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 2164, 39, true);

WriteLiteral(">192:40:00</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 2164, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 2203, 29, true);

WriteLiteral(" class=\"h-kpi-trend trend-up\"");

EndContext("~/Views/Home/_History.cshtml", 2203, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 2232, 29, true);

WriteLiteral(" id=\"history-kpi-month-trend\"");

EndContext("~/Views/Home/_History.cshtml", 2232, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 2261, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 2261, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 2286, 25, true);

WriteLiteral(" class=\"trend-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 2286, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 2311, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 2311, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 2331, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 2331, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 2343, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 2343, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 2365, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_History.cshtml", 2365, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 2384, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 2384, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 2407, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 2407, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 2431, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 2431, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 2459, 7, true);

WriteLiteral(" x1=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 2459, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 2466, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 2466, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 2474, 8, true);

WriteLiteral(" x2=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 2474, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 2482, 7, true);

WriteLiteral(" y2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 2482, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 2489, 39, true);

WriteLiteral("></line>\r\n                    <polyline");

EndContext("~/Views/Home/_History.cshtml", 2489, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 2528, 24, true);

WriteLiteral(" points=\"7 7 17 7 17 17\"");

EndContext("~/Views/Home/_History.cshtml", 2528, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 2552, 75, true);

WriteLiteral("></polyline>\r\n                  </svg>\r\n                  <span>+0.8% <span");

EndContext("~/Views/Home/_History.cshtml", 2552, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 2627, 44, true);

WriteLiteral(" data-i18n=\"history_kpi_monthly_strokes_sub\"");

EndContext("~/Views/Home/_History.cshtml", 2627, 44, true);

BeginContext("~/Views/Home/_History.cshtml", 2671, 147, true);

WriteLiteral(">so với tháng trước</span></span>\r\n                </div>\r\n              </div>\r\n" +
"\r\n              <!-- KPI Card 4: Day Yield -->\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 2671, 147, true);

BeginContext("~/Views/Home/_History.cshtml", 2818, 32, true);

WriteLiteral(" class=\"h-kpi-card accent-green\"");

EndContext("~/Views/Home/_History.cshtml", 2818, 32, true);

BeginContext("~/Views/Home/_History.cshtml", 2850, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 2850, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 2874, 20, true);

WriteLiteral(" class=\"h-kpi-label\"");

EndContext("~/Views/Home/_History.cshtml", 2874, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 2894, 34, true);

WriteLiteral(" data-i18n=\"history_kpi_day_yield\"");

EndContext("~/Views/Home/_History.cshtml", 2894, 34, true);

BeginContext("~/Views/Home/_History.cshtml", 2928, 51, true);

WriteLiteral(">SẢN LƯỢNG TRONG NGÀY</span>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 2928, 51, true);

BeginContext("~/Views/Home/_History.cshtml", 2979, 20, true);

WriteLiteral(" class=\"h-kpi-value\"");

EndContext("~/Views/Home/_History.cshtml", 2979, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 2999, 27, true);

WriteLiteral(" id=\"history-kpi-day-yield\"");

EndContext("~/Views/Home/_History.cshtml", 2999, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 3026, 36, true);

WriteLiteral(">14.700</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 3026, 36, true);

BeginContext("~/Views/Home/_History.cshtml", 3062, 29, true);

WriteLiteral(" class=\"h-kpi-trend trend-up\"");

EndContext("~/Views/Home/_History.cshtml", 3062, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 3091, 33, true);

WriteLiteral(" id=\"history-kpi-day-yield-trend\"");

EndContext("~/Views/Home/_History.cshtml", 3091, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 3124, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 3124, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 3149, 25, true);

WriteLiteral(" class=\"trend-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 3149, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 3174, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 3174, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 3194, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 3194, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 3206, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 3206, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 3228, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_History.cshtml", 3228, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 3247, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 3247, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 3270, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 3270, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 3294, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 3294, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 3322, 7, true);

WriteLiteral(" x1=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 3322, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 3329, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 3329, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 3337, 8, true);

WriteLiteral(" x2=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 3337, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 3345, 7, true);

WriteLiteral(" y2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 3345, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 3352, 39, true);

WriteLiteral("></line>\r\n                    <polyline");

EndContext("~/Views/Home/_History.cshtml", 3352, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 3391, 24, true);

WriteLiteral(" points=\"7 7 17 7 17 17\"");

EndContext("~/Views/Home/_History.cshtml", 3391, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 3415, 75, true);

WriteLiteral("></polyline>\r\n                  </svg>\r\n                  <span>+1.8% <span");

EndContext("~/Views/Home/_History.cshtml", 3415, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 3490, 38, true);

WriteLiteral(" data-i18n=\"history_kpi_day_yield_sub\"");

EndContext("~/Views/Home/_History.cshtml", 3490, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 3528, 144, true);

WriteLiteral(">so với hôm qua</span></span>\r\n                </div>\r\n              </div>\r\n\r\n  " +
"            <!-- KPI Card 5: Week Yield -->\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 3528, 144, true);

BeginContext("~/Views/Home/_History.cshtml", 3672, 32, true);

WriteLiteral(" class=\"h-kpi-card accent-green\"");

EndContext("~/Views/Home/_History.cshtml", 3672, 32, true);

BeginContext("~/Views/Home/_History.cshtml", 3704, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 3704, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 3728, 20, true);

WriteLiteral(" class=\"h-kpi-label\"");

EndContext("~/Views/Home/_History.cshtml", 3728, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 3748, 35, true);

WriteLiteral(" data-i18n=\"history_kpi_week_yield\"");

EndContext("~/Views/Home/_History.cshtml", 3748, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 3783, 51, true);

WriteLiteral(">SẢN LƯỢNG TRONG TUẦN</span>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 3783, 51, true);

BeginContext("~/Views/Home/_History.cshtml", 3834, 20, true);

WriteLiteral(" class=\"h-kpi-value\"");

EndContext("~/Views/Home/_History.cshtml", 3834, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 3854, 28, true);

WriteLiteral(" id=\"history-kpi-week-yield\"");

EndContext("~/Views/Home/_History.cshtml", 3854, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 3882, 37, true);

WriteLiteral(">102.900</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 3882, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 3919, 29, true);

WriteLiteral(" class=\"h-kpi-trend trend-up\"");

EndContext("~/Views/Home/_History.cshtml", 3919, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 3948, 34, true);

WriteLiteral(" id=\"history-kpi-week-yield-trend\"");

EndContext("~/Views/Home/_History.cshtml", 3948, 34, true);

BeginContext("~/Views/Home/_History.cshtml", 3982, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 3982, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 4007, 25, true);

WriteLiteral(" class=\"trend-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 4007, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 4032, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 4032, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 4052, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 4052, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 4064, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 4064, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 4086, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_History.cshtml", 4086, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 4105, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 4105, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 4128, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 4128, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 4152, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 4152, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 4180, 7, true);

WriteLiteral(" x1=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 4180, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 4187, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 4187, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 4195, 8, true);

WriteLiteral(" x2=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 4195, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 4203, 7, true);

WriteLiteral(" y2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 4203, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 4210, 39, true);

WriteLiteral("></line>\r\n                    <polyline");

EndContext("~/Views/Home/_History.cshtml", 4210, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 4249, 24, true);

WriteLiteral(" points=\"7 7 17 7 17 17\"");

EndContext("~/Views/Home/_History.cshtml", 4249, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 4273, 75, true);

WriteLiteral("></polyline>\r\n                  </svg>\r\n                  <span>+2.3% <span");

EndContext("~/Views/Home/_History.cshtml", 4273, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 4348, 39, true);

WriteLiteral(" data-i18n=\"history_kpi_week_yield_sub\"");

EndContext("~/Views/Home/_History.cshtml", 4348, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 4387, 148, true);

WriteLiteral(">so với tuần trước</span></span>\r\n                </div>\r\n              </div>\r\n\r" +
"\n              <!-- KPI Card 6: Month Yield -->\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 4387, 148, true);

BeginContext("~/Views/Home/_History.cshtml", 4535, 32, true);

WriteLiteral(" class=\"h-kpi-card accent-green\"");

EndContext("~/Views/Home/_History.cshtml", 4535, 32, true);

BeginContext("~/Views/Home/_History.cshtml", 4567, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 4567, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 4591, 20, true);

WriteLiteral(" class=\"h-kpi-label\"");

EndContext("~/Views/Home/_History.cshtml", 4591, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 4611, 36, true);

WriteLiteral(" data-i18n=\"history_kpi_month_yield\"");

EndContext("~/Views/Home/_History.cshtml", 4611, 36, true);

BeginContext("~/Views/Home/_History.cshtml", 4647, 52, true);

WriteLiteral(">SẢN LƯỢNG TRONG THÁNG</span>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 4647, 52, true);

BeginContext("~/Views/Home/_History.cshtml", 4699, 20, true);

WriteLiteral(" class=\"h-kpi-value\"");

EndContext("~/Views/Home/_History.cshtml", 4699, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 4719, 29, true);

WriteLiteral(" id=\"history-kpi-month-yield\"");

EndContext("~/Views/Home/_History.cshtml", 4719, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 4748, 37, true);

WriteLiteral(">441.000</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 4748, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 4785, 29, true);

WriteLiteral(" class=\"h-kpi-trend trend-up\"");

EndContext("~/Views/Home/_History.cshtml", 4785, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 4814, 35, true);

WriteLiteral(" id=\"history-kpi-month-yield-trend\"");

EndContext("~/Views/Home/_History.cshtml", 4814, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 4849, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 4849, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 4874, 25, true);

WriteLiteral(" class=\"trend-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 4874, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 4899, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 4899, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 4919, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 4919, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 4931, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 4931, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 4953, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_History.cshtml", 4953, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 4972, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 4972, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 4995, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 4995, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 5019, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 5019, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 5047, 7, true);

WriteLiteral(" x1=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 5047, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 5054, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 5054, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 5062, 8, true);

WriteLiteral(" x2=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 5062, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 5070, 7, true);

WriteLiteral(" y2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 5070, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 5077, 39, true);

WriteLiteral("></line>\r\n                    <polyline");

EndContext("~/Views/Home/_History.cshtml", 5077, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 5116, 24, true);

WriteLiteral(" points=\"7 7 17 7 17 17\"");

EndContext("~/Views/Home/_History.cshtml", 5116, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 5140, 75, true);

WriteLiteral("></polyline>\r\n                  </svg>\r\n                  <span>+1.2% <span");

EndContext("~/Views/Home/_History.cshtml", 5140, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 5215, 40, true);

WriteLiteral(" data-i18n=\"history_kpi_month_yield_sub\"");

EndContext("~/Views/Home/_History.cshtml", 5215, 40, true);

BeginContext("~/Views/Home/_History.cshtml", 5255, 180, true);

WriteLiteral(">so với tháng trước</span></span>\r\n                </div>\r\n              </div>\r\n" +
"            </div>\r\n\r\n            <!-- Toolbar (Search, Date, Filter, Export) --" +
">\r\n            <div");

EndContext("~/Views/Home/_History.cshtml", 5255, 180, true);

BeginContext("~/Views/Home/_History.cshtml", 5435, 24, true);

WriteLiteral(" class=\"history-toolbar\"");

EndContext("~/Views/Home/_History.cshtml", 5435, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 5459, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 5459, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 5480, 27, true);

WriteLiteral(" class=\"search-box-wrapper\"");

EndContext("~/Views/Home/_History.cshtml", 5480, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 5507, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_History.cshtml", 5507, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 5530, 20, true);

WriteLiteral(" class=\"search-icon\"");

EndContext("~/Views/Home/_History.cshtml", 5530, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 5550, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 5550, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 5570, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 5570, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 5582, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 5582, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 5604, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 5604, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 5621, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 5621, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 5644, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 5644, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 5668, 28, true);

WriteLiteral(">\r\n                  <circle");

EndContext("~/Views/Home/_History.cshtml", 5668, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 5696, 8, true);

WriteLiteral(" cx=\"11\"");

EndContext("~/Views/Home/_History.cshtml", 5696, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 5704, 8, true);

WriteLiteral(" cy=\"11\"");

EndContext("~/Views/Home/_History.cshtml", 5704, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 5712, 6, true);

WriteLiteral(" r=\"8\"");

EndContext("~/Views/Home/_History.cshtml", 5712, 6, true);

BeginContext("~/Views/Home/_History.cshtml", 5718, 35, true);

WriteLiteral("></circle>\r\n                  <line");

EndContext("~/Views/Home/_History.cshtml", 5718, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 5753, 8, true);

WriteLiteral(" x1=\"21\"");

EndContext("~/Views/Home/_History.cshtml", 5753, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 5761, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_History.cshtml", 5761, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 5769, 11, true);

WriteLiteral(" x2=\"16.65\"");

EndContext("~/Views/Home/_History.cshtml", 5769, 11, true);

BeginContext("~/Views/Home/_History.cshtml", 5780, 11, true);

WriteLiteral(" y2=\"16.65\"");

EndContext("~/Views/Home/_History.cshtml", 5780, 11, true);

BeginContext("~/Views/Home/_History.cshtml", 5791, 56, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <input");

EndContext("~/Views/Home/_History.cshtml", 5791, 56, true);

BeginContext("~/Views/Home/_History.cshtml", 5847, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_History.cshtml", 5847, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 5859, 26, true);

WriteLiteral(" id=\"history-search-input\"");

EndContext("~/Views/Home/_History.cshtml", 5859, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 5885, 39, true);

WriteLiteral(" data-i18n=\"history_search_placeholder\"");

EndContext("~/Views/Home/_History.cshtml", 5885, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 5924, 33, true);

WriteLiteral(" placeholder=\"Tìm theo Mã máy...\"");

EndContext("~/Views/Home/_History.cshtml", 5924, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 5957, 45, true);

WriteLiteral(">\r\n              </div>\r\n\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 5957, 45, true);

BeginContext("~/Views/Home/_History.cshtml", 6002, 28, true);

WriteLiteral(" class=\"date-picker-wrapper\"");

EndContext("~/Views/Home/_History.cshtml", 6002, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 6030, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_History.cshtml", 6030, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 6053, 22, true);

WriteLiteral(" class=\"calendar-icon\"");

EndContext("~/Views/Home/_History.cshtml", 6053, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 6075, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 6075, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 6095, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 6095, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 6107, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 6107, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 6129, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 6129, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 6146, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 6146, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 6169, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 6169, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 6193, 26, true);

WriteLiteral(">\r\n                  <rect");

EndContext("~/Views/Home/_History.cshtml", 6193, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 6219, 6, true);

WriteLiteral(" x=\"3\"");

EndContext("~/Views/Home/_History.cshtml", 6219, 6, true);

BeginContext("~/Views/Home/_History.cshtml", 6225, 6, true);

WriteLiteral(" y=\"4\"");

EndContext("~/Views/Home/_History.cshtml", 6225, 6, true);

BeginContext("~/Views/Home/_History.cshtml", 6231, 11, true);

WriteLiteral(" width=\"18\"");

EndContext("~/Views/Home/_History.cshtml", 6231, 11, true);

BeginContext("~/Views/Home/_History.cshtml", 6242, 12, true);

WriteLiteral(" height=\"18\"");

EndContext("~/Views/Home/_History.cshtml", 6242, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 6254, 7, true);

WriteLiteral(" rx=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 6254, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6261, 7, true);

WriteLiteral(" ry=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 6261, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6268, 33, true);

WriteLiteral("></rect>\r\n                  <line");

EndContext("~/Views/Home/_History.cshtml", 6268, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 6301, 8, true);

WriteLiteral(" x1=\"16\"");

EndContext("~/Views/Home/_History.cshtml", 6301, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 6309, 7, true);

WriteLiteral(" y1=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 6309, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6316, 8, true);

WriteLiteral(" x2=\"16\"");

EndContext("~/Views/Home/_History.cshtml", 6316, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 6324, 7, true);

WriteLiteral(" y2=\"6\"");

EndContext("~/Views/Home/_History.cshtml", 6324, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6331, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_History.cshtml", 6331, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 6364, 7, true);

WriteLiteral(" x1=\"8\"");

EndContext("~/Views/Home/_History.cshtml", 6364, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6371, 7, true);

WriteLiteral(" y1=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 6371, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6378, 7, true);

WriteLiteral(" x2=\"8\"");

EndContext("~/Views/Home/_History.cshtml", 6378, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6385, 7, true);

WriteLiteral(" y2=\"6\"");

EndContext("~/Views/Home/_History.cshtml", 6385, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6392, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_History.cshtml", 6392, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 6425, 7, true);

WriteLiteral(" x1=\"3\"");

EndContext("~/Views/Home/_History.cshtml", 6425, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 6432, 8, true);

WriteLiteral(" y1=\"10\"");

EndContext("~/Views/Home/_History.cshtml", 6432, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 6440, 8, true);

WriteLiteral(" x2=\"21\"");

EndContext("~/Views/Home/_History.cshtml", 6440, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 6448, 8, true);

WriteLiteral(" y2=\"10\"");

EndContext("~/Views/Home/_History.cshtml", 6448, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 6456, 56, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <input");

EndContext("~/Views/Home/_History.cshtml", 6456, 56, true);

BeginContext("~/Views/Home/_History.cshtml", 6512, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_History.cshtml", 6512, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 6524, 24, true);

WriteLiteral(" id=\"history-date-range\"");

EndContext("~/Views/Home/_History.cshtml", 6524, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 6548, 37, true);

WriteLiteral(" data-i18n=\"history_date_placeholder\"");

EndContext("~/Views/Home/_History.cshtml", 6548, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 6585, 39, true);

WriteLiteral(" placeholder=\"Chọn khoảng thời gian...\"");

EndContext("~/Views/Home/_History.cshtml", 6585, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 6624, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_History.cshtml", 6624, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 6647, 28, true);

WriteLiteral(" class=\"dropdown-arrow-icon\"");

EndContext("~/Views/Home/_History.cshtml", 6647, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 6675, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 6675, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 6695, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 6695, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 6707, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 6707, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 6729, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 6729, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 6746, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 6746, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 6769, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 6769, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 6793, 30, true);

WriteLiteral(">\r\n                  <polyline");

EndContext("~/Views/Home/_History.cshtml", 6793, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 6823, 24, true);

WriteLiteral(" points=\"6 9 12 15 18 9\"");

EndContext("~/Views/Home/_History.cshtml", 6823, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 6847, 80, true);

WriteLiteral("></polyline>\r\n                </svg>\r\n              </div>\r\n\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 6847, 80, true);

BeginContext("~/Views/Home/_History.cshtml", 6927, 35, true);

WriteLiteral(" class=\"main-filter-wrapper-custom\"");

EndContext("~/Views/Home/_History.cshtml", 6927, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 6962, 44, true);

WriteLiteral(" style=\"display: flex; align-items: center;\"");

EndContext("~/Views/Home/_History.cshtml", 6962, 44, true);

BeginContext("~/Views/Home/_History.cshtml", 7006, 26, true);

WriteLiteral(">\r\n                <select");

EndContext("~/Views/Home/_History.cshtml", 7006, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 7032, 30, true);

WriteLiteral(" id=\"history-main-type-filter\"");

EndContext("~/Views/Home/_History.cshtml", 7032, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 7062, 33, true);

WriteLiteral(" class=\"date-picker-input-custom\"");

EndContext("~/Views/Home/_History.cshtml", 7062, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 7095, 246, true);

WriteLiteral(" style=\"padding: 0 12px; height: 38px; border-radius: 8px; border: 1px solid var(" +
"--border-color); background-color: var(--bg-secondary); color: var(--text-primar" +
"y); font-weight: 500; cursor: pointer; outline: none; transition: border-color 0" +
".2s;\"");

EndContext("~/Views/Home/_History.cshtml", 7095, 246, true);

BeginContext("~/Views/Home/_History.cshtml", 7341, 28, true);

WriteLiteral(">\r\n                  <option");

EndContext("~/Views/Home/_History.cshtml", 7341, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 7369, 17, true);

WriteLiteral(" value=\"stamping\"");

EndContext("~/Views/Home/_History.cshtml", 7369, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 7386, 9, true);

WriteLiteral(" selected");

EndContext("~/Views/Home/_History.cshtml", 7386, 9, true);

BeginContext("~/Views/Home/_History.cshtml", 7395, 41, true);

WriteLiteral(" data-i18n=\"history_main_filter_stamping\"");

EndContext("~/Views/Home/_History.cshtml", 7395, 41, true);

BeginContext("~/Views/Home/_History.cshtml", 7436, 44, true);

WriteLiteral(">Máy dập</option>\r\n                  <option");

EndContext("~/Views/Home/_History.cshtml", 7436, 44, true);

BeginContext("~/Views/Home/_History.cshtml", 7480, 14, true);

WriteLiteral(" value=\"screw\"");

EndContext("~/Views/Home/_History.cshtml", 7480, 14, true);

BeginContext("~/Views/Home/_History.cshtml", 7494, 38, true);

WriteLiteral(" data-i18n=\"history_main_filter_screw\"");

EndContext("~/Views/Home/_History.cshtml", 7494, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 7532, 88, true);

WriteLiteral(">Máy vít</option>\r\n                </select>\r\n              </div>\r\n\r\n           " +
"   <div");

EndContext("~/Views/Home/_History.cshtml", 7532, 88, true);

BeginContext("~/Views/Home/_History.cshtml", 7620, 27, true);

WriteLiteral(" class=\"filter-btn-wrapper\"");

EndContext("~/Views/Home/_History.cshtml", 7620, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 7647, 28, true);

WriteLiteral(" style=\"position: relative;\"");

EndContext("~/Views/Home/_History.cshtml", 7647, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 7675, 26, true);

WriteLiteral(">\r\n                <button");

EndContext("~/Views/Home/_History.cshtml", 7675, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 7701, 19, true);

WriteLiteral(" class=\"filter-btn\"");

EndContext("~/Views/Home/_History.cshtml", 7701, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 7720, 24, true);

WriteLiteral(" id=\"history-filter-btn\"");

EndContext("~/Views/Home/_History.cshtml", 7720, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 7744, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_History.cshtml", 7744, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 7769, 20, true);

WriteLiteral(" class=\"filter-icon\"");

EndContext("~/Views/Home/_History.cshtml", 7769, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 7789, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 7789, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 7809, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 7809, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 7821, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 7821, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 7843, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 7843, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 7860, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 7860, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 7883, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 7883, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 7907, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 7907, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 7935, 7, true);

WriteLiteral(" x1=\"4\"");

EndContext("~/Views/Home/_History.cshtml", 7935, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 7942, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_History.cshtml", 7942, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 7950, 7, true);

WriteLiteral(" x2=\"4\"");

EndContext("~/Views/Home/_History.cshtml", 7950, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 7957, 8, true);

WriteLiteral(" y2=\"14\"");

EndContext("~/Views/Home/_History.cshtml", 7957, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 7965, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 7965, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8000, 7, true);

WriteLiteral(" x1=\"4\"");

EndContext("~/Views/Home/_History.cshtml", 8000, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8007, 8, true);

WriteLiteral(" y1=\"10\"");

EndContext("~/Views/Home/_History.cshtml", 8007, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8015, 7, true);

WriteLiteral(" x2=\"4\"");

EndContext("~/Views/Home/_History.cshtml", 8015, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8022, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_History.cshtml", 8022, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8029, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8029, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8064, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 8064, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8072, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_History.cshtml", 8072, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8080, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 8080, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8088, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 8088, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8096, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8096, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8131, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 8131, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8139, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_History.cshtml", 8139, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8146, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 8146, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8154, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_History.cshtml", 8154, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8161, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8161, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8196, 8, true);

WriteLiteral(" x1=\"20\"");

EndContext("~/Views/Home/_History.cshtml", 8196, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8204, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_History.cshtml", 8204, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8212, 8, true);

WriteLiteral(" x2=\"20\"");

EndContext("~/Views/Home/_History.cshtml", 8212, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8220, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_History.cshtml", 8220, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8228, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8228, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8263, 8, true);

WriteLiteral(" x1=\"20\"");

EndContext("~/Views/Home/_History.cshtml", 8263, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8271, 8, true);

WriteLiteral(" y1=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 8271, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8279, 8, true);

WriteLiteral(" x2=\"20\"");

EndContext("~/Views/Home/_History.cshtml", 8279, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8287, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_History.cshtml", 8287, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8294, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8294, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8329, 7, true);

WriteLiteral(" x1=\"1\"");

EndContext("~/Views/Home/_History.cshtml", 8329, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8336, 8, true);

WriteLiteral(" y1=\"14\"");

EndContext("~/Views/Home/_History.cshtml", 8336, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8344, 7, true);

WriteLiteral(" x2=\"7\"");

EndContext("~/Views/Home/_History.cshtml", 8344, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8351, 8, true);

WriteLiteral(" y2=\"14\"");

EndContext("~/Views/Home/_History.cshtml", 8351, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8359, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8359, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8394, 7, true);

WriteLiteral(" x1=\"9\"");

EndContext("~/Views/Home/_History.cshtml", 8394, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8401, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_History.cshtml", 8401, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8408, 8, true);

WriteLiteral(" x2=\"15\"");

EndContext("~/Views/Home/_History.cshtml", 8408, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8416, 7, true);

WriteLiteral(" y2=\"8\"");

EndContext("~/Views/Home/_History.cshtml", 8416, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 8423, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_History.cshtml", 8423, 35, true);

BeginContext("~/Views/Home/_History.cshtml", 8458, 8, true);

WriteLiteral(" x1=\"17\"");

EndContext("~/Views/Home/_History.cshtml", 8458, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8466, 8, true);

WriteLiteral(" y1=\"16\"");

EndContext("~/Views/Home/_History.cshtml", 8466, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8474, 8, true);

WriteLiteral(" x2=\"23\"");

EndContext("~/Views/Home/_History.cshtml", 8474, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8482, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_History.cshtml", 8482, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 8490, 59, true);

WriteLiteral("></line>\r\n                  </svg>\r\n                  <span");

EndContext("~/Views/Home/_History.cshtml", 8490, 59, true);

BeginContext("~/Views/Home/_History.cshtml", 8549, 31, true);

WriteLiteral(" data-i18n=\"history_btn_filter\"");

EndContext("~/Views/Home/_History.cshtml", 8549, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 8580, 60, true);

WriteLiteral(">Lọc</span>\r\n                </button>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 8580, 60, true);

BeginContext("~/Views/Home/_History.cshtml", 8640, 31, true);

WriteLiteral(" class=\"filter-dropdown hidden\"");

EndContext("~/Views/Home/_History.cshtml", 8640, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 8671, 29, true);

WriteLiteral(" id=\"history-filter-dropdown\"");

EndContext("~/Views/Home/_History.cshtml", 8671, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 8700, 25, true);

WriteLiteral(">\r\n                  <div");

EndContext("~/Views/Home/_History.cshtml", 8700, 25, true);

BeginContext("~/Views/Home/_History.cshtml", 8725, 21, true);

WriteLiteral(" class=\"filter-group\"");

EndContext("~/Views/Home/_History.cshtml", 8725, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 8746, 28, true);

WriteLiteral(">\r\n                    <span");

EndContext("~/Views/Home/_History.cshtml", 8746, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 8774, 27, true);

WriteLiteral(" class=\"filter-group-title\"");

EndContext("~/Views/Home/_History.cshtml", 8774, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 8801, 38, true);

WriteLiteral(" data-i18n=\"history_filter_status_lbl\"");

EndContext("~/Views/Home/_History.cshtml", 8801, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 8839, 46, true);

WriteLiteral(">Trạng thái</span>\r\n                    <label");

EndContext("~/Views/Home/_History.cshtml", 8839, 46, true);

BeginContext("~/Views/Home/_History.cshtml", 8885, 30, true);

WriteLiteral(" class=\"filter-checkbox-label\"");

EndContext("~/Views/Home/_History.cshtml", 8885, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 8915, 31, true);

WriteLiteral(">\r\n                      <input");

EndContext("~/Views/Home/_History.cshtml", 8915, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 8946, 13, true);

WriteLiteral(" type=\"radio\"");

EndContext("~/Views/Home/_History.cshtml", 8946, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 8959, 21, true);

WriteLiteral(" name=\"filter-status\"");

EndContext("~/Views/Home/_History.cshtml", 8959, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 8980, 12, true);

WriteLiteral(" value=\"all\"");

EndContext("~/Views/Home/_History.cshtml", 8980, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 8992, 38, true);

WriteLiteral(" checked>\r\n                      <span");

EndContext("~/Views/Home/_History.cshtml", 8992, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 9030, 38, true);

WriteLiteral(" data-i18n=\"history_filter_status_all\"");

EndContext("~/Views/Home/_History.cshtml", 9030, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 9068, 72, true);

WriteLiteral(">Tất cả</span>\r\n                    </label>\r\n                    <label");

EndContext("~/Views/Home/_History.cshtml", 9068, 72, true);

BeginContext("~/Views/Home/_History.cshtml", 9140, 30, true);

WriteLiteral(" class=\"filter-checkbox-label\"");

EndContext("~/Views/Home/_History.cshtml", 9140, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 9170, 31, true);

WriteLiteral(">\r\n                      <input");

EndContext("~/Views/Home/_History.cshtml", 9170, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 9201, 13, true);

WriteLiteral(" type=\"radio\"");

EndContext("~/Views/Home/_History.cshtml", 9201, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 9214, 21, true);

WriteLiteral(" name=\"filter-status\"");

EndContext("~/Views/Home/_History.cshtml", 9214, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 9235, 16, true);

WriteLiteral(" value=\"running\"");

EndContext("~/Views/Home/_History.cshtml", 9235, 16, true);

BeginContext("~/Views/Home/_History.cshtml", 9251, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_History.cshtml", 9251, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 9281, 44, true);

WriteLiteral(" data-i18n=\"history_filter_status_completed\"");

EndContext("~/Views/Home/_History.cshtml", 9281, 44, true);

BeginContext("~/Views/Home/_History.cshtml", 9325, 76, true);

WriteLiteral(">Hoàn thành</span>\r\n                    </label>\r\n                    <label");

EndContext("~/Views/Home/_History.cshtml", 9325, 76, true);

BeginContext("~/Views/Home/_History.cshtml", 9401, 30, true);

WriteLiteral(" class=\"filter-checkbox-label\"");

EndContext("~/Views/Home/_History.cshtml", 9401, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 9431, 31, true);

WriteLiteral(">\r\n                      <input");

EndContext("~/Views/Home/_History.cshtml", 9431, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 9462, 13, true);

WriteLiteral(" type=\"radio\"");

EndContext("~/Views/Home/_History.cshtml", 9462, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 9475, 21, true);

WriteLiteral(" name=\"filter-status\"");

EndContext("~/Views/Home/_History.cshtml", 9475, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 9496, 16, true);

WriteLiteral(" value=\"stopped\"");

EndContext("~/Views/Home/_History.cshtml", 9496, 16, true);

BeginContext("~/Views/Home/_History.cshtml", 9512, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_History.cshtml", 9512, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 9542, 42, true);

WriteLiteral(" data-i18n=\"history_filter_status_stopped\"");

EndContext("~/Views/Home/_History.cshtml", 9542, 42, true);

BeginContext("~/Views/Home/_History.cshtml", 9584, 104, true);

WriteLiteral(">Không hoàn thành</span>\r\n                    </label>\r\n                  </div>\r" +
"\n                  <div");

EndContext("~/Views/Home/_History.cshtml", 9584, 104, true);

BeginContext("~/Views/Home/_History.cshtml", 9688, 21, true);

WriteLiteral(" class=\"filter-group\"");

EndContext("~/Views/Home/_History.cshtml", 9688, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 9709, 26, true);

WriteLiteral(" style=\"margin-top: 10px;\"");

EndContext("~/Views/Home/_History.cshtml", 9709, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 9735, 28, true);

WriteLiteral(">\r\n                    <span");

EndContext("~/Views/Home/_History.cshtml", 9735, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 9763, 27, true);

WriteLiteral(" class=\"filter-group-title\"");

EndContext("~/Views/Home/_History.cshtml", 9763, 27, true);

BeginContext("~/Views/Home/_History.cshtml", 9790, 39, true);

WriteLiteral(" data-i18n=\"history_filter_quality_lbl\"");

EndContext("~/Views/Home/_History.cshtml", 9790, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 9829, 46, true);

WriteLiteral(">Chất lượng</span>\r\n                    <label");

EndContext("~/Views/Home/_History.cshtml", 9829, 46, true);

BeginContext("~/Views/Home/_History.cshtml", 9875, 30, true);

WriteLiteral(" class=\"filter-checkbox-label\"");

EndContext("~/Views/Home/_History.cshtml", 9875, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 9905, 31, true);

WriteLiteral(">\r\n                      <input");

EndContext("~/Views/Home/_History.cshtml", 9905, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 9936, 13, true);

WriteLiteral(" type=\"radio\"");

EndContext("~/Views/Home/_History.cshtml", 9936, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 9949, 22, true);

WriteLiteral(" name=\"filter-quality\"");

EndContext("~/Views/Home/_History.cshtml", 9949, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 9971, 12, true);

WriteLiteral(" value=\"all\"");

EndContext("~/Views/Home/_History.cshtml", 9971, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 9983, 38, true);

WriteLiteral(" checked>\r\n                      <span");

EndContext("~/Views/Home/_History.cshtml", 9983, 38, true);

BeginContext("~/Views/Home/_History.cshtml", 10021, 39, true);

WriteLiteral(" data-i18n=\"history_filter_quality_all\"");

EndContext("~/Views/Home/_History.cshtml", 10021, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 10060, 72, true);

WriteLiteral(">Tất cả</span>\r\n                    </label>\r\n                    <label");

EndContext("~/Views/Home/_History.cshtml", 10060, 72, true);

BeginContext("~/Views/Home/_History.cshtml", 10132, 30, true);

WriteLiteral(" class=\"filter-checkbox-label\"");

EndContext("~/Views/Home/_History.cshtml", 10132, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 10162, 31, true);

WriteLiteral(">\r\n                      <input");

EndContext("~/Views/Home/_History.cshtml", 10162, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 10193, 13, true);

WriteLiteral(" type=\"radio\"");

EndContext("~/Views/Home/_History.cshtml", 10193, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 10206, 22, true);

WriteLiteral(" name=\"filter-quality\"");

EndContext("~/Views/Home/_History.cshtml", 10206, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 10228, 13, true);

WriteLiteral(" value=\"high\"");

EndContext("~/Views/Home/_History.cshtml", 10228, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 10241, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_History.cshtml", 10241, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 10271, 40, true);

WriteLiteral(" data-i18n=\"history_filter_quality_high\"");

EndContext("~/Views/Home/_History.cshtml", 10271, 40, true);

BeginContext("~/Views/Home/_History.cshtml", 10311, 82, true);

WriteLiteral(">Đạt chuẩn (100%)</span>\r\n                    </label>\r\n                    <labe" +
"l");

EndContext("~/Views/Home/_History.cshtml", 10311, 82, true);

BeginContext("~/Views/Home/_History.cshtml", 10393, 30, true);

WriteLiteral(" class=\"filter-checkbox-label\"");

EndContext("~/Views/Home/_History.cshtml", 10393, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 10423, 31, true);

WriteLiteral(">\r\n                      <input");

EndContext("~/Views/Home/_History.cshtml", 10423, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 10454, 13, true);

WriteLiteral(" type=\"radio\"");

EndContext("~/Views/Home/_History.cshtml", 10454, 13, true);

BeginContext("~/Views/Home/_History.cshtml", 10467, 22, true);

WriteLiteral(" name=\"filter-quality\"");

EndContext("~/Views/Home/_History.cshtml", 10467, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 10489, 12, true);

WriteLiteral(" value=\"low\"");

EndContext("~/Views/Home/_History.cshtml", 10489, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 10501, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_History.cshtml", 10501, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 10531, 39, true);

WriteLiteral(" data-i18n=\"history_filter_quality_low\"");

EndContext("~/Views/Home/_History.cshtml", 10531, 39, true);

BeginContext("~/Views/Home/_History.cshtml", 10570, 108, true);

WriteLiteral(">Không đạt (< 100%)</span>\r\n                    </label>\r\n                  </div" +
">\r\n\r\n                  <div");

EndContext("~/Views/Home/_History.cshtml", 10570, 108, true);

BeginContext("~/Views/Home/_History.cshtml", 10678, 23, true);

WriteLiteral(" class=\"filter-actions\"");

EndContext("~/Views/Home/_History.cshtml", 10678, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 10701, 30, true);

WriteLiteral(">\r\n                    <button");

EndContext("~/Views/Home/_History.cshtml", 10701, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 10731, 32, true);

WriteLiteral(" class=\"filter-action-btn reset\"");

EndContext("~/Views/Home/_History.cshtml", 10731, 32, true);

BeginContext("~/Views/Home/_History.cshtml", 10763, 22, true);

WriteLiteral(" id=\"filter-reset-btn\"");

EndContext("~/Views/Home/_History.cshtml", 10763, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 10785, 37, true);

WriteLiteral(" data-i18n=\"history_filter_btn_reset\"");

EndContext("~/Views/Home/_History.cshtml", 10785, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 10822, 44, true);

WriteLiteral(">Reset</button>\r\n                    <button");

EndContext("~/Views/Home/_History.cshtml", 10822, 44, true);

BeginContext("~/Views/Home/_History.cshtml", 10866, 32, true);

WriteLiteral(" class=\"filter-action-btn apply\"");

EndContext("~/Views/Home/_History.cshtml", 10866, 32, true);

BeginContext("~/Views/Home/_History.cshtml", 10898, 22, true);

WriteLiteral(" id=\"filter-apply-btn\"");

EndContext("~/Views/Home/_History.cshtml", 10898, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 10920, 37, true);

WriteLiteral(" data-i18n=\"history_filter_btn_apply\"");

EndContext("~/Views/Home/_History.cshtml", 10920, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 10957, 110, true);

WriteLiteral(">Lọc</button>\r\n                  </div>\r\n                </div>\r\n              </" +
"div>\r\n\r\n              <button");

EndContext("~/Views/Home/_History.cshtml", 10957, 110, true);

BeginContext("~/Views/Home/_History.cshtml", 11067, 19, true);

WriteLiteral(" class=\"export-btn\"");

EndContext("~/Views/Home/_History.cshtml", 11067, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 11086, 24, true);

WriteLiteral(" id=\"history-export-btn\"");

EndContext("~/Views/Home/_History.cshtml", 11086, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 11110, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_History.cshtml", 11110, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 11133, 20, true);

WriteLiteral(" class=\"export-icon\"");

EndContext("~/Views/Home/_History.cshtml", 11133, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 11153, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_History.cshtml", 11153, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 11173, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_History.cshtml", 11173, 12, true);

BeginContext("~/Views/Home/_History.cshtml", 11185, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_History.cshtml", 11185, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 11207, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_History.cshtml", 11207, 17, true);

BeginContext("~/Views/Home/_History.cshtml", 11224, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 11224, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 11247, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_History.cshtml", 11247, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 11271, 26, true);

WriteLiteral(">\r\n                  <path");

EndContext("~/Views/Home/_History.cshtml", 11271, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 11297, 46, true);

WriteLiteral(" d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"");

EndContext("~/Views/Home/_History.cshtml", 11297, 46, true);

BeginContext("~/Views/Home/_History.cshtml", 11343, 37, true);

WriteLiteral("></path>\r\n                  <polyline");

EndContext("~/Views/Home/_History.cshtml", 11343, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 11380, 26, true);

WriteLiteral(" points=\"7 10 12 15 17 10\"");

EndContext("~/Views/Home/_History.cshtml", 11380, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 11406, 37, true);

WriteLiteral("></polyline>\r\n                  <line");

EndContext("~/Views/Home/_History.cshtml", 11406, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 11443, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 11443, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 11451, 8, true);

WriteLiteral(" y1=\"15\"");

EndContext("~/Views/Home/_History.cshtml", 11451, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 11459, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_History.cshtml", 11459, 8, true);

BeginContext("~/Views/Home/_History.cshtml", 11467, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_History.cshtml", 11467, 7, true);

BeginContext("~/Views/Home/_History.cshtml", 11474, 55, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 11474, 55, true);

BeginContext("~/Views/Home/_History.cshtml", 11529, 31, true);

WriteLiteral(" data-i18n=\"history_btn_export\"");

EndContext("~/Views/Home/_History.cshtml", 11529, 31, true);

BeginContext("~/Views/Home/_History.cshtml", 11560, 123, true);

WriteLiteral(">XUẤT BÁO CÁO</span>\r\n              </button>\r\n            </div>\r\n\r\n            " +
"<!-- Table Container -->\r\n            <div");

EndContext("~/Views/Home/_History.cshtml", 11560, 123, true);

BeginContext("~/Views/Home/_History.cshtml", 11683, 24, true);

WriteLiteral(" class=\"table-container\"");

EndContext("~/Views/Home/_History.cshtml", 11683, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 11707, 23, true);

WriteLiteral(">\r\n              <table");

EndContext("~/Views/Home/_History.cshtml", 11707, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 11730, 22, true);

WriteLiteral(" class=\"history-table\"");

EndContext("~/Views/Home/_History.cshtml", 11730, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 11752, 75, true);

WriteLiteral(">\r\n                <thead>\r\n                  <tr>\r\n                    <th");

EndContext("~/Views/Home/_History.cshtml", 11752, 75, true);

BeginContext("~/Views/Home/_History.cshtml", 11827, 36, true);

WriteLiteral(" data-i18n=\"history_tbl_col_machine\"");

EndContext("~/Views/Home/_History.cshtml", 11827, 36, true);

BeginContext("~/Views/Home/_History.cshtml", 11863, 37, true);

WriteLiteral(">MÃ MÁY</th>\r\n                    <th");

EndContext("~/Views/Home/_History.cshtml", 11863, 37, true);

BeginContext("~/Views/Home/_History.cshtml", 11900, 34, true);

WriteLiteral(" data-i18n=\"history_tbl_col_start\"");

EndContext("~/Views/Home/_History.cshtml", 11900, 34, true);

BeginContext("~/Views/Home/_History.cshtml", 11934, 48, true);

WriteLiteral(">THỜI GIAN BẮT ĐẦU</th>\r\n                    <th");

EndContext("~/Views/Home/_History.cshtml", 11934, 48, true);

BeginContext("~/Views/Home/_History.cshtml", 11982, 32, true);

WriteLiteral(" data-i18n=\"history_tbl_col_end\"");

EndContext("~/Views/Home/_History.cshtml", 11982, 32, true);

BeginContext("~/Views/Home/_History.cshtml", 12014, 49, true);

WriteLiteral(">THỜI GIAN KẾT THÚC</th>\r\n                    <th");

EndContext("~/Views/Home/_History.cshtml", 12014, 49, true);

BeginContext("~/Views/Home/_History.cshtml", 12063, 36, true);

WriteLiteral(" data-i18n=\"history_tbl_col_strokes\"");

EndContext("~/Views/Home/_History.cshtml", 12063, 36, true);

BeginContext("~/Views/Home/_History.cshtml", 12099, 28, true);

WriteLiteral(" style=\"text-align: center;\"");

EndContext("~/Views/Home/_History.cshtml", 12099, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 12127, 48, true);

WriteLiteral(">SẢN LƯỢNG THỰC TẾ</th>\r\n                    <th");

EndContext("~/Views/Home/_History.cshtml", 12127, 48, true);

BeginContext("~/Views/Home/_History.cshtml", 12175, 36, true);

WriteLiteral(" data-i18n=\"history_tbl_col_details\"");

EndContext("~/Views/Home/_History.cshtml", 12175, 36, true);

BeginContext("~/Views/Home/_History.cshtml", 12211, 28, true);

WriteLiteral(" style=\"text-align: center;\"");

EndContext("~/Views/Home/_History.cshtml", 12211, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 12239, 89, true);

WriteLiteral(">CHI TIẾT</th>\r\n                  </tr>\r\n                </thead>\r\n              " +
"  <tbody");

EndContext("~/Views/Home/_History.cshtml", 12239, 89, true);

BeginContext("~/Views/Home/_History.cshtml", 12328, 24, true);

WriteLiteral(" id=\"history-table-body\"");

EndContext("~/Views/Home/_History.cshtml", 12328, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 12352, 127, true);

WriteLiteral(">\r\n                  <!-- Dynamically rendered via JS -->\r\n                </tbod" +
"y>\r\n              </table>\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 12352, 127, true);

BeginContext("~/Views/Home/_History.cshtml", 12479, 21, true);

WriteLiteral(" class=\"table-footer\"");

EndContext("~/Views/Home/_History.cshtml", 12479, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 12500, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 12500, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 12524, 19, true);

WriteLiteral(" class=\"table-info\"");

EndContext("~/Views/Home/_History.cshtml", 12524, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 12543, 24, true);

WriteLiteral(" id=\"history-table-info\"");

EndContext("~/Views/Home/_History.cshtml", 12543, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 12567, 59, true);

WriteLiteral(">Hiển thị 1 - 5 của 24 bản ghi</span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 12567, 59, true);

BeginContext("~/Views/Home/_History.cshtml", 12626, 19, true);

WriteLiteral(" class=\"pagination\"");

EndContext("~/Views/Home/_History.cshtml", 12626, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 12645, 24, true);

WriteLiteral(" id=\"history-pagination\"");

EndContext("~/Views/Home/_History.cshtml", 12645, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 12669, 191, true);

WriteLiteral(">\r\n                  <!-- Dynamically rendered via JS -->\r\n                </div>" +
"\r\n              </div>\r\n            </div>\r\n\r\n            <!-- Bảng Lệnh sản xuấ" +
"t đã lưu -->\r\n            <div");

EndContext("~/Views/Home/_History.cshtml", 12669, 191, true);

BeginContext("~/Views/Home/_History.cshtml", 12860, 24, true);

WriteLiteral(" class=\"table-container\"");

EndContext("~/Views/Home/_History.cshtml", 12860, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 12884, 26, true);

WriteLiteral(" style=\"margin-top: 30px;\"");

EndContext("~/Views/Home/_History.cshtml", 12884, 26, true);

BeginContext("~/Views/Home/_History.cshtml", 12910, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 12910, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 12931, 21, true);

WriteLiteral(" class=\"panel-header\"");

EndContext("~/Views/Home/_History.cshtml", 12931, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 12952, 29, true);

WriteLiteral(" style=\"margin-bottom: 15px;\"");

EndContext("~/Views/Home/_History.cshtml", 12952, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 12981, 22, true);

WriteLiteral(">\r\n                <h3");

EndContext("~/Views/Home/_History.cshtml", 12981, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 13003, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Home/_History.cshtml", 13003, 20, true);

BeginContext("~/Views/Home/_History.cshtml", 13023, 70, true);

WriteLiteral(" style=\"font-size: 1rem; font-weight: 700; color: var(--accent-blue);\"");

EndContext("~/Views/Home/_History.cshtml", 13023, 70, true);

BeginContext("~/Views/Home/_History.cshtml", 13093, 33, true);

WriteLiteral(" data-i18n=\"history_orders_title\"");

EndContext("~/Views/Home/_History.cshtml", 13093, 33, true);

BeginContext("~/Views/Home/_History.cshtml", 13126, 71, true);

WriteLiteral(">QUẢN LÝ LỆNH SẢN XUẤT</h3>\r\n              </div>\r\n              <table");

EndContext("~/Views/Home/_History.cshtml", 13126, 71, true);

BeginContext("~/Views/Home/_History.cshtml", 13197, 22, true);

WriteLiteral(" class=\"history-table\"");

EndContext("~/Views/Home/_History.cshtml", 13197, 22, true);

BeginContext("~/Views/Home/_History.cshtml", 13219, 29, true);

WriteLiteral(" id=\"orders-management-table\"");

EndContext("~/Views/Home/_History.cshtml", 13219, 29, true);

BeginContext("~/Views/Home/_History.cshtml", 13248, 317, true);

WriteLiteral(@">
                <thead>
                  <tr>
                    <th>NGÀY TẠO</th>
                    <th>SỐ LỆNH SX</th>
                    <th>MÃ SẢN PHẨM</th>
                    <th>TÊN SẢN PHẨM</th>
                    <th>MÃ MÁY</th>
                    <th>CÔNG ĐOẠN</th>
                    <th");

EndContext("~/Views/Home/_History.cshtml", 13248, 317, true);

BeginContext("~/Views/Home/_History.cshtml", 13565, 28, true);

WriteLiteral(" style=\"text-align: center;\"");

EndContext("~/Views/Home/_History.cshtml", 13565, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 13593, 45, true);

WriteLiteral(">SỐ LƯỢNG (PCS)</th>\r\n                    <th");

EndContext("~/Views/Home/_History.cshtml", 13593, 45, true);

BeginContext("~/Views/Home/_History.cshtml", 13638, 28, true);

WriteLiteral(" style=\"text-align: center;\"");

EndContext("~/Views/Home/_History.cshtml", 13638, 28, true);

BeginContext("~/Views/Home/_History.cshtml", 13666, 91, true);

WriteLiteral(">TRẠNG THÁI</th>\r\n                  </tr>\r\n                </thead>\r\n            " +
"    <tbody");

EndContext("~/Views/Home/_History.cshtml", 13666, 91, true);

BeginContext("~/Views/Home/_History.cshtml", 13757, 23, true);

WriteLiteral(" id=\"orders-table-body\"");

EndContext("~/Views/Home/_History.cshtml", 13757, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 13780, 118, true);

WriteLiteral(">\r\n                  <!-- Render động qua JS -->\r\n                </tbody>\r\n     " +
"         </table>\r\n              <div");

EndContext("~/Views/Home/_History.cshtml", 13780, 118, true);

BeginContext("~/Views/Home/_History.cshtml", 13898, 21, true);

WriteLiteral(" class=\"table-footer\"");

EndContext("~/Views/Home/_History.cshtml", 13898, 21, true);

BeginContext("~/Views/Home/_History.cshtml", 13919, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_History.cshtml", 13919, 24, true);

BeginContext("~/Views/Home/_History.cshtml", 13943, 19, true);

WriteLiteral(" class=\"table-info\"");

EndContext("~/Views/Home/_History.cshtml", 13943, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 13962, 23, true);

WriteLiteral(" id=\"orders-table-info\"");

EndContext("~/Views/Home/_History.cshtml", 13962, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 13985, 30, true);

WriteLiteral("></span>\r\n                <div");

EndContext("~/Views/Home/_History.cshtml", 13985, 30, true);

BeginContext("~/Views/Home/_History.cshtml", 14015, 19, true);

WriteLiteral(" class=\"pagination\"");

EndContext("~/Views/Home/_History.cshtml", 14015, 19, true);

BeginContext("~/Views/Home/_History.cshtml", 14034, 23, true);

WriteLiteral(" id=\"orders-pagination\"");

EndContext("~/Views/Home/_History.cshtml", 14034, 23, true);

BeginContext("~/Views/Home/_History.cshtml", 14057, 127, true);

WriteLiteral("></div>\r\n              </div>\r\n            </div>\r\n\r\n          </div>\r\n        </" +
"section>\r\n\r\n        <!-- 4. VIEW BÁO CÁO -->\r\n");

EndContext("~/Views/Home/_History.cshtml", 14057, 127, true);

        }
    }
}
