#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_Alerts.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5772E861459D0BC382C2D8BD496C43231AED9052"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__Alerts_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__Alerts_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_Alerts.cshtml", 0, 16, true);

WriteLiteral("        <section");

EndContext("~/Views/Home/_Alerts.cshtml", 0, 16, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 16, 16, true);

WriteLiteral(" id=\"view-alert\"");

EndContext("~/Views/Home/_Alerts.cshtml", 16, 16, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 32, 28, true);

WriteLiteral(" class=\"view-section hidden\"");

EndContext("~/Views/Home/_Alerts.cshtml", 32, 28, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 60, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_Alerts.cshtml", 60, 17, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 77, 21, true);

WriteLiteral(" class=\"alarm-layout\"");

EndContext("~/Views/Home/_Alerts.cshtml", 77, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 98, 59, true);

WriteLiteral(">\r\n            <!-- Top KPI Cards Row -->\r\n            <div");

EndContext("~/Views/Home/_Alerts.cshtml", 98, 59, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 157, 22, true);

WriteLiteral(" class=\"alarm-kpi-row\"");

EndContext("~/Views/Home/_Alerts.cshtml", 157, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 179, 73, true);

WriteLiteral(">\r\n              <!-- KPI Card 1: Critical errors -->\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 179, 73, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 252, 34, true);

WriteLiteral(" class=\"alarm-kpi-card border-red\"");

EndContext("~/Views/Home/_Alerts.cshtml", 252, 34, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 286, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Home/_Alerts.cshtml", 286, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 309, 26, true);

WriteLiteral(" class=\"alarm-kpi-content\"");

EndContext("~/Views/Home/_Alerts.cshtml", 309, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 335, 26, true);

WriteLiteral(">\r\n                  <span");

EndContext("~/Views/Home/_Alerts.cshtml", 335, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 361, 24, true);

WriteLiteral(" class=\"alarm-kpi-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 361, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 385, 31, true);

WriteLiteral(" data-i18n=\"alarm_kpi_critical\"");

EndContext("~/Views/Home/_Alerts.cshtml", 385, 31, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 416, 49, true);

WriteLiteral(">LỖI NGHIÊM TRỌNG</span>\r\n                  <span");

EndContext("~/Views/Home/_Alerts.cshtml", 416, 49, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 465, 34, true);

WriteLiteral(" class=\"alarm-kpi-value color-red\"");

EndContext("~/Views/Home/_Alerts.cshtml", 465, 34, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 499, 24, true);

WriteLiteral(" id=\"alarm-kpi-critical\"");

EndContext("~/Views/Home/_Alerts.cshtml", 499, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 523, 35, true);

WriteLiteral(">03</span>\r\n                  <span");

EndContext("~/Views/Home/_Alerts.cshtml", 523, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 558, 26, true);

WriteLiteral(" class=\"alarm-kpi-subtext\"");

EndContext("~/Views/Home/_Alerts.cshtml", 558, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 584, 35, true);

WriteLiteral(" data-i18n=\"alarm_kpi_critical_sub\"");

EndContext("~/Views/Home/_Alerts.cshtml", 584, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 619, 84, true);

WriteLiteral(">Yêu cầu can thiệp ngay lập tức</span>\r\n                </div>\r\n                <" +
"div");

EndContext("~/Views/Home/_Alerts.cshtml", 619, 84, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 703, 24, true);

WriteLiteral(" class=\"alarm-kpi-badge\"");

EndContext("~/Views/Home/_Alerts.cshtml", 703, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 727, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_Alerts.cshtml", 727, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 752, 32, true);

WriteLiteral(" class=\"alarm-icon-svg text-red\"");

EndContext("~/Views/Home/_Alerts.cshtml", 752, 32, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 784, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Alerts.cshtml", 784, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 804, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Alerts.cshtml", 804, 12, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 816, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Alerts.cshtml", 816, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 838, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Alerts.cshtml", 838, 17, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 855, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 855, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 878, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 878, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 902, 30, true);

WriteLiteral(">\r\n                    <circle");

EndContext("~/Views/Home/_Alerts.cshtml", 902, 30, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 932, 8, true);

WriteLiteral(" cx=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 932, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 940, 8, true);

WriteLiteral(" cy=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 940, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 948, 7, true);

WriteLiteral(" r=\"10\"");

EndContext("~/Views/Home/_Alerts.cshtml", 948, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 955, 37, true);

WriteLiteral("></circle>\r\n                    <line");

EndContext("~/Views/Home/_Alerts.cshtml", 955, 37, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 992, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 992, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1000, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1000, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1007, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1007, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1015, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1015, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1023, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_Alerts.cshtml", 1023, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1058, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1058, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1066, 8, true);

WriteLiteral(" y1=\"16\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1066, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1074, 11, true);

WriteLiteral(" x2=\"12.01\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1074, 11, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1085, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1085, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1093, 154, true);

WriteLiteral("></line>\r\n                  </svg>\r\n                </div>\r\n              </div>\r" +
"\n\r\n              <!-- KPI Card 2: System warnings -->\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 1093, 154, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1247, 37, true);

WriteLiteral(" class=\"alarm-kpi-card border-orange\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1247, 37, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1284, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Home/_Alerts.cshtml", 1284, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1307, 26, true);

WriteLiteral(" class=\"alarm-kpi-content\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1307, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1333, 26, true);

WriteLiteral(">\r\n                  <span");

EndContext("~/Views/Home/_Alerts.cshtml", 1333, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1359, 24, true);

WriteLiteral(" class=\"alarm-kpi-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1359, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1383, 30, true);

WriteLiteral(" data-i18n=\"alarm_kpi_warning\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1383, 30, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1413, 50, true);

WriteLiteral(">CẢNH BÁO HỆ THỐNG</span>\r\n                  <span");

EndContext("~/Views/Home/_Alerts.cshtml", 1413, 50, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1463, 37, true);

WriteLiteral(" class=\"alarm-kpi-value color-orange\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1463, 37, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1500, 23, true);

WriteLiteral(" id=\"alarm-kpi-warning\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1500, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1523, 35, true);

WriteLiteral(">12</span>\r\n                  <span");

EndContext("~/Views/Home/_Alerts.cshtml", 1523, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1558, 26, true);

WriteLiteral(" class=\"alarm-kpi-subtext\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1558, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1584, 34, true);

WriteLiteral(" data-i18n=\"alarm_kpi_warning_sub\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1584, 34, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1618, 78, true);

WriteLiteral(">Kiểm tra bảo trì định kỳ</span>\r\n                </div>\r\n                <div");

EndContext("~/Views/Home/_Alerts.cshtml", 1618, 78, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1696, 24, true);

WriteLiteral(" class=\"alarm-kpi-badge\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1696, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1720, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_Alerts.cshtml", 1720, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1745, 35, true);

WriteLiteral(" class=\"alarm-icon-svg text-orange\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1745, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1780, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1780, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1800, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1800, 12, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1812, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1812, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1834, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1834, 17, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1851, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1851, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1874, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1874, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1898, 28, true);

WriteLiteral(">\r\n                    <path");

EndContext("~/Views/Home/_Alerts.cshtml", 1898, 28, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 1926, 93, true);

WriteLiteral(" d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 " +
"0 0-3.42 0z\"");

EndContext("~/Views/Home/_Alerts.cshtml", 1926, 93, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2019, 35, true);

WriteLiteral("></path>\r\n                    <line");

EndContext("~/Views/Home/_Alerts.cshtml", 2019, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2054, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2054, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2062, 7, true);

WriteLiteral(" y1=\"9\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2062, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2069, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2069, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2077, 8, true);

WriteLiteral(" y2=\"13\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2077, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2085, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_Alerts.cshtml", 2085, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2120, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2120, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2128, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2128, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2136, 11, true);

WriteLiteral(" x2=\"12.01\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2136, 11, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2147, 8, true);

WriteLiteral(" y2=\"17\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2147, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2155, 166, true);

WriteLiteral("></line>\r\n                  </svg>\r\n                </div>\r\n              </div>\r" +
"\n\r\n\r\n            </div>\r\n\r\n            <!-- Filter & Search Bar -->\r\n           " +
" <div");

EndContext("~/Views/Home/_Alerts.cshtml", 2155, 166, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2321, 25, true);

WriteLiteral(" class=\"alarm-filter-bar\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2321, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2346, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 2346, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2367, 26, true);

WriteLiteral(" class=\"alarm-filter-tabs\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2367, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2393, 25, true);

WriteLiteral(" id=\"alarm-severity-tabs\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2393, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2418, 26, true);

WriteLiteral(">\r\n                <button");

EndContext("~/Views/Home/_Alerts.cshtml", 2418, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2444, 29, true);

WriteLiteral(" class=\"alarm-tab-btn active\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2444, 29, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2473, 20, true);

WriteLiteral(" data-severity=\"all\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2473, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2493, 6, true);

WriteLiteral("><span");

EndContext("~/Views/Home/_Alerts.cshtml", 2493, 6, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2499, 38, true);

WriteLiteral(" data-i18n=\"alarm_filter_severity_all\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2499, 38, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2537, 20, true);

WriteLiteral(">Tất cả</span> <span");

EndContext("~/Views/Home/_Alerts.cshtml", 2537, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2557, 20, true);

WriteLiteral(" class=\"badge-count\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2557, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2577, 21, true);

WriteLiteral(" id=\"alarm-count-all\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2577, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2598, 43, true);

WriteLiteral(">3</span></button>\r\n                <button");

EndContext("~/Views/Home/_Alerts.cshtml", 2598, 43, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2641, 22, true);

WriteLiteral(" class=\"alarm-tab-btn\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2641, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2663, 25, true);

WriteLiteral(" data-severity=\"critical\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2663, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2688, 43, true);

WriteLiteral(" data-i18n=\"alarm_filter_severity_critical\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2688, 43, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2731, 47, true);

WriteLiteral(">Nghiêm trọng</button>\r\n                <button");

EndContext("~/Views/Home/_Alerts.cshtml", 2731, 47, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2778, 22, true);

WriteLiteral(" class=\"alarm-tab-btn\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2778, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2800, 24, true);

WriteLiteral(" data-severity=\"warning\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2800, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2824, 42, true);

WriteLiteral(" data-i18n=\"alarm_filter_severity_warning\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2824, 42, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2866, 43, true);

WriteLiteral(">Cảnh báo</button>\r\n                <button");

EndContext("~/Views/Home/_Alerts.cshtml", 2866, 43, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2909, 22, true);

WriteLiteral(" class=\"alarm-tab-btn\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2909, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2931, 21, true);

WriteLiteral(" data-severity=\"info\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2931, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2952, 39, true);

WriteLiteral(" data-i18n=\"alarm_filter_severity_info\"");

EndContext("~/Views/Home/_Alerts.cshtml", 2952, 39, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 2991, 63, true);

WriteLiteral(">Thông tin</button>\r\n              </div>\r\n\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 2991, 63, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3054, 29, true);

WriteLiteral(" class=\"alarm-search-wrapper\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3054, 29, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3083, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_Alerts.cshtml", 3083, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3106, 20, true);

WriteLiteral(" class=\"search-icon\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3106, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3126, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3126, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3146, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3146, 12, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3158, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3158, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3180, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3180, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3199, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3199, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3222, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3222, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3246, 28, true);

WriteLiteral(">\r\n                  <circle");

EndContext("~/Views/Home/_Alerts.cshtml", 3246, 28, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3274, 8, true);

WriteLiteral(" cx=\"11\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3274, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3282, 8, true);

WriteLiteral(" cy=\"11\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3282, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3290, 6, true);

WriteLiteral(" r=\"8\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3290, 6, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3296, 35, true);

WriteLiteral("></circle>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 3296, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3331, 8, true);

WriteLiteral(" x1=\"21\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3331, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3339, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3339, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3347, 11, true);

WriteLiteral(" x2=\"16.65\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3347, 11, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3358, 11, true);

WriteLiteral(" y2=\"16.65\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3358, 11, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3369, 56, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <input");

EndContext("~/Views/Home/_Alerts.cshtml", 3369, 56, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3425, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3425, 12, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3437, 24, true);

WriteLiteral(" id=\"alarm-search-input\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3437, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3461, 47, true);

WriteLiteral(" placeholder=\"Tìm kiếm theo mã lỗi hoặc máy...\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3461, 47, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3508, 37, true);

WriteLiteral(" data-i18n=\"alarm_search_placeholder\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3508, 37, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3545, 48, true);

WriteLiteral(">\r\n              </div>\r\n\r\n              <button");

EndContext("~/Views/Home/_Alerts.cshtml", 3545, 48, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3593, 25, true);

WriteLiteral(" class=\"alarm-filter-btn\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3593, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3618, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_Alerts.cshtml", 3618, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3641, 20, true);

WriteLiteral(" class=\"filter-icon\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3641, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3661, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3661, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3681, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3681, 12, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3693, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3693, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3715, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3715, 17, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3732, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3732, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3755, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3755, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3779, 26, true);

WriteLiteral(">\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 3779, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3805, 7, true);

WriteLiteral(" x1=\"4\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3805, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3812, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3812, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3820, 7, true);

WriteLiteral(" x2=\"4\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3820, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3827, 8, true);

WriteLiteral(" y2=\"14\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3827, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3835, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 3835, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3868, 7, true);

WriteLiteral(" x1=\"4\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3868, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3875, 8, true);

WriteLiteral(" y1=\"10\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3875, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3883, 7, true);

WriteLiteral(" x2=\"4\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3883, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3890, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3890, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3897, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 3897, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3930, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3930, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3938, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3938, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3946, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3946, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3954, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3954, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3962, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 3962, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 3995, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 3995, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4003, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4003, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4010, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4010, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4018, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4018, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4025, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 4025, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4058, 8, true);

WriteLiteral(" x1=\"20\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4058, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4066, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4066, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4074, 8, true);

WriteLiteral(" x2=\"20\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4074, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4082, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4082, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4090, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 4090, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4123, 8, true);

WriteLiteral(" x1=\"20\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4123, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4131, 8, true);

WriteLiteral(" y1=\"12\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4131, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4139, 8, true);

WriteLiteral(" x2=\"20\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4139, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4147, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4147, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4154, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 4154, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4187, 7, true);

WriteLiteral(" x1=\"2\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4187, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4194, 8, true);

WriteLiteral(" y1=\"14\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4194, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4202, 7, true);

WriteLiteral(" x2=\"6\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4202, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4209, 8, true);

WriteLiteral(" y2=\"14\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4209, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4217, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 4217, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4250, 8, true);

WriteLiteral(" x1=\"10\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4250, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4258, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4258, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4265, 8, true);

WriteLiteral(" x2=\"14\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4265, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4273, 7, true);

WriteLiteral(" y2=\"8\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4273, 7, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4280, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Alerts.cshtml", 4280, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4313, 8, true);

WriteLiteral(" x1=\"18\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4313, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4321, 8, true);

WriteLiteral(" y1=\"16\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4321, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4329, 8, true);

WriteLiteral(" x2=\"22\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4329, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4337, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4337, 8, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4345, 55, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 4345, 55, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4400, 31, true);

WriteLiteral(" data-i18n=\"history_btn_filter\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4400, 31, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4431, 110, true);

WriteLiteral(">Lọc</span>\r\n              </button>\r\n            </div>\r\n\r\n            <!-- Tabl" +
"e Panel -->\r\n            <div");

EndContext("~/Views/Home/_Alerts.cshtml", 4431, 110, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4541, 26, true);

WriteLiteral(" class=\"alarm-table-panel\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4541, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4567, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 4567, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4588, 30, true);

WriteLiteral(" class=\"alarm-table-container\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4588, 30, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4618, 25, true);

WriteLiteral(">\r\n                <table");

EndContext("~/Views/Home/_Alerts.cshtml", 4618, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4643, 20, true);

WriteLiteral(" class=\"alarm-table\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4643, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4663, 81, true);

WriteLiteral(">\r\n                  <thead>\r\n                    <tr>\r\n                      <th" +
"");

EndContext("~/Views/Home/_Alerts.cshtml", 4663, 81, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4744, 22, true);

WriteLiteral(" style=\"width: 140px;\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4744, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4766, 31, true);

WriteLiteral(" data-i18n=\"alarm_tbl_col_time\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4766, 31, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4797, 42, true);

WriteLiteral(">THỜI GIAN</th>\r\n                      <th");

EndContext("~/Views/Home/_Alerts.cshtml", 4797, 42, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4839, 22, true);

WriteLiteral(" style=\"width: 140px;\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4839, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4861, 35, true);

WriteLiteral(" data-i18n=\"alarm_tbl_col_severity\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4861, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4896, 39, true);

WriteLiteral(">MỨC ĐỘ</th>\r\n                      <th");

EndContext("~/Views/Home/_Alerts.cshtml", 4896, 39, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4935, 22, true);

WriteLiteral(" style=\"width: 220px;\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4935, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4957, 31, true);

WriteLiteral(" data-i18n=\"alarm_tbl_col_code\"");

EndContext("~/Views/Home/_Alerts.cshtml", 4957, 31, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 4988, 50, true);

WriteLiteral(">MÃ LỖI / THIẾT BỊ</th>\r\n                      <th");

EndContext("~/Views/Home/_Alerts.cshtml", 4988, 50, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5038, 31, true);

WriteLiteral(" data-i18n=\"alarm_tbl_col_desc\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5038, 31, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5069, 47, true);

WriteLiteral(">MÔ TẢ CHI TIẾT</th>\r\n                      <th");

EndContext("~/Views/Home/_Alerts.cshtml", 5069, 47, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5116, 22, true);

WriteLiteral(" style=\"width: 160px;\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5116, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5138, 33, true);

WriteLiteral(" data-i18n=\"alarm_tbl_col_status\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5138, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5171, 97, true);

WriteLiteral(">TRẠNG THÁI</th>\r\n                    </tr>\r\n                  </thead>\r\n        " +
"          <tbody");

EndContext("~/Views/Home/_Alerts.cshtml", 5171, 97, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5268, 22, true);

WriteLiteral(" id=\"alarm-table-body\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5268, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5290, 214, true);

WriteLiteral(">\r\n                    <!-- Dynamically populated via JS -->\r\n                  <" +
"/tbody>\r\n                </table>\r\n              </div>\r\n              \r\n       " +
"       <!-- Footer Pagination -->\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 5290, 214, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5504, 27, true);

WriteLiteral(" class=\"alarm-table-footer\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5504, 27, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5531, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 5531, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5555, 20, true);

WriteLiteral(" class=\"footer-info\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5555, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5575, 22, true);

WriteLiteral(" id=\"alarm-table-info\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5575, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5597, 70, true);

WriteLiteral(">Hiển thị 1 - 10 trên tổng số 24 cảnh báo</span>\r\n                <div");

EndContext("~/Views/Home/_Alerts.cshtml", 5597, 70, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5667, 19, true);

WriteLiteral(" class=\"pagination\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5667, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5686, 22, true);

WriteLiteral(" id=\"alarm-pagination\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5686, 22, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5708, 220, true);

WriteLiteral(">\r\n                  <!-- Generated via JS -->\r\n                </div>\r\n         " +
"     </div>\r\n            </div>\r\n          </div>\r\n        </section>\r\n\r\n       " +
" <!-- Alarm Interactive Acknowledge Modal -->\r\n        <div");

EndContext("~/Views/Home/_Alerts.cshtml", 5708, 220, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5928, 35, true);

WriteLiteral(" class=\"alarm-modal-overlay hidden\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5928, 35, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5963, 24, true);

WriteLiteral(" id=\"alarm-action-modal\"");

EndContext("~/Views/Home/_Alerts.cshtml", 5963, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 5987, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_Alerts.cshtml", 5987, 17, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6004, 25, true);

WriteLiteral(" class=\"alarm-modal-card\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6004, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6029, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Home/_Alerts.cshtml", 6029, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6048, 27, true);

WriteLiteral(" class=\"alarm-modal-header\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6048, 27, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6075, 20, true);

WriteLiteral(">\r\n              <h3");

EndContext("~/Views/Home/_Alerts.cshtml", 6075, 20, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6095, 26, true);

WriteLiteral(" class=\"alarm-modal-title\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6095, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6121, 30, true);

WriteLiteral(" data-i18n=\"alarm_modal_title\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6121, 30, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6151, 47, true);

WriteLiteral(">Xử Lý Cảnh Báo Lỗi</h3>\r\n              <button");

EndContext("~/Views/Home/_Alerts.cshtml", 6151, 47, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6198, 26, true);

WriteLiteral(" class=\"alarm-modal-close\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6198, 26, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6224, 27, true);

WriteLiteral(" id=\"alarm-modal-close-btn\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6224, 27, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6251, 55, true);

WriteLiteral(">&times;</button>\r\n            </div>\r\n            <div");

EndContext("~/Views/Home/_Alerts.cshtml", 6251, 55, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6306, 25, true);

WriteLiteral(" class=\"alarm-modal-body\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6306, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6331, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 6331, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6352, 25, true);

WriteLiteral(" class=\"modal-detail-row\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6352, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6377, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 6377, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6401, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6401, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6422, 33, true);

WriteLiteral(" data-i18n=\"alarm_modal_lbl_time\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6422, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6455, 41, true);

WriteLiteral(">Thời gian:</span>\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 6455, 41, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6496, 19, true);

WriteLiteral(" class=\"detail-val\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6496, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6515, 23, true);

WriteLiteral(" id=\"modal-detail-time\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6515, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6538, 69, true);

WriteLiteral(">14:22:15 12/10/2024</span>\r\n              </div>\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 6538, 69, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6607, 25, true);

WriteLiteral(" class=\"modal-detail-row\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6607, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6632, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 6632, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6656, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6656, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6677, 37, true);

WriteLiteral(" data-i18n=\"alarm_modal_lbl_severity\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6677, 37, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6714, 38, true);

WriteLiteral(">Mức độ:</span>\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 6714, 38, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6752, 19, true);

WriteLiteral(" class=\"detail-val\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6752, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6771, 27, true);

WriteLiteral(" id=\"modal-detail-severity\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6771, 27, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6798, 62, true);

WriteLiteral(">Nghiêm trọng</span>\r\n              </div>\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 6798, 62, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6860, 25, true);

WriteLiteral(" class=\"modal-detail-row\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6860, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6885, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 6885, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6909, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6909, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6930, 33, true);

WriteLiteral(" data-i18n=\"alarm_modal_lbl_code\"");

EndContext("~/Views/Home/_Alerts.cshtml", 6930, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 6963, 49, true);

WriteLiteral(">Thiết bị / Mã lỗi:</span>\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 6963, 49, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7012, 29, true);

WriteLiteral(" class=\"detail-val font-bold\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7012, 29, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7041, 23, true);

WriteLiteral(" id=\"modal-detail-code\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7041, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7064, 79, true);

WriteLiteral(">ERR-DOWNTIME-902 (MÁY ÉP #08)</span>\r\n              </div>\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 7064, 79, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7143, 25, true);

WriteLiteral(" class=\"modal-detail-row\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7143, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7168, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 7168, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7192, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7192, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7213, 33, true);

WriteLiteral(" data-i18n=\"alarm_modal_lbl_desc\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7213, 33, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7246, 43, true);

WriteLiteral(">Mô tả sự cố:</span>\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 7246, 43, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7289, 24, true);

WriteLiteral(" class=\"detail-val desc\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7289, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7313, 23, true);

WriteLiteral(" id=\"modal-detail-desc\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7313, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7336, 130, true);

WriteLiteral(">Áp suất thủy lực vượt ngưỡng cho phép (185 bar). Hệ thống tự động ngắt khẩn cấp." +
"</span>\r\n              </div>\r\n              <div");

EndContext("~/Views/Home/_Alerts.cshtml", 7336, 130, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7466, 25, true);

WriteLiteral(" class=\"modal-detail-row\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7466, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7491, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 7491, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7515, 21, true);

WriteLiteral(" class=\"detail-label\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7515, 21, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7536, 51, true);

WriteLiteral(">Trạng thái hiện tại:</span>\r\n                <span");

EndContext("~/Views/Home/_Alerts.cshtml", 7536, 51, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7587, 19, true);

WriteLiteral(" class=\"detail-val\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7587, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7606, 25, true);

WriteLiteral(" id=\"modal-detail-status\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7606, 25, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7631, 78, true);

WriteLiteral(">Đang xử lý</span>\r\n              </div>\r\n            </div>\r\n            <div");

EndContext("~/Views/Home/_Alerts.cshtml", 7631, 78, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7709, 27, true);

WriteLiteral(" class=\"alarm-modal-footer\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7709, 27, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7736, 24, true);

WriteLiteral(">\r\n              <button");

EndContext("~/Views/Home/_Alerts.cshtml", 7736, 24, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7760, 32, true);

WriteLiteral(" class=\"alarm-modal-btn btn-ack\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7760, 32, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7792, 19, true);

WriteLiteral(" id=\"alarm-btn-ack\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7792, 19, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7811, 61, true);

WriteLiteral(">Xác nhận xử lý (Acknowledge)</button>\r\n              <button");

EndContext("~/Views/Home/_Alerts.cshtml", 7811, 61, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7872, 36, true);

WriteLiteral(" class=\"alarm-modal-btn btn-resolve\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7872, 36, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7908, 23, true);

WriteLiteral(" id=\"alarm-btn-resolve\"");

EndContext("~/Views/Home/_Alerts.cshtml", 7908, 23, true);

BeginContext("~/Views/Home/_Alerts.cshtml", 7931, 129, true);

WriteLiteral(">Đã khắc phục xong (Resolve)</button>\r\n            </div>\r\n          </div>\r\n    " +
"    </div>\r\n\r\n        <!-- 6. VIEW CÀI ĐẶT -->\r\n");

EndContext("~/Views/Home/_Alerts.cshtml", 7931, 129, true);

        }
    }
}
