#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_MachineDetail.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9D92808EEE3F4AF77C2FE7ECCB981A10402DA48C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__MachineDetail_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__MachineDetail_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_MachineDetail.cshtml", 0, 16, true);

WriteLiteral("        <section");

EndContext("~/Views/Home/_MachineDetail.cshtml", 0, 16, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 16, 25, true);

WriteLiteral(" id=\"view-machine-detail\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 16, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 41, 28, true);

WriteLiteral(" class=\"view-section hidden\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 41, 28, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 69, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 69, 17, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 86, 30, true);

WriteLiteral(" class=\"machine-detail-layout\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 86, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 116, 80, true);

WriteLiteral(">\r\n            <!-- Top Action Bar (Back button and Title) -->\r\n            <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 116, 80, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 196, 26, true);

WriteLiteral(" class=\"detail-action-bar\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 196, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 222, 24, true);

WriteLiteral(">\r\n              <button");

EndContext("~/Views/Home/_MachineDetail.cshtml", 222, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 246, 17, true);

WriteLiteral(" class=\"back-btn\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 246, 17, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 263, 29, true);

WriteLiteral(" id=\"machine-detail-back-btn\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 263, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 292, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_MachineDetail.cshtml", 292, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 315, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 315, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 335, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 335, 12, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 347, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 347, 22, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 369, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 369, 19, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 388, 35, true);

WriteLiteral(" style=\"width: 16px; height: 16px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 388, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 423, 26, true);

WriteLiteral(">\r\n                  <line");

EndContext("~/Views/Home/_MachineDetail.cshtml", 423, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 449, 8, true);

WriteLiteral(" x1=\"19\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 449, 8, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 457, 8, true);

WriteLiteral(" y1=\"12\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 457, 8, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 465, 7, true);

WriteLiteral(" x2=\"5\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 465, 7, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 472, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 472, 8, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 480, 37, true);

WriteLiteral("></line>\r\n                  <polyline");

EndContext("~/Views/Home/_MachineDetail.cshtml", 480, 37, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 517, 25, true);

WriteLiteral(" points=\"12 19 5 12 12 5\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 517, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 542, 59, true);

WriteLiteral("></polyline>\r\n                </svg>\r\n                <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 542, 59, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 601, 33, true);

WriteLiteral(" data-i18n=\"btn_back_to_overview\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 601, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 634, 87, true);

WriteLiteral(">Quay lại Tổng quan</span>\r\n              </button>\r\n              \r\n            " +
"  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 634, 87, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 721, 27, true);

WriteLiteral(" class=\"detail-title-block\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 721, 27, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 748, 117, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: center; width" +
": 100%; flex-wrap: wrap; gap: 15px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 748, 117, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 865, 47, true);

WriteLiteral(">\r\n                <div>\r\n                  <h2");

EndContext("~/Views/Home/_MachineDetail.cshtml", 865, 47, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 912, 26, true);

WriteLiteral(" class=\"detail-main-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 912, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 938, 26, true);

WriteLiteral(" id=\"machine-detail-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 938, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 964, 44, true);

WriteLiteral(">MÁY DẬP SỐ #01</h2>\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 964, 44, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1008, 29, true);

WriteLiteral(" class=\"machine-status-badge\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1008, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1037, 25, true);

WriteLiteral(" style=\"margin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1037, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1062, 28, true);

WriteLiteral(">\r\n                    <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1062, 28, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1090, 37, true);

WriteLiteral(" class=\"status-indicator-dot running\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1090, 37, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1127, 31, true);

WriteLiteral(" id=\"machine-detail-status-dot\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1127, 31, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1158, 35, true);

WriteLiteral("></span>\r\n                    <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1158, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1193, 33, true);

WriteLiteral(" class=\"status-text text-running\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1193, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1226, 32, true);

WriteLiteral(" id=\"machine-detail-status-text\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1226, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1258, 94, true);

WriteLiteral(">ĐANG HOẠT ĐỘNG</span>\r\n                  </div>\r\n                </div>\r\n       " +
"         <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1258, 94, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1352, 31, true);

WriteLiteral(" class=\"order-selector-wrapper\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1352, 31, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1383, 170, true);

WriteLiteral(" style=\"display: flex; align-items: center; gap: 10px; background: rgba(255,255,2" +
"55,0.02); border: 1px solid var(--border-color); padding: 6px 12px; border-radiu" +
"s: 10px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1383, 170, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1553, 26, true);

WriteLiteral(">\r\n                  <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1553, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1579, 58, true);

WriteLiteral(" style=\"font-size: 0.85rem; color: var(--text-secondary);\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1579, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1637, 38, true);

WriteLiteral(" data-i18n=\"detail_select_order_label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1637, 38, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1675, 49, true);

WriteLiteral(">Lệnh sản xuất:</span>\r\n                  <select");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1675, 49, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1724, 25, true);

WriteLiteral(" id=\"detail-order-select\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1724, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1749, 235, true);

WriteLiteral(" style=\"background: var(--bg-secondary); border: 1px solid var(--border-color); b" +
"order-radius: 6px; color: var(--text-primary); padding: 6px 12px; font-size: 0.8" +
"5rem; cursor: pointer; outline: none; font-weight: 600; min-width: 160px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1749, 235, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 1984, 207, true);

WriteLiteral(">\r\n                    <!-- Dynamically populated -->\r\n                  </select" +
">\r\n                </div>\r\n              </div>\r\n            </div>\r\n\r\n         " +
"   <!-- Main Detail Grid -->\r\n            <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 1984, 207, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2191, 20, true);

WriteLiteral(" class=\"detail-grid\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2191, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2211, 88, true);

WriteLiteral(">\r\n              <!-- Left Column: Heavy Stamp Animation & Speed -->\r\n           " +
"   <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2211, 88, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2299, 24, true);

WriteLiteral(" class=\"detail-left-col\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2299, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2323, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2323, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2346, 27, true);

WriteLiteral(" class=\"machine-stamp-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2346, 27, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2373, 24, true);

WriteLiteral(" id=\"machine-stamp-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2373, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2397, 25, true);

WriteLiteral(">\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2397, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2422, 29, true);

WriteLiteral(" class=\"stamp-image-viewport\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2422, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2451, 27, true);

WriteLiteral(">\r\n                    <img");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2451, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2478), Tuple.Create("\"", 2519)
            
            #line 36 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_MachineDetail.cshtml"
, Tuple.Create(Tuple.Create("", 2484), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Image/maydap.jpeg")
            
            #line default
            #line hidden
, 2484), false)
);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2520, 21, true);

WriteLiteral(" alt=\"Stamping Press\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2520, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2541, 37, true);

WriteLiteral(" class=\"machine-stamp-image img-open\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2541, 37, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2578, 30, true);

WriteLiteral(" id=\"machine-detail-stamp-img\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2578, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2608, 27, true);

WriteLiteral(">\r\n                    <img");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2608, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2635), Tuple.Create("\"", 2678)
            
            #line 37 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_MachineDetail.cshtml"
, Tuple.Create(Tuple.Create("", 2641), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Image/maydap_2.jpeg")
            
            #line default
            #line hidden
, 2641), false)
);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2679, 21, true);

WriteLiteral(" alt=\"Stamping Press\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2679, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2700, 40, true);

WriteLiteral(" class=\"machine-stamp-image img-pressed\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2700, 40, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2740, 32, true);

WriteLiteral(" id=\"machine-detail-stamp-img-2\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2740, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2772, 82, true);

WriteLiteral(">\r\n                    <!-- Glow indicator on impact -->\r\n                    <di" +
"v");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2772, 82, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2854, 19, true);

WriteLiteral(" class=\"stamp-glow\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2854, 19, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2873, 31, true);

WriteLiteral(" id=\"machine-detail-stamp-glow\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2873, 31, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 2904, 144, true);

WriteLiteral("></div>\r\n                  </div>\r\n                </div>\r\n                <!-- B" +
"ảng thông số kỹ thuật (14 thuộc tính) -->\r\n                <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 2904, 144, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3048, 32, true);

WriteLiteral(" class=\"detail-attributes-panel\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3048, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3080, 134, true);

WriteLiteral(" style=\"margin-top: 24px; background: var(--bg-secondary); border: 1px solid var(" +
"--border-color); border-radius: 20px; padding: 20px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3080, 134, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3214, 25, true);

WriteLiteral(">\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3214, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3239, 21, true);

WriteLiteral(" class=\"panel-header\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3239, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3260, 99, true);

WriteLiteral(" style=\"margin-bottom: 12px; border-bottom: 1px solid rgba(255,255,255,0.05); pad" +
"ding-bottom: 8px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3260, 99, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3359, 26, true);

WriteLiteral(">\r\n                    <h3");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3359, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3385, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3385, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3405, 27, true);

WriteLiteral(" style=\"font-size: 0.9rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3405, 27, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3432, 29, true);

WriteLiteral(" data-i18n=\"attributes_title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3432, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3461, 84, true);

WriteLiteral(">THÔNG SỐ KỸ THUẬT THIẾT BỊ</h3>\r\n                  </div>\r\n                  <ta" +
"ble");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3461, 84, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3545, 25, true);

WriteLiteral(" class=\"attributes-table\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3545, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3570, 95, true);

WriteLiteral(" style=\"width: 100%; border-collapse: collapse; font-size: 0.8rem; color: var(--t" +
"ext-primary);\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3570, 95, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3665, 29, true);

WriteLiteral(">\r\n                    <tbody");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3665, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3694, 37, true);

WriteLiteral(" id=\"machine-detail-attributes-tbody\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3694, 37, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3731, 247, true);

WriteLiteral(">\r\n                      <!-- Trình bày động qua JS -->\r\n                    </tb" +
"ody>\r\n                  </table>\r\n                </div>\r\n              </div>\r\n" +
"\r\n              <!-- Right Column: Product Info, Stats & Chart -->\r\n            " +
"  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3731, 247, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 3978, 25, true);

WriteLiteral(" class=\"detail-right-col\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 3978, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4003, 75, true);

WriteLiteral(">\r\n                <!-- Product Information Panel -->\r\n                <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4003, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4078, 29, true);

WriteLiteral(" class=\"detail-product-panel\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4078, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4107, 29, true);

WriteLiteral(" style=\"margin-bottom: 24px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4107, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4136, 25, true);

WriteLiteral(">\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4136, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4161, 21, true);

WriteLiteral(" class=\"panel-header\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4161, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4182, 29, true);

WriteLiteral(" style=\"margin-bottom: 15px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4182, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4211, 26, true);

WriteLiteral(">\r\n                    <h3");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4211, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4237, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4237, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4257, 31, true);

WriteLiteral(" data-i18n=\"product_info_title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4257, 31, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4288, 74, true);

WriteLiteral(">THÔNG TIN SẢN PHẨM</h3>\r\n                  </div>\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4288, 74, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4362, 33, true);

WriteLiteral(" class=\"product-info-grid-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4362, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4395, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4395, 27, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4422, 33, true);

WriteLiteral(" class=\"product-info-item-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4422, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4455, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4455, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4485, 26, true);

WriteLiteral(" class=\"info-label-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4485, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4511, 49, true);

WriteLiteral(">Mã sản phẩm:</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4511, 49, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4560, 26, true);

WriteLiteral(" class=\"info-value-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4560, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4586, 25, true);

WriteLiteral(" id=\"product-detail-code\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4586, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4611, 63, true);

WriteLiteral(">-</span>\r\n                    </div>\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4611, 63, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4674, 33, true);

WriteLiteral(" class=\"product-info-item-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4674, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4707, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4707, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4737, 26, true);

WriteLiteral(" class=\"info-label-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4737, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4763, 50, true);

WriteLiteral(">Tên sản phẩm:</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4763, 50, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4813, 26, true);

WriteLiteral(" class=\"info-value-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4813, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4839, 25, true);

WriteLiteral(" id=\"product-detail-name\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4839, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4864, 63, true);

WriteLiteral(">-</span>\r\n                    </div>\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4864, 63, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4927, 33, true);

WriteLiteral(" class=\"product-info-item-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4927, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4960, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4960, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 4990, 26, true);

WriteLiteral(" class=\"info-label-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 4990, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5016, 51, true);

WriteLiteral(">Lệnh sản xuất:</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5016, 51, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5067, 26, true);

WriteLiteral(" class=\"info-value-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5067, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5093, 26, true);

WriteLiteral(" id=\"product-detail-batch\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5093, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5119, 63, true);

WriteLiteral(">-</span>\r\n                    </div>\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5119, 63, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5182, 33, true);

WriteLiteral(" class=\"product-info-item-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5182, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5215, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5215, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5245, 26, true);

WriteLiteral(" class=\"info-label-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5245, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5271, 55, true);

WriteLiteral(">Sản lượng dự kiến:</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5271, 55, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5326, 26, true);

WriteLiteral(" class=\"info-value-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5326, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5352, 25, true);

WriteLiteral(" id=\"product-detail-plan\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5352, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5377, 164, true);

WriteLiteral(">-</span>\r\n                    </div>\r\n                  </div>\r\n                " +
"</div>\r\n\r\n                <!-- Daily Stats Panel (Phần 1) -->\r\n                <" +
"div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5377, 164, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5541, 29, true);

WriteLiteral(" class=\"detail-section-part1\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5541, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5570, 29, true);

WriteLiteral(" style=\"margin-bottom: 28px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5570, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5599, 25, true);

WriteLiteral(">\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5599, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5624, 35, true);

WriteLiteral(" class=\"section-part-header-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5624, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5659, 125, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: center; margi" +
"n-bottom: 18px; flex-wrap: wrap; gap: 10px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5659, 125, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5784, 55, true);

WriteLiteral(">\r\n                    <div>\r\n                      <h3");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5784, 55, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5839, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5839, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5859, 30, true);

WriteLiteral(" data-i18n=\"part1_daily_title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5859, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5889, 50, true);

WriteLiteral(">THỐNG KÊ THEO NGÀY</h3>\r\n                      <p");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5889, 50, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5939, 23, true);

WriteLiteral(" class=\"panel-subtitle\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5939, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 5962, 58, true);

WriteLiteral(" style=\"font-size: 0.75rem; color: var(--text-secondary);\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 5962, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6020, 96, true);

WriteLiteral(">Chỉ số vận hành chi tiết trong 24 giờ</p>\r\n                    </div>\r\n         " +
"           <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6020, 96, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6116, 42, true);

WriteLiteral(" class=\"single-date-picker-wrapper-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6116, 42, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6158, 54, true);

WriteLiteral(" style=\"display: flex; align-items: center; gap: 8px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6158, 54, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6212, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6212, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6242, 32, true);

WriteLiteral(" class=\"datepicker-label-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6242, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6274, 57, true);

WriteLiteral(" style=\"font-size: 0.8rem; color: var(--text-secondary);\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6274, 57, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6331, 48, true);

WriteLiteral(">Chọn ngày:</span>\r\n                      <input");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6331, 48, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6379, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6379, 12, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6391, 24, true);

WriteLiteral(" id=\"detail-single-date\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6391, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6415, 33, true);

WriteLiteral(" class=\"date-picker-input-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6415, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6448, 88, true);

WriteLiteral(" readonly>\r\n                    </div>\r\n                  </div>\r\n               " +
"   <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6448, 88, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6536, 26, true);

WriteLiteral(" class=\"detail-stats-grid\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6536, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6562, 75, true);

WriteLiteral(">\r\n                    <!-- 1. Sản lượng ngày -->\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6562, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6637, 25, true);

WriteLiteral(" class=\"detail-stat-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6637, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6662, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6662, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6692, 24, true);

WriteLiteral(" class=\"stat-card-label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6692, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6716, 51, true);

WriteLiteral(">SẢN LƯỢNG NGÀY</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6716, 51, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6767, 40, true);

WriteLiteral(" class=\"stat-card-value value-highlight\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6767, 40, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6807, 39, true);

WriteLiteral(" id=\"machine-detail-strokes-target-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6807, 39, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6846, 38, true);

WriteLiteral(">0</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6846, 38, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6884, 23, true);

WriteLiteral(" class=\"stat-card-desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6884, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6907, 58, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.72rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6907, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 6965, 132, true);

WriteLiteral(">Sản lượng trong ngày</span>\r\n                    </div>\r\n                    <!-" +
"- 2. Tiến độ đơn hàng -->\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 6965, 132, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7097, 25, true);

WriteLiteral(" class=\"detail-stat-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7097, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7122, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7122, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7152, 24, true);

WriteLiteral(" class=\"stat-card-label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7152, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7176, 69, true);

WriteLiteral(">SẢN LƯỢNG THỰC TẾ / LỆNH SẢN XUẤT</span>\r\n                      <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7176, 69, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7245, 95, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: baseline; mar" +
"gin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7245, 95, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7340, 32, true);

WriteLiteral(">\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7340, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7372, 24, true);

WriteLiteral(" class=\"stat-card-value\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7372, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7396, 38, true);

WriteLiteral(" id=\"machine-detail-strokes-order-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7396, 38, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7434, 23, true);

WriteLiteral(" style=\"margin-top: 0;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7434, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7457, 44, true);

WriteLiteral(">0 / 0</span>\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7457, 44, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7501, 38, true);

WriteLiteral(" id=\"machine-detail-strokes-order-pct\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7501, 38, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7539, 61, true);

WriteLiteral(" style=\"color: #00e676; font-weight: 700; font-size: 1.1rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7539, 61, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7600, 69, true);

WriteLiteral(">0%</span>\r\n                      </div>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7600, 69, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7669, 23, true);

WriteLiteral(" class=\"stat-card-desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7669, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7692, 75, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.72rem; margin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7692, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7767, 159, true);

WriteLiteral(">= Thực tế / Tổng lệnh sản xuất</span>\r\n                    </div>\r\n             " +
"       <!-- 3. Thời gian máy chạy / Thời gian ca -->\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7767, 159, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7926, 25, true);

WriteLiteral(" class=\"detail-stat-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7926, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7951, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7951, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 7981, 24, true);

WriteLiteral(" class=\"stat-card-label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 7981, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8005, 69, true);

WriteLiteral(">THỜI GIAN MÁY CHẠY / THỜI GIAN CA</span>\r\n                      <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8005, 69, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8074, 95, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: baseline; mar" +
"gin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8074, 95, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8169, 32, true);

WriteLiteral(">\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8169, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8201, 24, true);

WriteLiteral(" class=\"stat-card-value\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8201, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8225, 34, true);

WriteLiteral(" id=\"machine-detail-run-shift-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8225, 34, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8259, 23, true);

WriteLiteral(" style=\"margin-top: 0;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8259, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8282, 58, true);

WriteLiteral(">00:00:00 / 08:00:00</span>\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8282, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8340, 33, true);

WriteLiteral(" id=\"machine-detail-time-eff-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8340, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8373, 61, true);

WriteLiteral(" style=\"color: #00e676; font-weight: 700; font-size: 1.1rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8373, 61, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8434, 69, true);

WriteLiteral(">0%</span>\r\n                      </div>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8434, 69, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8503, 23, true);

WriteLiteral(" class=\"stat-card-desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8503, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8526, 75, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.72rem; margin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8526, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8601, 170, true);

WriteLiteral(">= Thời gian máy chạy / Thời gian ca</span>\r\n                    </div>\r\n        " +
"            <!-- 4. Thời gian chạy thử / Thời gian máy chạy -->\r\n               " +
"     <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8601, 170, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8771, 25, true);

WriteLiteral(" class=\"detail-stat-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8771, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8796, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8796, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8826, 24, true);

WriteLiteral(" class=\"stat-card-label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8826, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8850, 75, true);

WriteLiteral(">THỜI GIAN CHẠY THỬ / THỜI GIAN MÁY CHẠY</span>\r\n                      <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8850, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 8925, 95, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: baseline; mar" +
"gin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 8925, 95, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9020, 32, true);

WriteLiteral(">\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9020, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9052, 24, true);

WriteLiteral(" class=\"stat-card-value\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9052, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9076, 34, true);

WriteLiteral(" id=\"machine-detail-trial-run-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9076, 34, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9110, 23, true);

WriteLiteral(" style=\"margin-top: 0;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9110, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9133, 58, true);

WriteLiteral(">00:00:00 / 00:00:00</span>\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9133, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9191, 30, true);

WriteLiteral(" id=\"machine-detail-trial-pct\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9191, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9221, 61, true);

WriteLiteral(" style=\"color: #00e676; font-weight: 700; font-size: 1.1rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9221, 61, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9282, 69, true);

WriteLiteral(">0%</span>\r\n                      </div>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9282, 69, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9351, 23, true);

WriteLiteral(" class=\"stat-card-desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9351, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9374, 75, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.72rem; margin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9374, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9449, 176, true);

WriteLiteral(">= Thời gian chạy thử / Thời gian máy chạy</span>\r\n                    </div>\r\n  " +
"                  <!-- 5. Thời gian sản xuất / Thời gian máy chạy -->\r\n         " +
"           <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9449, 176, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9625, 25, true);

WriteLiteral(" class=\"detail-stat-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9625, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9650, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9650, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9680, 24, true);

WriteLiteral(" class=\"stat-card-label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9680, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9704, 75, true);

WriteLiteral(">THỜI GIAN SẢN XUẤT / THỜI GIAN MÁY CHẠY</span>\r\n                      <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9704, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9779, 95, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: baseline; mar" +
"gin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9779, 95, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9874, 32, true);

WriteLiteral(">\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9874, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9906, 24, true);

WriteLiteral(" class=\"stat-card-value\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9906, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9930, 33, true);

WriteLiteral(" id=\"machine-detail-prod-run-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9930, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9963, 23, true);

WriteLiteral(" style=\"margin-top: 0;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9963, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 9986, 58, true);

WriteLiteral(">00:00:00 / 00:00:00</span>\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 9986, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10044, 29, true);

WriteLiteral(" id=\"machine-detail-prod-pct\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10044, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10073, 61, true);

WriteLiteral(" style=\"color: #00e676; font-weight: 700; font-size: 1.1rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10073, 61, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10134, 69, true);

WriteLiteral(">0%</span>\r\n                      </div>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10134, 69, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10203, 23, true);

WriteLiteral(" class=\"stat-card-desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10203, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10226, 75, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.72rem; margin-top: 4px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10226, 75, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10301, 163, true);

WriteLiteral(">= Thời gian sản xuất / Thời gian máy chạy</span>\r\n                    </div>\r\n  " +
"                  <!-- 6. Thời gian còn lại ước tính -->\r\n                    <d" +
"iv");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10301, 163, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10464, 25, true);

WriteLiteral(" class=\"detail-stat-card\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10464, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10489, 30, true);

WriteLiteral(">\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10489, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10519, 24, true);

WriteLiteral(" class=\"stat-card-label\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10519, 24, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10543, 63, true);

WriteLiteral(">THỜI GIAN CÒN LẠI ƯỚC TÍNH</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10543, 63, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10606, 40, true);

WriteLiteral(" class=\"stat-card-value value-highlight\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10606, 40, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10646, 28, true);

WriteLiteral(" id=\"machine-detail-est-val\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10646, 28, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10674, 45, true);

WriteLiteral(">00:00:00</span>\r\n                      <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10674, 45, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10719, 23, true);

WriteLiteral(" class=\"stat-card-desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10719, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10742, 58, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.72rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10742, 58, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 10800, 215, true);

WriteLiteral(">Ước tính thời gian còn lại hoàn thành</span>\r\n                    </div>\r\n      " +
"            </div>\r\n                </div>\r\n\r\n                <!-- Production Tr" +
"end & Filters Panel (Phần 2) -->\r\n                <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 10800, 215, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11015, 29, true);

WriteLiteral(" class=\"detail-section-part2\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11015, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11044, 25, true);

WriteLiteral(">\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11044, 25, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11069, 35, true);

WriteLiteral(" class=\"section-part-header-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11069, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11104, 194, true);

WriteLiteral(" style=\"display: flex; justify-content: space-between; align-items: flex-start; m" +
"argin-bottom: 20px; flex-wrap: wrap; gap: 15px; border-top: 1px solid rgba(255,2" +
"55,255,0.05); padding-top: 24px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11104, 194, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11298, 55, true);

WriteLiteral(">\r\n                    <div>\r\n                      <h3");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11298, 55, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11353, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11353, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11373, 30, true);

WriteLiteral(" id=\"trend-chart-title-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11373, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11403, 50, true);

WriteLiteral(">XU HƯỚNG SẢN LƯỢNG</h3>\r\n                      <p");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11403, 50, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11453, 23, true);

WriteLiteral(" class=\"panel-subtitle\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11453, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11476, 111, true);

WriteLiteral(">Biểu đồ xu hướng sản lượng dập và cảnh báo liên quan</p>\r\n                    </" +
"div>\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11476, 111, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11587, 39, true);

WriteLiteral(" class=\"part2-filters-container-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11587, 39, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11626, 72, true);

WriteLiteral(" style=\"display: flex; align-items: center; gap: 12px; flex-wrap: wrap;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11626, 72, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11698, 80, true);

WriteLiteral(">\r\n                      <!-- Toggle button Mode -->\r\n                      <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11698, 80, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11778, 35, true);

WriteLiteral(" class=\"toggle-mode-wrapper-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11778, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11813, 133, true);

WriteLiteral(" style=\"display: flex; background: rgba(255,255,255,0.03); border: 1px solid var(" +
"--border-color); border-radius: 10px; padding: 3px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11813, 133, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11946, 34, true);

WriteLiteral(">\r\n                        <button");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11946, 34, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11980, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11980, 14, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 11994, 38, true);

WriteLiteral(" class=\"toggle-mode-btn-custom active\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 11994, 38, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12032, 16, true);

WriteLiteral(" data-mode=\"day\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12032, 16, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12048, 192, true);

WriteLiteral(" style=\"padding: 6px 14px; border: none; background: transparent; color: var(--te" +
"xt-secondary); border-radius: 8px; font-size: 0.8rem; cursor: pointer; font-weig" +
"ht: 500; transition: all 0.2s;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12048, 192, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12240, 52, true);

WriteLiteral(">Theo ngày</button>\r\n                        <button");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12240, 52, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12292, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12292, 14, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12306, 31, true);

WriteLiteral(" class=\"toggle-mode-btn-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12306, 31, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12337, 18, true);

WriteLiteral(" data-mode=\"month\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12337, 18, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12355, 192, true);

WriteLiteral(" style=\"padding: 6px 14px; border: none; background: transparent; color: var(--te" +
"xt-secondary); border-radius: 8px; font-size: 0.8rem; cursor: pointer; font-weig" +
"ht: 500; transition: all 0.2s;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12355, 192, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12547, 185, true);

WriteLiteral(">Theo tháng</button>\r\n                      </div>\r\n                      \r\n     " +
"                 <!-- Date Range Pickers (shown when Day mode is active) -->\r\n  " +
"                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12547, 185, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12732, 36, true);

WriteLiteral(" class=\"range-picker-wrapper-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12732, 36, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12768, 21, true);

WriteLiteral(" id=\"part2-range-day\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12768, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12789, 54, true);

WriteLiteral(" style=\"display: flex; align-items: center; gap: 6px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12789, 54, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12843, 33, true);

WriteLiteral(">\r\n                        <input");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12843, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12876, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12876, 12, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12888, 22, true);

WriteLiteral(" id=\"part2-date-range\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12888, 22, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12910, 33, true);

WriteLiteral(" class=\"date-picker-input-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12910, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12943, 26, true);

WriteLiteral(" style=\"min-width: 200px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12943, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 12969, 157, true);

WriteLiteral(" readonly>\r\n                      </div>\r\n \r\n                      <!-- Month Ran" +
"ge Pickers (shown when Month mode is active) -->\r\n                      <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 12969, 157, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13126, 43, true);

WriteLiteral(" class=\"range-picker-wrapper-custom hidden\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13126, 43, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13169, 23, true);

WriteLiteral(" id=\"part2-range-month\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13169, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13192, 54, true);

WriteLiteral(" style=\"display: flex; align-items: center; gap: 6px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13192, 54, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13246, 33, true);

WriteLiteral(">\r\n                        <input");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13246, 33, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13279, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13279, 12, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13291, 23, true);

WriteLiteral(" id=\"part2-month-start\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13291, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13314, 34, true);

WriteLiteral(" class=\"month-picker-input-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13314, 34, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13348, 41, true);

WriteLiteral(" readonly>\r\n                        <span");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13348, 41, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13389, 22, true);

WriteLiteral(" class=\"range-divider\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13389, 22, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13411, 57, true);

WriteLiteral(" style=\"color: var(--text-secondary); font-size: 0.8rem;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13411, 57, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13468, 43, true);

WriteLiteral(">đến</span>\r\n                        <input");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13468, 43, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13511, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13511, 12, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13523, 21, true);

WriteLiteral(" id=\"part2-month-end\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13523, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13544, 34, true);

WriteLiteral(" class=\"month-picker-input-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13544, 34, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13578, 125, true);

WriteLiteral(" readonly>\r\n                      </div>\r\n\r\n                      <!-- Export Exc" +
"el Button -->\r\n                      <button");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13578, 125, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13703, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13703, 14, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13717, 32, true);

WriteLiteral(" class=\"btn-export-excel-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13717, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13749, 22, true);

WriteLiteral(" id=\"btn-export-excel\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13749, 22, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 13771, 264, true);

WriteLiteral(@" style=""display: flex; align-items: center; gap: 8px; padding: 8px 16px; background: rgba(0, 210, 255, 0.1); border: 1px solid rgba(0, 210, 255, 0.3); color: #00d2ff; border-radius: 10px; font-size: 0.8rem; cursor: pointer; font-weight: 600; transition: all 0.2s;""");

EndContext("~/Views/Home/_MachineDetail.cshtml", 13771, 264, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14035, 31, true);

WriteLiteral(">\r\n                        <svg");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14035, 31, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14066, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14066, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14086, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14086, 12, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14098, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14098, 22, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14120, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14120, 19, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14139, 19, true);

WriteLiteral(" class=\"excel-icon\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14139, 19, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14158, 35, true);

WriteLiteral(" style=\"width: 14px; height: 14px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14158, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14193, 34, true);

WriteLiteral(">\r\n                          <path");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14193, 34, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14227, 46, true);

WriteLiteral(" d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14227, 46, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14273, 45, true);

WriteLiteral("></path>\r\n                          <polyline");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14273, 45, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14318, 26, true);

WriteLiteral(" points=\"7 10 12 15 17 10\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14318, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14344, 45, true);

WriteLiteral("></polyline>\r\n                          <line");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14344, 45, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14389, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14389, 8, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14397, 8, true);

WriteLiteral(" y1=\"15\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14397, 8, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14405, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14405, 8, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14413, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14413, 7, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14420, 244, true);

WriteLiteral("></line>\r\n                        </svg>\r\n                        <span>Xuất Exce" +
"l</span>\r\n                      </button>\r\n                    </div>\r\n         " +
"         </div>\r\n\r\n                  <!-- Chart Wrapper -->\r\n                  <" +
"div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14420, 244, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14664, 32, true);

WriteLiteral(" class=\"chart-container-wrapper\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14664, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14696, 188, true);

WriteLiteral(" style=\"position: relative; height: 260px; width: 100%; margin-bottom: 28px; back" +
"ground: rgba(255,255,255,0.01); border-radius: 16px; padding: 15px; border: 1px " +
"solid var(--border-color);\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14696, 188, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14884, 30, true);

WriteLiteral(">\r\n                    <canvas");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14884, 30, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14914, 26, true);

WriteLiteral(" id=\"machine-detail-chart\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14914, 26, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 14940, 125, true);

WriteLiteral("></canvas>\r\n                  </div>\r\n\r\n                  <!-- Related Alarms (no" +
"w inside Part 2) -->\r\n                  <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 14940, 125, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15065, 35, true);

WriteLiteral(" class=\"detail-alarms-panel-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15065, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15100, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15100, 27, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15127, 21, true);

WriteLiteral(" class=\"panel-header\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15127, 21, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15148, 29, true);

WriteLiteral(" style=\"margin-bottom: 15px;\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15148, 29, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15177, 28, true);

WriteLiteral(">\r\n                      <h3");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15177, 28, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15205, 20, true);

WriteLiteral(" class=\"panel-title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15205, 20, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15225, 40, true);

WriteLiteral(" data-i18n=\"machine_detail_alarms_title\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15225, 40, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15265, 50, true);

WriteLiteral(">CẢNH BÁO LIÊN QUAN</h3>\r\n                      <p");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15265, 50, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15315, 23, true);

WriteLiteral(" class=\"panel-subtitle\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15315, 23, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15338, 39, true);

WriteLiteral(" data-i18n=\"machine_detail_alarms_desc\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15338, 39, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15377, 107, true);

WriteLiteral(">Các cảnh báo và sự cố trong khoảng thời gian lọc</p>\r\n                    </div>" +
"\r\n                    <div");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15377, 107, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15484, 35, true);

WriteLiteral(" class=\"machine-alarms-list-custom\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15484, 35, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15519, 32, true);

WriteLiteral(" id=\"machine-detail-alarms-list\"");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15519, 32, true);

BeginContext("~/Views/Home/_MachineDetail.cshtml", 15551, 257, true);

WriteLiteral(@">
                      <!-- Dynamically rendered via JS -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <!-- 3. VIEW LỊCH SỬ -->
");

EndContext("~/Views/Home/_MachineDetail.cshtml", 15551, 257, true);

        }
    }
}
