#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_Sidebar.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CCA85022AC6D86A3085F47A9EE3C554CAD98BC69"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__Sidebar_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__Sidebar_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_Sidebar.cshtml", 0, 10, true);

WriteLiteral("    <aside");

EndContext("~/Views/Home/_Sidebar.cshtml", 0, 10, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 10, 16, true);

WriteLiteral(" class=\"sidebar\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 10, 16, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 26, 13, true);

WriteLiteral(" id=\"sidebar\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 26, 13, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 39, 40, true);

WriteLiteral(">\r\n      <!-- Logo Brand -->\r\n      <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 39, 40, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 79, 22, true);

WriteLiteral(" class=\"sidebar-brand\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 79, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 101, 15, true);

WriteLiteral(">\r\n        <img");

EndContext("~/Views/Home/_Sidebar.cshtml", 101, 15, true);

WriteAttribute("src", Tuple.Create(" src=\"", 116), Tuple.Create("\"", 154)
            
            #line 4 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_Sidebar.cshtml"
, Tuple.Create(Tuple.Create("", 122), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Image/logo.png")
            
            #line default
            #line hidden
, 122), false)
);

BeginContext("~/Views/Home/_Sidebar.cshtml", 155, 21, true);

WriteLiteral(" alt=\"HaiPhuong Logo\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 155, 21, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 176, 23, true);

WriteLiteral(" class=\"brand-logo-img\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 176, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 199, 61, true);

WriteLiteral(">\r\n      </div>\r\n\r\n      <!-- Navigation Menu -->\r\n      <nav");

EndContext("~/Views/Home/_Sidebar.cshtml", 199, 61, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 260, 20, true);

WriteLiteral(" class=\"sidebar-nav\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 260, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 280, 13, true);

WriteLiteral(">\r\n        <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 280, 13, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 293, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 293, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 302, 24, true);

WriteLiteral(" class=\"nav-item active\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 302, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 326, 20, true);

WriteLiteral(" data-tab=\"overview\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 326, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 346, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 346, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 363, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 363, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 380, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 380, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 400, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 400, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 412, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 412, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 434, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 434, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 451, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 451, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 474, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 474, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 498, 20, true);

WriteLiteral(">\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 498, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 518, 51, true);

WriteLiteral(" d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 518, 51, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 569, 31, true);

WriteLiteral("></path>\r\n            <polyline");

EndContext("~/Views/Home/_Sidebar.cshtml", 569, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 600, 31, true);

WriteLiteral(" points=\"9 22 9 12 15 12 15 22\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 600, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 631, 90, true);

WriteLiteral("></polyline>\r\n          </svg>\r\n          <span>Máy dập</span>\r\n        </a>\r\n   " +
"     <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 631, 90, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 721, 24, true);

WriteLiteral(" class=\"nav-item-parent\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 721, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 745, 15, true);

WriteLiteral(">\r\n          <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 745, 15, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 760, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 760, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 769, 37, true);

WriteLiteral(" class=\"nav-item nav-dropdown-toggle\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 769, 37, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 806, 19, true);

WriteLiteral(">\r\n            <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 806, 19, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 825, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 825, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 842, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 842, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 862, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 862, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 874, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 874, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 896, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 896, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 913, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 913, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 936, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 936, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 960, 22, true);

WriteLiteral(">\r\n              <rect");

EndContext("~/Views/Home/_Sidebar.cshtml", 960, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 982, 6, true);

WriteLiteral(" x=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 982, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 988, 6, true);

WriteLiteral(" y=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 988, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 994, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 994, 10, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1004, 11, true);

WriteLiteral(" height=\"9\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1004, 11, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1015, 29, true);

WriteLiteral("></rect>\r\n              <rect");

EndContext("~/Views/Home/_Sidebar.cshtml", 1015, 29, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1044, 7, true);

WriteLiteral(" x=\"14\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1044, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1051, 6, true);

WriteLiteral(" y=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1051, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1057, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1057, 10, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1067, 11, true);

WriteLiteral(" height=\"5\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1067, 11, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1078, 29, true);

WriteLiteral("></rect>\r\n              <rect");

EndContext("~/Views/Home/_Sidebar.cshtml", 1078, 29, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1107, 7, true);

WriteLiteral(" x=\"14\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1107, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1114, 7, true);

WriteLiteral(" y=\"12\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1114, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1121, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1121, 10, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1131, 11, true);

WriteLiteral(" height=\"9\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1131, 11, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1142, 29, true);

WriteLiteral("></rect>\r\n              <rect");

EndContext("~/Views/Home/_Sidebar.cshtml", 1142, 29, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1171, 6, true);

WriteLiteral(" x=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1171, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1177, 7, true);

WriteLiteral(" y=\"16\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1177, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1184, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1184, 10, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1194, 11, true);

WriteLiteral(" height=\"5\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1194, 11, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1205, 80, true);

WriteLiteral("></rect>\r\n            </svg>\r\n            <span>Máy vít</span>\r\n            <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 1205, 80, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1285, 21, true);

WriteLiteral(" class=\"expand-arrow\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1285, 21, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1306, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1306, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1326, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1326, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1338, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1338, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1360, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1360, 19, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1379, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1379, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1402, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1402, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1426, 26, true);

WriteLiteral(">\r\n              <polyline");

EndContext("~/Views/Home/_Sidebar.cshtml", 1426, 26, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1452, 24, true);

WriteLiteral(" points=\"9 18 15 12 9 6\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1452, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1476, 63, true);

WriteLiteral("></polyline>\r\n            </svg>\r\n          </a>\r\n          <ul");

EndContext("~/Views/Home/_Sidebar.cshtml", 1476, 63, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1539, 24, true);

WriteLiteral(" class=\"sidebar-submenu\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1539, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1563, 37, true);

WriteLiteral(">\r\n            <li>\r\n              <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 1563, 37, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1600, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1600, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1609, 30, true);

WriteLiteral(" class=\"nav-item submenu-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1609, 30, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1639, 28, true);

WriteLiteral(" data-tab=\"overview-heading\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1639, 28, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1667, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Sidebar.cshtml", 1667, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1691, 12, true);

WriteLiteral(" class=\"dot\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1691, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1703, 125, true);

WriteLiteral("></span>\r\n                <span>Máy đấm vít</span>\r\n              </a>\r\n         " +
"   </li>\r\n            <li>\r\n              <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 1703, 125, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1828, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1828, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1837, 30, true);

WriteLiteral(" class=\"nav-item submenu-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1837, 30, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1867, 30, true);

WriteLiteral(" data-tab=\"overview-threading\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1867, 30, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1897, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Sidebar.cshtml", 1897, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1921, 12, true);

WriteLiteral(" class=\"dot\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 1921, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 1933, 136, true);

WriteLiteral("></span>\r\n                <span>Máy ren vít</span>\r\n              </a>\r\n         " +
"   </li>\r\n          </ul>\r\n        </div>\r\n\r\n        <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 1933, 136, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2069, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2069, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2078, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2078, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2095, 29, true);

WriteLiteral(" data-tab=\"production-orders\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2095, 29, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2124, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 2124, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2141, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2141, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2158, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2158, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2178, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2178, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2190, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2190, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2212, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2212, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2229, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2229, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2252, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2252, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2276, 20, true);

WriteLiteral(">\r\n            <rect");

EndContext("~/Views/Home/_Sidebar.cshtml", 2276, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2296, 6, true);

WriteLiteral(" x=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2296, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2302, 6, true);

WriteLiteral(" y=\"4\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2302, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2308, 11, true);

WriteLiteral(" width=\"18\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2308, 11, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2319, 12, true);

WriteLiteral(" height=\"18\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2319, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2331, 7, true);

WriteLiteral(" rx=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2331, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2338, 7, true);

WriteLiteral(" ry=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2338, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2345, 27, true);

WriteLiteral("></rect>\r\n            <line");

EndContext("~/Views/Home/_Sidebar.cshtml", 2345, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2372, 8, true);

WriteLiteral(" x1=\"16\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2372, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2380, 7, true);

WriteLiteral(" y1=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2380, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2387, 8, true);

WriteLiteral(" x2=\"16\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2387, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2395, 7, true);

WriteLiteral(" y2=\"6\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2395, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2402, 27, true);

WriteLiteral("></line>\r\n            <line");

EndContext("~/Views/Home/_Sidebar.cshtml", 2402, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2429, 7, true);

WriteLiteral(" x1=\"8\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2429, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2436, 7, true);

WriteLiteral(" y1=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2436, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2443, 7, true);

WriteLiteral(" x2=\"8\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2443, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2450, 7, true);

WriteLiteral(" y2=\"6\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2450, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2457, 27, true);

WriteLiteral("></line>\r\n            <line");

EndContext("~/Views/Home/_Sidebar.cshtml", 2457, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2484, 7, true);

WriteLiteral(" x1=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2484, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2491, 8, true);

WriteLiteral(" y1=\"10\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2491, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2499, 8, true);

WriteLiteral(" x2=\"21\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2499, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2507, 8, true);

WriteLiteral(" y2=\"10\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2507, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2515, 100, true);

WriteLiteral("></line>\r\n          </svg>\r\n          <span>Quản lý lệnh sản xuất</span>\r\n       " +
" </a>\r\n\r\n        <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 2515, 100, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2615, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2615, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2624, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2624, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2641, 19, true);

WriteLiteral(" data-tab=\"history\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2641, 19, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2660, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 2660, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2677, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2677, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2694, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2694, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2714, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2714, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2726, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2726, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2748, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2748, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2765, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2765, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2788, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2788, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2812, 24, true);

WriteLiteral(">\r\n            <polyline");

EndContext("~/Views/Home/_Sidebar.cshtml", 2812, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2836, 26, true);

WriteLiteral(" points=\"12 8 12 12 14 14\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2836, 26, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2862, 31, true);

WriteLiteral("></polyline>\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 2862, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2893, 80, true);

WriteLiteral(" d=\"M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8z\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 2893, 80, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 2973, 84, true);

WriteLiteral("></path>\r\n          </svg>\r\n          <span>Lịch sử</span>\r\n        </a>\r\n       " +
" <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 2973, 84, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3057, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3057, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3066, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3066, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3083, 18, true);

WriteLiteral(" data-tab=\"report\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3083, 18, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3101, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 3101, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3118, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3118, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3135, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3135, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3155, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3155, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3167, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3167, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3189, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3189, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3206, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3206, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3229, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3229, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3253, 20, true);

WriteLiteral(">\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 3253, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3273, 63, true);

WriteLiteral(" d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3273, 63, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3336, 31, true);

WriteLiteral("></path>\r\n            <polyline");

EndContext("~/Views/Home/_Sidebar.cshtml", 3336, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3367, 24, true);

WriteLiteral(" points=\"14 2 14 8 20 8\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3367, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3391, 31, true);

WriteLiteral("></polyline>\r\n            <line");

EndContext("~/Views/Home/_Sidebar.cshtml", 3391, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3422, 8, true);

WriteLiteral(" x1=\"16\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3422, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3430, 8, true);

WriteLiteral(" y1=\"13\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3430, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3438, 7, true);

WriteLiteral(" x2=\"8\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3438, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3445, 8, true);

WriteLiteral(" y2=\"13\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3445, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3453, 27, true);

WriteLiteral("></line>\r\n            <line");

EndContext("~/Views/Home/_Sidebar.cshtml", 3453, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3480, 8, true);

WriteLiteral(" x1=\"16\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3480, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3488, 8, true);

WriteLiteral(" y1=\"17\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3488, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3496, 7, true);

WriteLiteral(" x2=\"8\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3496, 7, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3503, 8, true);

WriteLiteral(" y2=\"17\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3503, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3511, 31, true);

WriteLiteral("></line>\r\n            <polyline");

EndContext("~/Views/Home/_Sidebar.cshtml", 3511, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3542, 22, true);

WriteLiteral(" points=\"10 9 9 9 8 9\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3542, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3564, 88, true);

WriteLiteral("></polyline>\r\n          </svg>\r\n          <span>Báo cáo</span>\r\n        </a>\r\n   " +
"     <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 3564, 88, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3652, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3652, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3661, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3661, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3678, 17, true);

WriteLiteral(" data-tab=\"alert\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3678, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3695, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 3695, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3712, 25, true);

WriteLiteral(" class=\"nav-icon-wrapper\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3712, 25, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3737, 19, true);

WriteLiteral(">\r\n            <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 3737, 19, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3756, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3756, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3773, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3773, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3793, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3793, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3805, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3805, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3827, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3827, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3844, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3844, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3867, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3867, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3891, 22, true);

WriteLiteral(">\r\n              <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 3891, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3913, 48, true);

WriteLiteral(" d=\"M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3913, 48, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3961, 29, true);

WriteLiteral("></path>\r\n              <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 3961, 29, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 3990, 31, true);

WriteLiteral(" d=\"M13.73 21a2 2 0 0 1-3.46 0\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 3990, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4021, 47, true);

WriteLiteral("></path>\r\n            </svg>\r\n            <span");

EndContext("~/Views/Home/_Sidebar.cshtml", 4021, 47, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4068, 18, true);

WriteLiteral(" class=\"nav-badge\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4068, 18, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4086, 86, true);

WriteLiteral(">3</span>\r\n          </div>\r\n          <span>Cảnh báo</span>\r\n        </a>\r\n     " +
"   <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 4086, 86, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4172, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4172, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4181, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4181, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4198, 17, true);

WriteLiteral(" data-tab=\"guide\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4198, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4215, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 4215, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4232, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4232, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4249, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4249, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4269, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4269, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4281, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4281, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4303, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4303, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4320, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4320, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4343, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4343, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4367, 20, true);

WriteLiteral(">\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 4367, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4387, 36, true);

WriteLiteral(" d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4387, 36, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4423, 27, true);

WriteLiteral("></path>\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 4423, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4450, 67, true);

WriteLiteral(" d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4450, 67, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4517, 86, true);

WriteLiteral("></path>\r\n          </svg>\r\n          <span>Hướng dẫn</span>\r\n        </a>\r\n     " +
"   <a");

EndContext("~/Views/Home/_Sidebar.cshtml", 4517, 86, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4603, 9, true);

WriteLiteral(" href=\"#\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4603, 9, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4612, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4612, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4629, 20, true);

WriteLiteral(" data-tab=\"settings\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4629, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4649, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 4649, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4666, 17, true);

WriteLiteral(" class=\"nav-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4666, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4683, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4683, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4703, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4703, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4715, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4715, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4737, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4737, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4754, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4754, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4777, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4777, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4801, 22, true);

WriteLiteral(">\r\n            <circle");

EndContext("~/Views/Home/_Sidebar.cshtml", 4801, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4823, 8, true);

WriteLiteral(" cx=\"12\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4823, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4831, 8, true);

WriteLiteral(" cy=\"12\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4831, 8, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4839, 6, true);

WriteLiteral(" r=\"3\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 4839, 6, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4845, 29, true);

WriteLiteral("></circle>\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 4845, 29, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 4874, 627, true);

WriteLiteral(@" d=""M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z""");

EndContext("~/Views/Home/_Sidebar.cshtml", 4874, 627, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5501, 135, true);

WriteLiteral("></path>\r\n          </svg>\r\n          <span>Cài đặt</span>\r\n        </a>\r\n      <" +
"/nav>\r\n\r\n      <!-- System Status Card -->\r\n      <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 5501, 135, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5636, 28, true);

WriteLiteral(" class=\"sidebar-status-card\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5636, 28, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5664, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 5664, 15, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5679, 27, true);

WriteLiteral(" class=\"status-card-header\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5679, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5706, 17, true);

WriteLiteral(">\r\n          <svg");

EndContext("~/Views/Home/_Sidebar.cshtml", 5706, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5723, 27, true);

WriteLiteral(" class=\"status-shield-icon\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5723, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5750, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5750, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5770, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5770, 12, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5782, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5782, 22, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5804, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5804, 17, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5821, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5821, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5844, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5844, 24, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5868, 20, true);

WriteLiteral(">\r\n            <path");

EndContext("~/Views/Home/_Sidebar.cshtml", 5868, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5888, 48, true);

WriteLiteral(" d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5888, 48, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5936, 31, true);

WriteLiteral("></path>\r\n            <polyline");

EndContext("~/Views/Home/_Sidebar.cshtml", 5936, 31, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5967, 25, true);

WriteLiteral(" points=\"9 11 11 13 15 9\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 5967, 25, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 5992, 46, true);

WriteLiteral("></polyline>\r\n          </svg>\r\n          <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 5992, 46, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6038, 27, true);

WriteLiteral(" class=\"status-card-titles\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6038, 27, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6065, 20, true);

WriteLiteral(">\r\n            <span");

EndContext("~/Views/Home/_Sidebar.cshtml", 6065, 20, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6085, 26, true);

WriteLiteral(" class=\"status-card-label\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6085, 26, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6111, 25, true);

WriteLiteral(" data-i18n=\"sys_card_lbl\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6111, 25, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6136, 35, true);

WriteLiteral(">HỆ THỐNG</span>\r\n            <span");

EndContext("~/Views/Home/_Sidebar.cshtml", 6136, 35, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6171, 26, true);

WriteLiteral(" class=\"status-card-value\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6171, 26, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6197, 25, true);

WriteLiteral(" data-i18n=\"sys_card_val\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6197, 25, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6222, 61, true);

WriteLiteral(">ỔN ĐỊNH</span>\r\n          </div>\r\n        </div>\r\n        <p");

EndContext("~/Views/Home/_Sidebar.cshtml", 6222, 61, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6283, 28, true);

WriteLiteral(" class=\"status-card-subtext\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6283, 28, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6311, 25, true);

WriteLiteral(" data-i18n=\"sys_card_sub\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6311, 25, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6336, 101, true);

WriteLiteral(">Tất cả thiết bị hoạt động bình thường</p>\r\n      </div>\r\n\r\n      <!-- Sidebar Fo" +
"oter -->\r\n      <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 6336, 101, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6437, 23, true);

WriteLiteral(" class=\"sidebar-footer\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6437, 23, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6460, 54, true);

WriteLiteral(">\r\n        <span>© 2026 HP System</span>\r\n        <div");

EndContext("~/Views/Home/_Sidebar.cshtml", 6460, 54, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6514, 16, true);

WriteLiteral(" class=\"version\"");

EndContext("~/Views/Home/_Sidebar.cshtml", 6514, 16, true);

BeginContext("~/Views/Home/_Sidebar.cshtml", 6530, 43, true);

WriteLiteral(">v1.0.0</div>\r\n      </div>\r\n    </aside>\r\n");

EndContext("~/Views/Home/_Sidebar.cshtml", 6530, 43, true);

        }
    }
}
