#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_MachineList.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6DBDDA9E0E8A13C6521B65AD9B6F9F656CCA5B30"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__MachineList_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__MachineList_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_MachineList.cshtml", 0, 16, true);

WriteLiteral("        <section");

EndContext("~/Views/Home/_MachineList.cshtml", 0, 16, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 16, 18, true);

WriteLiteral(" id=\"view-machine\"");

EndContext("~/Views/Home/_MachineList.cshtml", 16, 18, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 34, 28, true);

WriteLiteral(" class=\"view-section hidden\"");

EndContext("~/Views/Home/_MachineList.cshtml", 34, 28, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 62, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_MachineList.cshtml", 62, 17, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 79, 28, true);

WriteLiteral(" class=\"machine-list-layout\"");

EndContext("~/Views/Home/_MachineList.cshtml", 79, 28, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 107, 89, true);

WriteLiteral(">\r\n            <!-- Control Bar (Search, Filters, Toggle Grid/List) -->\r\n        " +
"    <div");

EndContext("~/Views/Home/_MachineList.cshtml", 107, 89, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 196, 20, true);

WriteLiteral(" class=\"control-bar\"");

EndContext("~/Views/Home/_MachineList.cshtml", 196, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 216, 56, true);

WriteLiteral(">\r\n              <!-- Search Bar -->\r\n              <div");

EndContext("~/Views/Home/_MachineList.cshtml", 216, 56, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 272, 27, true);

WriteLiteral(" class=\"search-box-wrapper\"");

EndContext("~/Views/Home/_MachineList.cshtml", 272, 27, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 299, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_MachineList.cshtml", 299, 23, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 322, 20, true);

WriteLiteral(" class=\"search-icon\"");

EndContext("~/Views/Home/_MachineList.cshtml", 322, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 342, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_MachineList.cshtml", 342, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 362, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_MachineList.cshtml", 362, 12, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 374, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_MachineList.cshtml", 374, 22, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 396, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_MachineList.cshtml", 396, 17, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 413, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 413, 23, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 436, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 436, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 460, 28, true);

WriteLiteral(">\r\n                  <circle");

EndContext("~/Views/Home/_MachineList.cshtml", 460, 28, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 488, 8, true);

WriteLiteral(" cx=\"11\"");

EndContext("~/Views/Home/_MachineList.cshtml", 488, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 496, 8, true);

WriteLiteral(" cy=\"11\"");

EndContext("~/Views/Home/_MachineList.cshtml", 496, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 504, 6, true);

WriteLiteral(" r=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 504, 6, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 510, 35, true);

WriteLiteral("></circle>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 510, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 545, 8, true);

WriteLiteral(" x1=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 545, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 553, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 553, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 561, 11, true);

WriteLiteral(" x2=\"16.65\"");

EndContext("~/Views/Home/_MachineList.cshtml", 561, 11, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 572, 11, true);

WriteLiteral(" y2=\"16.65\"");

EndContext("~/Views/Home/_MachineList.cshtml", 572, 11, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 583, 56, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <input");

EndContext("~/Views/Home/_MachineList.cshtml", 583, 56, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 639, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/Home/_MachineList.cshtml", 639, 12, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 651, 26, true);

WriteLiteral(" id=\"machine-search-input\"");

EndContext("~/Views/Home/_MachineList.cshtml", 651, 26, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 677, 44, true);

WriteLiteral(" data-i18n=\"machine_list_search_placeholder\"");

EndContext("~/Views/Home/_MachineList.cshtml", 677, 44, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 721, 44, true);

WriteLiteral(" placeholder=\"Search Machine ID or Model...\"");

EndContext("~/Views/Home/_MachineList.cshtml", 721, 44, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 765, 101, true);

WriteLiteral(">\r\n              </div>\r\n              \r\n              <!-- Filters Button -->\r\n " +
"             <button");

EndContext("~/Views/Home/_MachineList.cshtml", 765, 101, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 866, 19, true);

WriteLiteral(" class=\"filter-btn\"");

EndContext("~/Views/Home/_MachineList.cshtml", 866, 19, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 885, 24, true);

WriteLiteral(" id=\"machine-filter-btn\"");

EndContext("~/Views/Home/_MachineList.cshtml", 885, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 909, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_MachineList.cshtml", 909, 23, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 932, 20, true);

WriteLiteral(" class=\"filter-icon\"");

EndContext("~/Views/Home/_MachineList.cshtml", 932, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 952, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_MachineList.cshtml", 952, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 972, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_MachineList.cshtml", 972, 12, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 984, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_MachineList.cshtml", 984, 22, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1006, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1006, 17, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1023, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1023, 23, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1046, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1046, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1070, 26, true);

WriteLiteral(">\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1070, 26, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1096, 7, true);

WriteLiteral(" x1=\"4\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1096, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1103, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1103, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1111, 7, true);

WriteLiteral(" x2=\"4\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1111, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1118, 8, true);

WriteLiteral(" y2=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1118, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1126, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1126, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1159, 7, true);

WriteLiteral(" x1=\"4\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1159, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1166, 8, true);

WriteLiteral(" y1=\"10\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1166, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1174, 7, true);

WriteLiteral(" x2=\"4\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1174, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1181, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1181, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1188, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1188, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1221, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1221, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1229, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1229, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1237, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1237, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1245, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1245, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1253, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1253, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1286, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1286, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1294, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1294, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1301, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1301, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1309, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1309, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1316, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1316, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1349, 8, true);

WriteLiteral(" x1=\"20\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1349, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1357, 8, true);

WriteLiteral(" y1=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1357, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1365, 8, true);

WriteLiteral(" x2=\"20\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1365, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1373, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1373, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1381, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1381, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1414, 8, true);

WriteLiteral(" x1=\"20\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1414, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1422, 8, true);

WriteLiteral(" y1=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1422, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1430, 8, true);

WriteLiteral(" x2=\"20\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1430, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1438, 7, true);

WriteLiteral(" y2=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1438, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1445, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1445, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1478, 7, true);

WriteLiteral(" x1=\"1\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1478, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1485, 8, true);

WriteLiteral(" y1=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1485, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1493, 7, true);

WriteLiteral(" x2=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1493, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1500, 8, true);

WriteLiteral(" y2=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1500, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1508, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1508, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1541, 7, true);

WriteLiteral(" x1=\"9\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1541, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1548, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1548, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1555, 8, true);

WriteLiteral(" x2=\"15\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1555, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1563, 7, true);

WriteLiteral(" y2=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1563, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1570, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_MachineList.cshtml", 1570, 33, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1603, 8, true);

WriteLiteral(" x1=\"17\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1603, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1611, 8, true);

WriteLiteral(" y1=\"16\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1611, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1619, 8, true);

WriteLiteral(" x2=\"23\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1619, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1627, 8, true);

WriteLiteral(" y2=\"16\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1627, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1635, 55, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <span");

EndContext("~/Views/Home/_MachineList.cshtml", 1635, 55, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1690, 31, true);

WriteLiteral(" data-i18n=\"history_btn_filter\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1690, 31, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1721, 114, true);

WriteLiteral(">Filters</span>\r\n              </button>\r\n\r\n              <!-- View Switcher (Gri" +
"d / List) -->\r\n              <div");

EndContext("~/Views/Home/_MachineList.cshtml", 1721, 114, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1835, 22, true);

WriteLiteral(" class=\"view-switcher\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1835, 22, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1857, 26, true);

WriteLiteral(">\r\n                <button");

EndContext("~/Views/Home/_MachineList.cshtml", 1857, 26, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1883, 26, true);

WriteLiteral(" class=\"switch-btn active\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1883, 26, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1909, 19, true);

WriteLiteral(" id=\"view-grid-btn\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1909, 19, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1928, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_MachineList.cshtml", 1928, 25, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1953, 20, true);

WriteLiteral(" class=\"switch-icon\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1953, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1973, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1973, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 1993, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_MachineList.cshtml", 1993, 12, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2005, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2005, 22, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2027, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2027, 17, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2044, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2044, 23, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2067, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2067, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2091, 28, true);

WriteLiteral(">\r\n                    <rect");

EndContext("~/Views/Home/_MachineList.cshtml", 2091, 28, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2119, 6, true);

WriteLiteral(" x=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2119, 6, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2125, 6, true);

WriteLiteral(" y=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2125, 6, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2131, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2131, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2141, 11, true);

WriteLiteral(" height=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2141, 11, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2152, 35, true);

WriteLiteral("></rect>\r\n                    <rect");

EndContext("~/Views/Home/_MachineList.cshtml", 2152, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2187, 7, true);

WriteLiteral(" x=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2187, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2194, 6, true);

WriteLiteral(" y=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2194, 6, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2200, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2200, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2210, 11, true);

WriteLiteral(" height=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2210, 11, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2221, 35, true);

WriteLiteral("></rect>\r\n                    <rect");

EndContext("~/Views/Home/_MachineList.cshtml", 2221, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2256, 7, true);

WriteLiteral(" x=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2256, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2263, 7, true);

WriteLiteral(" y=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2263, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2270, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2270, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2280, 11, true);

WriteLiteral(" height=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2280, 11, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2291, 35, true);

WriteLiteral("></rect>\r\n                    <rect");

EndContext("~/Views/Home/_MachineList.cshtml", 2291, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2326, 6, true);

WriteLiteral(" x=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2326, 6, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2332, 7, true);

WriteLiteral(" y=\"14\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2332, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2339, 10, true);

WriteLiteral(" width=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2339, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2349, 11, true);

WriteLiteral(" height=\"7\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2349, 11, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2360, 59, true);

WriteLiteral("></rect>\r\n                  </svg>\r\n                  <span");

EndContext("~/Views/Home/_MachineList.cshtml", 2360, 59, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2419, 24, true);

WriteLiteral(" data-i18n=\"layout_grid\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2419, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2443, 64, true);

WriteLiteral(">Grid</span>\r\n                </button>\r\n                <button");

EndContext("~/Views/Home/_MachineList.cshtml", 2443, 64, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2507, 19, true);

WriteLiteral(" class=\"switch-btn\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2507, 19, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2526, 19, true);

WriteLiteral(" id=\"view-list-btn\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2526, 19, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2545, 25, true);

WriteLiteral(">\r\n                  <svg");

EndContext("~/Views/Home/_MachineList.cshtml", 2545, 25, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2570, 20, true);

WriteLiteral(" class=\"switch-icon\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2570, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2590, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2590, 20, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2610, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2610, 12, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2622, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2622, 22, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2644, 17, true);

WriteLiteral(" stroke-width=\"2\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2644, 17, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2661, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2661, 23, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2684, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2684, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2708, 28, true);

WriteLiteral(">\r\n                    <line");

EndContext("~/Views/Home/_MachineList.cshtml", 2708, 28, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2736, 7, true);

WriteLiteral(" x1=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2736, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2743, 7, true);

WriteLiteral(" y1=\"6\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2743, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2750, 8, true);

WriteLiteral(" x2=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2750, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2758, 7, true);

WriteLiteral(" y2=\"6\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2758, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2765, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_MachineList.cshtml", 2765, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2800, 7, true);

WriteLiteral(" x1=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2800, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2807, 8, true);

WriteLiteral(" y1=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2807, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2815, 8, true);

WriteLiteral(" x2=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2815, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2823, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2823, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2831, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_MachineList.cshtml", 2831, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2866, 7, true);

WriteLiteral(" x1=\"8\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2866, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2873, 8, true);

WriteLiteral(" y1=\"18\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2873, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2881, 8, true);

WriteLiteral(" x2=\"21\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2881, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2889, 8, true);

WriteLiteral(" y2=\"18\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2889, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2897, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_MachineList.cshtml", 2897, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2932, 7, true);

WriteLiteral(" x1=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2932, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2939, 7, true);

WriteLiteral(" y1=\"6\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2939, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2946, 10, true);

WriteLiteral(" x2=\"3.01\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2946, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2956, 7, true);

WriteLiteral(" y2=\"6\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2956, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2963, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_MachineList.cshtml", 2963, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 2998, 7, true);

WriteLiteral(" x1=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 2998, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3005, 8, true);

WriteLiteral(" y1=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3005, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3013, 10, true);

WriteLiteral(" x2=\"3.01\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3013, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3023, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3023, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3031, 35, true);

WriteLiteral("></line>\r\n                    <line");

EndContext("~/Views/Home/_MachineList.cshtml", 3031, 35, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3066, 7, true);

WriteLiteral(" x1=\"3\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3066, 7, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3073, 8, true);

WriteLiteral(" y1=\"18\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3073, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3081, 10, true);

WriteLiteral(" x2=\"3.01\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3081, 10, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3091, 8, true);

WriteLiteral(" y2=\"18\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3091, 8, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3099, 59, true);

WriteLiteral("></line>\r\n                  </svg>\r\n                  <span");

EndContext("~/Views/Home/_MachineList.cshtml", 3099, 59, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3158, 24, true);

WriteLiteral(" data-i18n=\"layout_list\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3158, 24, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3182, 147, true);

WriteLiteral(">List</span>\r\n                </button>\r\n              </div>\r\n            </div>" +
"\r\n\r\n            <!-- Machine List Cards Grid -->\r\n            <div");

EndContext("~/Views/Home/_MachineList.cshtml", 3182, 147, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3329, 26, true);

WriteLiteral(" class=\"machine-list-grid\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3329, 26, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3355, 28, true);

WriteLiteral(" id=\"machine-list-container\"");

EndContext("~/Views/Home/_MachineList.cshtml", 3355, 28, true);

BeginContext("~/Views/Home/_MachineList.cshtml", 3383, 115, true);

WriteLiteral(">\r\n              <!-- Dynamically rendered via JS -->\r\n            </div>\r\n      " +
"    </div>\r\n        </section>\r\n\r\n");

EndContext("~/Views/Home/_MachineList.cshtml", 3383, 115, true);

        }
    }
}
