#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E1D6B13499987A3895E18AB5A5EC01F24F3BAC97"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
BeginContext("~/Views/Home/Index.cshtml", 25, 24, true);

WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

EndContext("~/Views/Home/Index.cshtml", 25, 24, true);

BeginContext("~/Views/Home/Index.cshtml", 49, 10, true);

WriteLiteral(" lang=\"vi\"");

EndContext("~/Views/Home/Index.cshtml", 49, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 59, 18, true);

WriteLiteral(">\r\n<head>\r\n  <meta");

EndContext("~/Views/Home/Index.cshtml", 59, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 77, 16, true);

WriteLiteral(" charset=\"UTF-8\"");

EndContext("~/Views/Home/Index.cshtml", 77, 16, true);

BeginContext("~/Views/Home/Index.cshtml", 93, 10, true);

WriteLiteral(">\r\n  <meta");

EndContext("~/Views/Home/Index.cshtml", 93, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 103, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Home/Index.cshtml", 103, 16, true);

BeginContext("~/Views/Home/Index.cshtml", 119, 48, true);

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

EndContext("~/Views/Home/Index.cshtml", 119, 48, true);

BeginContext("~/Views/Home/Index.cshtml", 167, 56, true);

WriteLiteral(">\r\n  <title>Quản lý máy dập - HP System</title>\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 167, 56, true);

BeginContext("~/Views/Home/Index.cshtml", 223, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 223, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 240), Tuple.Create("\"", 282)
            
            #line 10 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 247), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/base.css?v=24")
            
            #line default
            #line hidden
, 247), false)
);

BeginContext("~/Views/Home/Index.cshtml", 283, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 283, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 293, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 293, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 310), Tuple.Create("\"", 354)
            
            #line 11 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 317), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/layout.css?v=24")
            
            #line default
            #line hidden
, 317), false)
);

BeginContext("~/Views/Home/Index.cshtml", 355, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 355, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 365, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 365, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 382), Tuple.Create("\"", 428)
            
            #line 12 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 389), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/overview.css?v=24")
            
            #line default
            #line hidden
, 389), false)
);

BeginContext("~/Views/Home/Index.cshtml", 429, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 429, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 439, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 439, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 456), Tuple.Create("\"", 501)
            
            #line 13 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 463), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/machine.css?v=24")
            
            #line default
            #line hidden
, 463), false)
);

BeginContext("~/Views/Home/Index.cshtml", 502, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 502, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 512, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 512, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 529), Tuple.Create("\"", 574)
            
            #line 14 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 536), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/history.css?v=24")
            
            #line default
            #line hidden
, 536), false)
);

BeginContext("~/Views/Home/Index.cshtml", 575, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 575, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 585, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 585, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 602), Tuple.Create("\"", 646)
            
            #line 15 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 609), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/report.css?v=24")
            
            #line default
            #line hidden
, 609), false)
);

BeginContext("~/Views/Home/Index.cshtml", 647, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 647, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 657, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 657, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 674), Tuple.Create("\"", 718)
            
            #line 16 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 681), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/alerts.css?v=24")
            
            #line default
            #line hidden
, 681), false)
);

BeginContext("~/Views/Home/Index.cshtml", 719, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 719, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 729, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 729, 17, true);

WriteAttribute("href", Tuple.Create(" href=\"", 746), Tuple.Create("\"", 792)
            
            #line 17 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 753), Tuple.Create<System.Object, System.Int32>(Url.Content("~/css/settings.css?v=24")
            
            #line default
            #line hidden
, 753), false)
);

BeginContext("~/Views/Home/Index.cshtml", 793, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 793, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 803, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 803, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 820, 69, true);

WriteLiteral(" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css\"");

EndContext("~/Views/Home/Index.cshtml", 820, 69, true);

BeginContext("~/Views/Home/Index.cshtml", 889, 10, true);

WriteLiteral(">\r\n  <link");

EndContext("~/Views/Home/Index.cshtml", 889, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 899, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Home/Index.cshtml", 899, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 916, 81, true);

WriteLiteral(" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/plugins/monthSelect/style.css\"" +
"");

EndContext("~/Views/Home/Index.cshtml", 916, 81, true);

BeginContext("~/Views/Home/Index.cshtml", 997, 12, true);

WriteLiteral(">\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 997, 12, true);

BeginContext("~/Views/Home/Index.cshtml", 1009, 44, true);

WriteLiteral(" src=\"https://cdn.jsdelivr.net/npm/chart.js\"");

EndContext("~/Views/Home/Index.cshtml", 1009, 44, true);

BeginContext("~/Views/Home/Index.cshtml", 1053, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1053, 27, true);

BeginContext("~/Views/Home/Index.cshtml", 1080, 45, true);

WriteLiteral(" src=\"https://cdn.jsdelivr.net/npm/flatpickr\"");

EndContext("~/Views/Home/Index.cshtml", 1080, 45, true);

BeginContext("~/Views/Home/Index.cshtml", 1125, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1125, 27, true);

BeginContext("~/Views/Home/Index.cshtml", 1152, 87, true);

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.m" +
"in.js\"");

EndContext("~/Views/Home/Index.cshtml", 1152, 87, true);

BeginContext("~/Views/Home/Index.cshtml", 1239, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1239, 27, true);

BeginContext("~/Views/Home/Index.cshtml", 1266, 79, true);

WriteLiteral(" src=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/plugins/monthSelect/index.js\"");

EndContext("~/Views/Home/Index.cshtml", 1266, 79, true);

BeginContext("~/Views/Home/Index.cshtml", 1345, 53, true);

WriteLiteral(" defer></script>\r\n  <script>\r\n    window.basePath = \'");

EndContext("~/Views/Home/Index.cshtml", 1345, 53, true);

BeginContext("~/Views/Home/Index.cshtml", 1399, 17, false);

            
            #line 25 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
                  Write(Url.Content("~/"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 1399, 17, false);

BeginContext("~/Views/Home/Index.cshtml", 1416, 26, true);

WriteLiteral("\';\r\n  </script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1416, 26, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1442), Tuple.Create("\"", 1481)
            
            #line 27 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1448), Tuple.Create<System.Object, System.Int32>(Url.Content("~/lang/vi.js?v=24")
            
            #line default
            #line hidden
, 1448), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1482, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1482, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1509), Tuple.Create("\"", 1548)
            
            #line 28 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1515), Tuple.Create<System.Object, System.Int32>(Url.Content("~/lang/en.js?v=24")
            
            #line default
            #line hidden
, 1515), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1549, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1549, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1576), Tuple.Create("\"", 1616)
            
            #line 29 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1582), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/state.js?v=24")
            
            #line default
            #line hidden
, 1582), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1617, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1617, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1644), Tuple.Create("\"", 1689)
            
            #line 30 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1650), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/navigation.js?v=24")
            
            #line default
            #line hidden
, 1650), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1690, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1690, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1717), Tuple.Create("\"", 1760)
            
            #line 31 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1723), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/overview.js?v=24")
            
            #line default
            #line hidden
, 1723), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1761, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1761, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1788), Tuple.Create("\"", 1830)
            
            #line 32 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1794), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/machine.js?v=24")
            
            #line default
            #line hidden
, 1794), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1831, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1831, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1858), Tuple.Create("\"", 1900)
            
            #line 33 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1864), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/history.js?v=24")
            
            #line default
            #line hidden
, 1864), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1901, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1901, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1928), Tuple.Create("\"", 1969)
            
            #line 34 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1934), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/report.js?v=24")
            
            #line default
            #line hidden
, 1934), false)
);

BeginContext("~/Views/Home/Index.cshtml", 1970, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 1970, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 1997), Tuple.Create("\"", 2038)
            
            #line 35 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2003), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/alerts.js?v=24")
            
            #line default
            #line hidden
, 2003), false)
);

BeginContext("~/Views/Home/Index.cshtml", 2039, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 2039, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2066), Tuple.Create("\"", 2117)
            
            #line 36 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2072), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/productionOrders.js?v=24")
            
            #line default
            #line hidden
, 2072), false)
);

BeginContext("~/Views/Home/Index.cshtml", 2118, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 2118, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2145), Tuple.Create("\"", 2188)
            
            #line 37 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2151), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/settings.js?v=24")
            
            #line default
            #line hidden
, 2151), false)
);

BeginContext("~/Views/Home/Index.cshtml", 2189, 27, true);

WriteLiteral(" defer></script>\r\n  <script");

EndContext("~/Views/Home/Index.cshtml", 2189, 27, true);

WriteAttribute("src", Tuple.Create(" src=\"", 2216), Tuple.Create("\"", 2254)
            
            #line 38 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2222), Tuple.Create<System.Object, System.Int32>(Url.Content("~/js/app.js?v=24")
            
            #line default
            #line hidden
, 2222), false)
);

BeginContext("~/Views/Home/Index.cshtml", 2255, 41, true);

WriteLiteral(" defer></script>\r\n</head>\r\n<body>\r\n  <div");

EndContext("~/Views/Home/Index.cshtml", 2255, 41, true);

BeginContext("~/Views/Home/Index.cshtml", 2296, 22, true);

WriteLiteral(" class=\"app-container\"");

EndContext("~/Views/Home/Index.cshtml", 2296, 22, true);

BeginContext("~/Views/Home/Index.cshtml", 2318, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Home/Index.cshtml", 2318, 3, true);

BeginContext("~/Views/Home/Index.cshtml", 2321, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Home/Index.cshtml", 2321, 4, true);

BeginContext("~/Views/Home/Index.cshtml", 2326, 24, false);

            
            #line 42 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
Write(Html.Partial("_Sidebar"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2326, 24, false);

BeginContext("~/Views/Home/Index.cshtml", 2350, 38, true);

WriteLiteral("\r\n\r\n    <!-- Main Layout -->\r\n    <div");

EndContext("~/Views/Home/Index.cshtml", 2350, 38, true);

BeginContext("~/Views/Home/Index.cshtml", 2388, 18, true);

WriteLiteral(" class=\"main-area\"");

EndContext("~/Views/Home/Index.cshtml", 2388, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 2406, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Home/Index.cshtml", 2406, 3, true);

BeginContext("~/Views/Home/Index.cshtml", 2409, 6, true);

WriteLiteral("      ");

EndContext("~/Views/Home/Index.cshtml", 2409, 6, true);

BeginContext("~/Views/Home/Index.cshtml", 2416, 23, false);

            
            #line 46 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
 Write(Html.Partial("_Header"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2416, 23, false);

BeginContext("~/Views/Home/Index.cshtml", 2439, 45, true);

WriteLiteral("\r\n\r\n      <!-- Content Views -->\r\n      <main");

EndContext("~/Views/Home/Index.cshtml", 2439, 45, true);

BeginContext("~/Views/Home/Index.cshtml", 2484, 26, true);

WriteLiteral(" class=\"content-container\"");

EndContext("~/Views/Home/Index.cshtml", 2484, 26, true);

BeginContext("~/Views/Home/Index.cshtml", 2510, 23, true);

WriteLiteral(" id=\"content-container\"");

EndContext("~/Views/Home/Index.cshtml", 2510, 23, true);

BeginContext("~/Views/Home/Index.cshtml", 2533, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Home/Index.cshtml", 2533, 3, true);

BeginContext("~/Views/Home/Index.cshtml", 2536, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2536, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2545, 25, false);

            
            #line 50 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_Overview"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2545, 25, false);

BeginContext("~/Views/Home/Index.cshtml", 2570, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2570, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2572, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2572, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2581, 28, false);

            
            #line 51 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_MachineList"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2581, 28, false);

BeginContext("~/Views/Home/Index.cshtml", 2609, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2609, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2611, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2611, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2620, 30, false);

            
            #line 52 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_MachineDetail"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2620, 30, false);

BeginContext("~/Views/Home/Index.cshtml", 2650, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2650, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2652, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2652, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2661, 33, false);

            
            #line 53 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_ProductionOrders"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2661, 33, false);

BeginContext("~/Views/Home/Index.cshtml", 2694, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2694, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2696, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2696, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2705, 24, false);

            
            #line 54 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_History"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2705, 24, false);

BeginContext("~/Views/Home/Index.cshtml", 2729, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2729, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2731, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2731, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2740, 23, false);

            
            #line 55 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_Report"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2740, 23, false);

BeginContext("~/Views/Home/Index.cshtml", 2763, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2763, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2765, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2765, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2774, 23, false);

            
            #line 56 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_Alerts"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2774, 23, false);

BeginContext("~/Views/Home/Index.cshtml", 2797, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2797, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2799, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2799, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2808, 22, false);

            
            #line 57 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_Guide"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2808, 22, false);

BeginContext("~/Views/Home/Index.cshtml", 2830, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Home/Index.cshtml", 2830, 2, true);

BeginContext("~/Views/Home/Index.cshtml", 2832, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Home/Index.cshtml", 2832, 8, true);

BeginContext("~/Views/Home/Index.cshtml", 2841, 25, false);

            
            #line 58 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\Index.cshtml"
   Write(Html.Partial("_Settings"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/Index.cshtml", 2841, 25, false);

BeginContext("~/Views/Home/Index.cshtml", 2866, 57, true);

WriteLiteral("\r\n      </main>\r\n    </div>\r\n  </div>\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Home/Index.cshtml", 2866, 57, true);

        }
    }
}
