#pragma checksum "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_Overview.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "959C291FA26CE7EF73DF334FE31A0C0B2373B073"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using TestIndema;
    
    
    public class _Page_Views_Home__Overview_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home__Overview_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Home/_Overview.cshtml", 0, 8, true);

WriteLiteral("<section");

EndContext("~/Views/Home/_Overview.cshtml", 0, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8, 19, true);

WriteLiteral(" id=\"view-overview\"");

EndContext("~/Views/Home/_Overview.cshtml", 8, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 27, 21, true);

WriteLiteral(" class=\"view-section\"");

EndContext("~/Views/Home/_Overview.cshtml", 27, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 48, 9, true);

WriteLiteral(">\r\n  <div");

EndContext("~/Views/Home/_Overview.cshtml", 48, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 57, 24, true);

WriteLiteral(" class=\"overview-layout\"");

EndContext("~/Views/Home/_Overview.cshtml", 57, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 81, 62, true);

WriteLiteral(">\r\n    <!-- Row 1: KPI Panels & Selected Machine -->\r\n    <div");

EndContext("~/Views/Home/_Overview.cshtml", 81, 62, true);

BeginContext("~/Views/Home/_Overview.cshtml", 143, 32, true);

WriteLiteral(" class=\"overview-row-top-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 143, 32, true);

BeginContext("~/Views/Home/_Overview.cshtml", 175, 61, true);

WriteLiteral(">\r\n      <!-- Panel 1: Selected Machine Image -->\r\n      <div");

EndContext("~/Views/Home/_Overview.cshtml", 175, 61, true);

BeginContext("~/Views/Home/_Overview.cshtml", 236, 23, true);

WriteLiteral(" class=\"kpi-panel-left\"");

EndContext("~/Views/Home/_Overview.cshtml", 236, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 259, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Home/_Overview.cshtml", 259, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 274, 36, true);

WriteLiteral(" class=\"active-machine-panel-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 274, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 310, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_Overview.cshtml", 310, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 327, 28, true);

WriteLiteral(" class=\"panel-header-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 327, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 355, 18, true);

WriteLiteral(">\r\n            <h3");

EndContext("~/Views/Home/_Overview.cshtml", 355, 18, true);

BeginContext("~/Views/Home/_Overview.cshtml", 373, 27, true);

WriteLiteral(" class=\"panel-title-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 373, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 400, 34, true);

WriteLiteral(" data-i18n=\"active_machine_header\"");

EndContext("~/Views/Home/_Overview.cshtml", 400, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 434, 47, true);

WriteLiteral(">MÁY DẬP</h3>\r\n          </div>\r\n          <div");

EndContext("~/Views/Home/_Overview.cshtml", 434, 47, true);

BeginContext("~/Views/Home/_Overview.cshtml", 481, 37, true);

WriteLiteral(" class=\"machine-image-wrapper-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 481, 37, true);

BeginContext("~/Views/Home/_Overview.cshtml", 518, 19, true);

WriteLiteral(">\r\n            <img");

EndContext("~/Views/Home/_Overview.cshtml", 518, 19, true);

WriteAttribute("src", Tuple.Create(" src=\"", 537), Tuple.Create("\"", 578)
            
            #line 12 "c:\Users\case 046\source\repos\HaiPhuong\HaiPhuong\Views\Home\_Overview.cshtml"
, Tuple.Create(Tuple.Create("", 543), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Image/maydap.jpeg")
            
            #line default
            #line hidden
, 543), false)
);

BeginContext("~/Views/Home/_Overview.cshtml", 579, 24, true);

WriteLiteral(" alt=\"Máy dập hoạt động\"");

EndContext("~/Views/Home/_Overview.cshtml", 579, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 603, 34, true);

WriteLiteral(" class=\"machine-hero-image-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 603, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 637, 28, true);

WriteLiteral(" id=\"selected-machine-image\"");

EndContext("~/Views/Home/_Overview.cshtml", 637, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 665, 39, true);

WriteLiteral(" style=\"width: 60%; object-fit: cover;\"");

EndContext("~/Views/Home/_Overview.cshtml", 665, 39, true);

BeginContext("~/Views/Home/_Overview.cshtml", 704, 107, true);

WriteLiteral(">\r\n          </div>\r\n        </div>\r\n      </div>\r\n\r\n      <!-- Panel 2: System P" +
"erformance -->\r\n      <div");

EndContext("~/Views/Home/_Overview.cshtml", 704, 107, true);

BeginContext("~/Views/Home/_Overview.cshtml", 811, 25, true);

WriteLiteral(" class=\"kpi-panel-middle\"");

EndContext("~/Views/Home/_Overview.cshtml", 811, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 836, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Home/_Overview.cshtml", 836, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 851, 24, true);

WriteLiteral(" class=\"kpi-card-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 851, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 875, 16, true);

WriteLiteral(">\r\n          <h3");

EndContext("~/Views/Home/_Overview.cshtml", 875, 16, true);

BeginContext("~/Views/Home/_Overview.cshtml", 891, 30, true);

WriteLiteral(" class=\"kpi-card-title-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 891, 30, true);

BeginContext("~/Views/Home/_Overview.cshtml", 921, 33, true);

WriteLiteral(" data-i18n=\"kpi_efficiency_title\"");

EndContext("~/Views/Home/_Overview.cshtml", 921, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 954, 45, true);

WriteLiteral(">HIỆU SUẤT TOÀN HỆ THỐNG</h3>\r\n          <div");

EndContext("~/Views/Home/_Overview.cshtml", 954, 45, true);

BeginContext("~/Views/Home/_Overview.cshtml", 999, 31, true);

WriteLiteral(" class=\"gauge-container-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 999, 31, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1030, 19, true);

WriteLiteral(">\r\n            <svg");

EndContext("~/Views/Home/_Overview.cshtml", 1030, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1049, 25, true);

WriteLiteral(" class=\"gauge-svg-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 1049, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1074, 22, true);

WriteLiteral(" viewBox=\"0 0 200 150\"");

EndContext("~/Views/Home/_Overview.cshtml", 1074, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1096, 56, true);

WriteLiteral(">\r\n              <defs>\r\n                <linearGradient");

EndContext("~/Views/Home/_Overview.cshtml", 1096, 56, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1152, 23, true);

WriteLiteral(" id=\"gauge-grad-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 1152, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1175, 8, true);

WriteLiteral(" x1=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1175, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1183, 10, true);

WriteLiteral(" y1=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1183, 10, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1193, 10, true);

WriteLiteral(" x2=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1193, 10, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1203, 8, true);

WriteLiteral(" y2=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1203, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1211, 26, true);

WriteLiteral(">\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 1211, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1237, 12, true);

WriteLiteral(" offset=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1237, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1249, 21, true);

WriteLiteral(" stop-color=\"#0055ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 1249, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1270, 28, true);

WriteLiteral(" />\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 1270, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1298, 13, true);

WriteLiteral(" offset=\"60%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1298, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1311, 21, true);

WriteLiteral(" stop-color=\"#00a8e8\"");

EndContext("~/Views/Home/_Overview.cshtml", 1311, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1332, 28, true);

WriteLiteral(" />\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 1332, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1360, 14, true);

WriteLiteral(" offset=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1360, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1374, 21, true);

WriteLiteral(" stop-color=\"#00d2ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 1374, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1395, 63, true);

WriteLiteral(" />\r\n                </linearGradient>\r\n                <filter");

EndContext("~/Views/Home/_Overview.cshtml", 1395, 63, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1458, 23, true);

WriteLiteral(" id=\"gauge-glow-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 1458, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1481, 9, true);

WriteLiteral(" x=\"-20%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1481, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1490, 9, true);

WriteLiteral(" y=\"-20%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1490, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1499, 13, true);

WriteLiteral(" width=\"140%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1499, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1512, 14, true);

WriteLiteral(" height=\"140%\"");

EndContext("~/Views/Home/_Overview.cshtml", 1512, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1526, 36, true);

WriteLiteral(">\r\n                  <feGaussianBlur");

EndContext("~/Views/Home/_Overview.cshtml", 1526, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1562, 17, true);

WriteLiteral(" stdDeviation=\"5\"");

EndContext("~/Views/Home/_Overview.cshtml", 1562, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1579, 14, true);

WriteLiteral(" result=\"blur\"");

EndContext("~/Views/Home/_Overview.cshtml", 1579, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1593, 35, true);

WriteLiteral(" />\r\n                  <feComposite");

EndContext("~/Views/Home/_Overview.cshtml", 1593, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1628, 19, true);

WriteLiteral(" in=\"SourceGraphic\"");

EndContext("~/Views/Home/_Overview.cshtml", 1628, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1647, 11, true);

WriteLiteral(" in2=\"blur\"");

EndContext("~/Views/Home/_Overview.cshtml", 1647, 11, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1658, 16, true);

WriteLiteral(" operator=\"over\"");

EndContext("~/Views/Home/_Overview.cshtml", 1658, 16, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1674, 74, true);

WriteLiteral(" />\r\n                </filter>\r\n              </defs>\r\n              <path");

EndContext("~/Views/Home/_Overview.cshtml", 1674, 74, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1748, 27, true);

WriteLiteral(" class=\"gauge-track-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 1748, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1775, 35, true);

WriteLiteral(" d=\"M 30,120 A 70,70 0 0,1 170,120\"");

EndContext("~/Views/Home/_Overview.cshtml", 1775, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1810, 17, true);

WriteLiteral(" stroke=\"#16223f\"");

EndContext("~/Views/Home/_Overview.cshtml", 1810, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1827, 17, true);

WriteLiteral(" stroke-width=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 1827, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1844, 22, true);

WriteLiteral(" stroke-linecap=\"butt\"");

EndContext("~/Views/Home/_Overview.cshtml", 1844, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1866, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Overview.cshtml", 1866, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1878, 24, true);

WriteLiteral(" />\r\n              <path");

EndContext("~/Views/Home/_Overview.cshtml", 1878, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1902, 26, true);

WriteLiteral(" class=\"gauge-fill-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 1902, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1928, 35, true);

WriteLiteral(" d=\"M 30,120 A 70,70 0 0,1 170,120\"");

EndContext("~/Views/Home/_Overview.cshtml", 1928, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1963, 33, true);

WriteLiteral(" stroke=\"url(#gauge-grad-custom)\"");

EndContext("~/Views/Home/_Overview.cshtml", 1963, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 1996, 17, true);

WriteLiteral(" stroke-width=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 1996, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2013, 22, true);

WriteLiteral(" stroke-linecap=\"butt\"");

EndContext("~/Views/Home/_Overview.cshtml", 2013, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2035, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Overview.cshtml", 2035, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2047, 44, true);

WriteLiteral("\r\n                    stroke-dasharray=\"220\"");

EndContext("~/Views/Home/_Overview.cshtml", 2047, 44, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2091, 23, true);

WriteLiteral(" stroke-dashoffset=\"33\"");

EndContext("~/Views/Home/_Overview.cshtml", 2091, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2114, 33, true);

WriteLiteral(" filter=\"url(#gauge-glow-custom)\"");

EndContext("~/Views/Home/_Overview.cshtml", 2114, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2147, 41, true);

WriteLiteral(" />\r\n            </svg>\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 2147, 41, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2188, 33, true);

WriteLiteral(" class=\"gauge-center-text-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 2188, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2221, 22, true);

WriteLiteral(">\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 2221, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2243, 27, true);

WriteLiteral(" class=\"gauge-value-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 2243, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2270, 8, true);

WriteLiteral(">85<span");

EndContext("~/Views/Home/_Overview.cshtml", 2270, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2278, 21, true);

WriteLiteral(" class=\"percent-sign\"");

EndContext("~/Views/Home/_Overview.cshtml", 2278, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2299, 37, true);

WriteLiteral(">%</span></span>\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 2299, 37, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2336, 27, true);

WriteLiteral(" class=\"gauge-label-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 2336, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2363, 40, true);

WriteLiteral(" data-i18n=\"overview_average_efficiency\"");

EndContext("~/Views/Home/_Overview.cshtml", 2363, 40, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2403, 94, true);

WriteLiteral(">Hiệu suất trung bình</span>\r\n            </div>\r\n          </div>\r\n          \r\n " +
"         <div");

EndContext("~/Views/Home/_Overview.cshtml", 2403, 94, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2497, 27, true);

WriteLiteral(" class=\"kpi-sub-stats-grid\"");

EndContext("~/Views/Home/_Overview.cshtml", 2497, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2524, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 2524, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2543, 26, true);

WriteLiteral(" class=\"kpi-sub-stat-item\"");

EndContext("~/Views/Home/_Overview.cshtml", 2543, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2569, 22, true);

WriteLiteral(">\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 2569, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2591, 21, true);

WriteLiteral(" class=\"sub-stat-lbl\"");

EndContext("~/Views/Home/_Overview.cshtml", 2591, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2612, 36, true);

WriteLiteral(" data-i18n=\"overview_kpi_trial_time\"");

EndContext("~/Views/Home/_Overview.cshtml", 2612, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2648, 52, true);

WriteLiteral(">THỜI GIAN CHẠY THỬ (TB)</span>\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 2648, 52, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2700, 21, true);

WriteLiteral(" class=\"sub-stat-val\"");

EndContext("~/Views/Home/_Overview.cshtml", 2700, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2721, 23, true);

WriteLiteral(" id=\"system-trial-time\"");

EndContext("~/Views/Home/_Overview.cshtml", 2721, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2744, 47, true);

WriteLiteral(">-</span>\r\n            </div>\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 2744, 47, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2791, 26, true);

WriteLiteral(" class=\"kpi-sub-stat-item\"");

EndContext("~/Views/Home/_Overview.cshtml", 2791, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2817, 22, true);

WriteLiteral(">\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 2817, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2839, 21, true);

WriteLiteral(" class=\"sub-stat-lbl\"");

EndContext("~/Views/Home/_Overview.cshtml", 2839, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2860, 41, true);

WriteLiteral(" data-i18n=\"overview_kpi_production_time\"");

EndContext("~/Views/Home/_Overview.cshtml", 2860, 41, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2901, 52, true);

WriteLiteral(">THỜI GIAN SẢN XUẤT (TB)</span>\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 2901, 52, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2953, 21, true);

WriteLiteral(" class=\"sub-stat-val\"");

EndContext("~/Views/Home/_Overview.cshtml", 2953, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 2974, 28, true);

WriteLiteral(" id=\"system-production-time\"");

EndContext("~/Views/Home/_Overview.cshtml", 2974, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3002, 47, true);

WriteLiteral(">-</span>\r\n            </div>\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 3002, 47, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3049, 26, true);

WriteLiteral(" class=\"kpi-sub-stat-item\"");

EndContext("~/Views/Home/_Overview.cshtml", 3049, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3075, 22, true);

WriteLiteral(">\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 3075, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3097, 21, true);

WriteLiteral(" class=\"sub-stat-lbl\"");

EndContext("~/Views/Home/_Overview.cshtml", 3097, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3118, 38, true);

WriteLiteral(" data-i18n=\"overview_kpi_running_time\"");

EndContext("~/Views/Home/_Overview.cshtml", 3118, 38, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3156, 52, true);

WriteLiteral(">THỜI GIAN MÁY CHẠY (TB)</span>\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 3156, 52, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3208, 21, true);

WriteLiteral(" class=\"sub-stat-val\"");

EndContext("~/Views/Home/_Overview.cshtml", 3208, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3229, 25, true);

WriteLiteral(" id=\"system-running-time\"");

EndContext("~/Views/Home/_Overview.cshtml", 3229, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3254, 75, true);

WriteLiteral(">-</span>\r\n            </div>\r\n          </div>\r\n          \r\n          <div");

EndContext("~/Views/Home/_Overview.cshtml", 3254, 75, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3329, 23, true);

WriteLiteral(" class=\"kpi-status-row\"");

EndContext("~/Views/Home/_Overview.cshtml", 3329, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3352, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 3352, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3371, 31, true);

WriteLiteral(" class=\"status-box box-running\"");

EndContext("~/Views/Home/_Overview.cshtml", 3371, 31, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3402, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_Overview.cshtml", 3402, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3423, 26, true);

WriteLiteral(" class=\"status-box-header\"");

EndContext("~/Views/Home/_Overview.cshtml", 3423, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3449, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_Overview.cshtml", 3449, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3472, 20, true);

WriteLiteral(" class=\"status-icon\"");

EndContext("~/Views/Home/_Overview.cshtml", 3472, 20, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3492, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Overview.cshtml", 3492, 20, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3512, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Overview.cshtml", 3512, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3524, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Overview.cshtml", 3524, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3546, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 3546, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3565, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 3565, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3588, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 3588, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3612, 30, true);

WriteLiteral(">\r\n                  <polyline");

EndContext("~/Views/Home/_Overview.cshtml", 3612, 30, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3642, 41, true);

WriteLiteral(" points=\"22 12 18 12 15 21 9 3 6 12 2 12\"");

EndContext("~/Views/Home/_Overview.cshtml", 3642, 41, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3683, 59, true);

WriteLiteral("></polyline>\r\n                </svg>\r\n                <span");

EndContext("~/Views/Home/_Overview.cshtml", 3683, 59, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3742, 23, true);

WriteLiteral(" class=\"status-box-lbl\"");

EndContext("~/Views/Home/_Overview.cshtml", 3742, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3765, 30, true);

WriteLiteral(" data-i18n=\"kpi_running_title\"");

EndContext("~/Views/Home/_Overview.cshtml", 3765, 30, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3795, 69, true);

WriteLiteral(">MÁY ĐANG HOẠT ĐỘNG</span>\r\n              </div>\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 3795, 69, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3864, 23, true);

WriteLiteral(" class=\"status-box-val\"");

EndContext("~/Views/Home/_Overview.cshtml", 3864, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3887, 13, true);

WriteLiteral(">7 / 10 <span");

EndContext("~/Views/Home/_Overview.cshtml", 3887, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3900, 13, true);

WriteLiteral(" class=\"unit\"");

EndContext("~/Views/Home/_Overview.cshtml", 3900, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3913, 35, true);

WriteLiteral(" data-i18n=\"overview_machines_unit\"");

EndContext("~/Views/Home/_Overview.cshtml", 3913, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 3948, 56, true);

WriteLiteral(">máy</span></span>\r\n            </div>\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 3948, 56, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4004, 31, true);

WriteLiteral(" class=\"status-box box-stopped\"");

EndContext("~/Views/Home/_Overview.cshtml", 4004, 31, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4035, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_Overview.cshtml", 4035, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4056, 26, true);

WriteLiteral(" class=\"status-box-header\"");

EndContext("~/Views/Home/_Overview.cshtml", 4056, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4082, 23, true);

WriteLiteral(">\r\n                <svg");

EndContext("~/Views/Home/_Overview.cshtml", 4082, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4105, 20, true);

WriteLiteral(" class=\"status-icon\"");

EndContext("~/Views/Home/_Overview.cshtml", 4105, 20, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4125, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Overview.cshtml", 4125, 20, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4145, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Overview.cshtml", 4145, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4157, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Overview.cshtml", 4157, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4179, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 4179, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4198, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 4198, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4221, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 4221, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4245, 26, true);

WriteLiteral(">\r\n                  <line");

EndContext("~/Views/Home/_Overview.cshtml", 4245, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4271, 7, true);

WriteLiteral(" x1=\"9\"");

EndContext("~/Views/Home/_Overview.cshtml", 4271, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4278, 7, true);

WriteLiteral(" y1=\"5\"");

EndContext("~/Views/Home/_Overview.cshtml", 4278, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4285, 7, true);

WriteLiteral(" x2=\"9\"");

EndContext("~/Views/Home/_Overview.cshtml", 4285, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4292, 8, true);

WriteLiteral(" y2=\"19\"");

EndContext("~/Views/Home/_Overview.cshtml", 4292, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4300, 33, true);

WriteLiteral("></line>\r\n                  <line");

EndContext("~/Views/Home/_Overview.cshtml", 4300, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4333, 8, true);

WriteLiteral(" x1=\"15\"");

EndContext("~/Views/Home/_Overview.cshtml", 4333, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4341, 7, true);

WriteLiteral(" y1=\"5\"");

EndContext("~/Views/Home/_Overview.cshtml", 4341, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4348, 8, true);

WriteLiteral(" x2=\"15\"");

EndContext("~/Views/Home/_Overview.cshtml", 4348, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4356, 8, true);

WriteLiteral(" y2=\"19\"");

EndContext("~/Views/Home/_Overview.cshtml", 4356, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4364, 55, true);

WriteLiteral("></line>\r\n                </svg>\r\n                <span");

EndContext("~/Views/Home/_Overview.cshtml", 4364, 55, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4419, 23, true);

WriteLiteral(" class=\"status-box-lbl\"");

EndContext("~/Views/Home/_Overview.cshtml", 4419, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4442, 30, true);

WriteLiteral(" data-i18n=\"kpi_stopped_title\"");

EndContext("~/Views/Home/_Overview.cshtml", 4442, 30, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4472, 59, true);

WriteLiteral(">MÁY DỪNG</span>\r\n              </div>\r\n              <span");

EndContext("~/Views/Home/_Overview.cshtml", 4472, 59, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4531, 23, true);

WriteLiteral(" class=\"status-box-val\"");

EndContext("~/Views/Home/_Overview.cshtml", 4531, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4554, 13, true);

WriteLiteral(">3 / 10 <span");

EndContext("~/Views/Home/_Overview.cshtml", 4554, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4567, 13, true);

WriteLiteral(" class=\"unit\"");

EndContext("~/Views/Home/_Overview.cshtml", 4567, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4580, 35, true);

WriteLiteral(" data-i18n=\"overview_machines_unit\"");

EndContext("~/Views/Home/_Overview.cshtml", 4580, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4615, 161, true);

WriteLiteral(">máy</span></span>\r\n            </div>\r\n          </div>\r\n        </div>\r\n      <" +
"/div>\r\n      \r\n      <!-- Panel 3: Time Series Chart & KPI Boxes -->\r\n      <div" +
"");

EndContext("~/Views/Home/_Overview.cshtml", 4615, 161, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4776, 24, true);

WriteLiteral(" class=\"kpi-panel-right\"");

EndContext("~/Views/Home/_Overview.cshtml", 4776, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4800, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Home/_Overview.cshtml", 4800, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4815, 27, true);

WriteLiteral(" class=\"chart-panel-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 4815, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4842, 17, true);

WriteLiteral(">\r\n          <div");

EndContext("~/Views/Home/_Overview.cshtml", 4842, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4859, 28, true);

WriteLiteral(" class=\"chart-header-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 4859, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4887, 18, true);

WriteLiteral(">\r\n            <h3");

EndContext("~/Views/Home/_Overview.cshtml", 4887, 18, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4905, 27, true);

WriteLiteral(" class=\"chart-title-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 4905, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4932, 37, true);

WriteLiteral(" data-i18n=\"chart_strokes_time_title\"");

EndContext("~/Views/Home/_Overview.cshtml", 4932, 37, true);

BeginContext("~/Views/Home/_Overview.cshtml", 4969, 84, true);

WriteLiteral(">SẢN LƯỢNG THỰC TẾ THEO THỜI GIAN</h3>\r\n          </div>\r\n          \r\n          <" +
"div");

EndContext("~/Views/Home/_Overview.cshtml", 4969, 84, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5053, 39, true);

WriteLiteral(" class=\"machine-chart-container-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 5053, 39, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5092, 19, true);

WriteLiteral(">\r\n            <svg");

EndContext("~/Views/Home/_Overview.cshtml", 5092, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5111, 24, true);

WriteLiteral(" class=\"trend-chart-svg\"");

EndContext("~/Views/Home/_Overview.cshtml", 5111, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5135, 22, true);

WriteLiteral(" viewBox=\"0 0 280 120\"");

EndContext("~/Views/Home/_Overview.cshtml", 5135, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5157, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Overview.cshtml", 5157, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5169, 35, true);

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

EndContext("~/Views/Home/_Overview.cshtml", 5169, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5204, 56, true);

WriteLiteral(">\r\n              <defs>\r\n                <linearGradient");

EndContext("~/Views/Home/_Overview.cshtml", 5204, 56, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5260, 28, true);

WriteLiteral(" id=\"chart-line-grad-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 5260, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5288, 8, true);

WriteLiteral(" x1=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5288, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5296, 8, true);

WriteLiteral(" y1=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5296, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5304, 10, true);

WriteLiteral(" x2=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5304, 10, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5314, 8, true);

WriteLiteral(" y2=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5314, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5322, 26, true);

WriteLiteral(">\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 5322, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5348, 12, true);

WriteLiteral(" offset=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5348, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5360, 21, true);

WriteLiteral(" stop-color=\"#0055ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 5360, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5381, 28, true);

WriteLiteral(" />\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 5381, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5409, 14, true);

WriteLiteral(" offset=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5409, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5423, 21, true);

WriteLiteral(" stop-color=\"#00d2ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 5423, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5444, 71, true);

WriteLiteral(" />\r\n                </linearGradient>\r\n                <linearGradient");

EndContext("~/Views/Home/_Overview.cshtml", 5444, 71, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5515, 28, true);

WriteLiteral(" id=\"chart-fill-grad-custom\"");

EndContext("~/Views/Home/_Overview.cshtml", 5515, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5543, 8, true);

WriteLiteral(" x1=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5543, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5551, 8, true);

WriteLiteral(" y1=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5551, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5559, 8, true);

WriteLiteral(" x2=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5559, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5567, 10, true);

WriteLiteral(" y2=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5567, 10, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5577, 26, true);

WriteLiteral(">\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 5577, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5603, 12, true);

WriteLiteral(" offset=\"0%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5603, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5615, 37, true);

WriteLiteral(" stop-color=\"rgba(0, 210, 255, 0.25)\"");

EndContext("~/Views/Home/_Overview.cshtml", 5615, 37, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5652, 28, true);

WriteLiteral(" />\r\n                  <stop");

EndContext("~/Views/Home/_Overview.cshtml", 5652, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5680, 14, true);

WriteLiteral(" offset=\"100%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5680, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5694, 36, true);

WriteLiteral(" stop-color=\"rgba(0, 210, 255, 0.0)\"");

EndContext("~/Views/Home/_Overview.cshtml", 5694, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5730, 63, true);

WriteLiteral(" />\r\n                </linearGradient>\r\n                <filter");

EndContext("~/Views/Home/_Overview.cshtml", 5730, 63, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5793, 28, true);

WriteLiteral(" id=\"chart-glow-custom-glow\"");

EndContext("~/Views/Home/_Overview.cshtml", 5793, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5821, 9, true);

WriteLiteral(" x=\"-10%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5821, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5830, 9, true);

WriteLiteral(" y=\"-10%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5830, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5839, 13, true);

WriteLiteral(" width=\"120%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5839, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5852, 14, true);

WriteLiteral(" height=\"120%\"");

EndContext("~/Views/Home/_Overview.cshtml", 5852, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5866, 36, true);

WriteLiteral(">\r\n                  <feGaussianBlur");

EndContext("~/Views/Home/_Overview.cshtml", 5866, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5902, 17, true);

WriteLiteral(" stdDeviation=\"4\"");

EndContext("~/Views/Home/_Overview.cshtml", 5902, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5919, 14, true);

WriteLiteral(" result=\"blur\"");

EndContext("~/Views/Home/_Overview.cshtml", 5919, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5933, 35, true);

WriteLiteral(" />\r\n                  <feComposite");

EndContext("~/Views/Home/_Overview.cshtml", 5933, 35, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5968, 19, true);

WriteLiteral(" in=\"SourceGraphic\"");

EndContext("~/Views/Home/_Overview.cshtml", 5968, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5987, 11, true);

WriteLiteral(" in2=\"blur\"");

EndContext("~/Views/Home/_Overview.cshtml", 5987, 11, true);

BeginContext("~/Views/Home/_Overview.cshtml", 5998, 16, true);

WriteLiteral(" operator=\"over\"");

EndContext("~/Views/Home/_Overview.cshtml", 5998, 16, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6014, 74, true);

WriteLiteral(" />\r\n                </filter>\r\n              </defs>\r\n              <line");

EndContext("~/Views/Home/_Overview.cshtml", 6014, 74, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6088, 8, true);

WriteLiteral(" x1=\"40\"");

EndContext("~/Views/Home/_Overview.cshtml", 6088, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6096, 8, true);

WriteLiteral(" y1=\"20\"");

EndContext("~/Views/Home/_Overview.cshtml", 6096, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6104, 9, true);

WriteLiteral(" x2=\"260\"");

EndContext("~/Views/Home/_Overview.cshtml", 6104, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6113, 8, true);

WriteLiteral(" y2=\"20\"");

EndContext("~/Views/Home/_Overview.cshtml", 6113, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6121, 17, true);

WriteLiteral(" stroke=\"#16223f\"");

EndContext("~/Views/Home/_Overview.cshtml", 6121, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6138, 17, true);

WriteLiteral(" stroke-width=\"1\"");

EndContext("~/Views/Home/_Overview.cshtml", 6138, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6155, 23, true);

WriteLiteral(" stroke-dasharray=\"3,3\"");

EndContext("~/Views/Home/_Overview.cshtml", 6155, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6178, 24, true);

WriteLiteral(" />\r\n              <line");

EndContext("~/Views/Home/_Overview.cshtml", 6178, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6202, 8, true);

WriteLiteral(" x1=\"40\"");

EndContext("~/Views/Home/_Overview.cshtml", 6202, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6210, 8, true);

WriteLiteral(" y1=\"55\"");

EndContext("~/Views/Home/_Overview.cshtml", 6210, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6218, 9, true);

WriteLiteral(" x2=\"260\"");

EndContext("~/Views/Home/_Overview.cshtml", 6218, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6227, 8, true);

WriteLiteral(" y2=\"55\"");

EndContext("~/Views/Home/_Overview.cshtml", 6227, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6235, 17, true);

WriteLiteral(" stroke=\"#16223f\"");

EndContext("~/Views/Home/_Overview.cshtml", 6235, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6252, 17, true);

WriteLiteral(" stroke-width=\"1\"");

EndContext("~/Views/Home/_Overview.cshtml", 6252, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6269, 23, true);

WriteLiteral(" stroke-dasharray=\"3,3\"");

EndContext("~/Views/Home/_Overview.cshtml", 6269, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6292, 24, true);

WriteLiteral(" />\r\n              <line");

EndContext("~/Views/Home/_Overview.cshtml", 6292, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6316, 8, true);

WriteLiteral(" x1=\"40\"");

EndContext("~/Views/Home/_Overview.cshtml", 6316, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6324, 8, true);

WriteLiteral(" y1=\"90\"");

EndContext("~/Views/Home/_Overview.cshtml", 6324, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6332, 9, true);

WriteLiteral(" x2=\"260\"");

EndContext("~/Views/Home/_Overview.cshtml", 6332, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6341, 8, true);

WriteLiteral(" y2=\"90\"");

EndContext("~/Views/Home/_Overview.cshtml", 6341, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6349, 17, true);

WriteLiteral(" stroke=\"#16223f\"");

EndContext("~/Views/Home/_Overview.cshtml", 6349, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6366, 17, true);

WriteLiteral(" stroke-width=\"1\"");

EndContext("~/Views/Home/_Overview.cshtml", 6366, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6383, 24, true);

WriteLiteral(" />\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 6383, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6407, 7, true);

WriteLiteral(" x=\"28\"");

EndContext("~/Views/Home/_Overview.cshtml", 6407, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6414, 7, true);

WriteLiteral(" y=\"24\"");

EndContext("~/Views/Home/_Overview.cshtml", 6414, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6421, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 6421, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6436, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 6436, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6450, 18, true);

WriteLiteral(" text-anchor=\"end\"");

EndContext("~/Views/Home/_Overview.cshtml", 6450, 18, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6468, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 6468, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6502, 33, true);

WriteLiteral(">2.0k</text>\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 6502, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6535, 7, true);

WriteLiteral(" x=\"28\"");

EndContext("~/Views/Home/_Overview.cshtml", 6535, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6542, 7, true);

WriteLiteral(" y=\"59\"");

EndContext("~/Views/Home/_Overview.cshtml", 6542, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6549, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 6549, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6564, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 6564, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6578, 18, true);

WriteLiteral(" text-anchor=\"end\"");

EndContext("~/Views/Home/_Overview.cshtml", 6578, 18, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6596, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 6596, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6630, 33, true);

WriteLiteral(">1.0k</text>\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 6630, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6663, 7, true);

WriteLiteral(" x=\"28\"");

EndContext("~/Views/Home/_Overview.cshtml", 6663, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6670, 7, true);

WriteLiteral(" y=\"94\"");

EndContext("~/Views/Home/_Overview.cshtml", 6670, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6677, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 6677, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6692, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 6692, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6706, 18, true);

WriteLiteral(" text-anchor=\"end\"");

EndContext("~/Views/Home/_Overview.cshtml", 6706, 18, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6724, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 6724, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6758, 32, true);

WriteLiteral(">500</text>\r\n              <path");

EndContext("~/Views/Home/_Overview.cshtml", 6758, 32, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6790, 21, true);

WriteLiteral(" id=\"chart-fill-path\"");

EndContext("~/Views/Home/_Overview.cshtml", 6790, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6811, 98, true);

WriteLiteral(" d=\"M 40,85 C 75,85 75,65 110,65 C 145,65 145,35 180,35 C 215,35 215,45 250,45 L " +
"250,90 L 40,90 Z\"");

EndContext("~/Views/Home/_Overview.cshtml", 6811, 98, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6909, 36, true);

WriteLiteral(" fill=\"url(#chart-fill-grad-custom)\"");

EndContext("~/Views/Home/_Overview.cshtml", 6909, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6945, 24, true);

WriteLiteral(" />\r\n              <path");

EndContext("~/Views/Home/_Overview.cshtml", 6945, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6969, 22, true);

WriteLiteral(" id=\"chart-trend-path\"");

EndContext("~/Views/Home/_Overview.cshtml", 6969, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 6991, 79, true);

WriteLiteral(" d=\"M 40,85 C 75,85 75,65 110,65 C 145,65 145,35 180,35 C 215,35 215,45 250,45\"");

EndContext("~/Views/Home/_Overview.cshtml", 6991, 79, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7070, 38, true);

WriteLiteral(" stroke=\"url(#chart-line-grad-custom)\"");

EndContext("~/Views/Home/_Overview.cshtml", 7070, 38, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7108, 17, true);

WriteLiteral(" stroke-width=\"3\"");

EndContext("~/Views/Home/_Overview.cshtml", 7108, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7125, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 7125, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7148, 38, true);

WriteLiteral(" filter=\"url(#chart-glow-custom-glow)\"");

EndContext("~/Views/Home/_Overview.cshtml", 7148, 38, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7186, 26, true);

WriteLiteral(" />\r\n              <circle");

EndContext("~/Views/Home/_Overview.cshtml", 7186, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7212, 8, true);

WriteLiteral(" cx=\"40\"");

EndContext("~/Views/Home/_Overview.cshtml", 7212, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7220, 8, true);

WriteLiteral(" cy=\"85\"");

EndContext("~/Views/Home/_Overview.cshtml", 7220, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7228, 6, true);

WriteLiteral(" r=\"4\"");

EndContext("~/Views/Home/_Overview.cshtml", 7228, 6, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7234, 15, true);

WriteLiteral(" fill=\"#00d2ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 7234, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7249, 17, true);

WriteLiteral(" stroke=\"#0c1527\"");

EndContext("~/Views/Home/_Overview.cshtml", 7249, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7266, 19, true);

WriteLiteral(" stroke-width=\"1.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 7266, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7285, 26, true);

WriteLiteral(" />\r\n              <circle");

EndContext("~/Views/Home/_Overview.cshtml", 7285, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7311, 9, true);

WriteLiteral(" cx=\"110\"");

EndContext("~/Views/Home/_Overview.cshtml", 7311, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7320, 8, true);

WriteLiteral(" cy=\"65\"");

EndContext("~/Views/Home/_Overview.cshtml", 7320, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7328, 6, true);

WriteLiteral(" r=\"4\"");

EndContext("~/Views/Home/_Overview.cshtml", 7328, 6, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7334, 15, true);

WriteLiteral(" fill=\"#00d2ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 7334, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7349, 17, true);

WriteLiteral(" stroke=\"#0c1527\"");

EndContext("~/Views/Home/_Overview.cshtml", 7349, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7366, 19, true);

WriteLiteral(" stroke-width=\"1.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 7366, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7385, 26, true);

WriteLiteral(" />\r\n              <circle");

EndContext("~/Views/Home/_Overview.cshtml", 7385, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7411, 9, true);

WriteLiteral(" cx=\"180\"");

EndContext("~/Views/Home/_Overview.cshtml", 7411, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7420, 8, true);

WriteLiteral(" cy=\"35\"");

EndContext("~/Views/Home/_Overview.cshtml", 7420, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7428, 6, true);

WriteLiteral(" r=\"4\"");

EndContext("~/Views/Home/_Overview.cshtml", 7428, 6, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7434, 15, true);

WriteLiteral(" fill=\"#00d2ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 7434, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7449, 17, true);

WriteLiteral(" stroke=\"#0c1527\"");

EndContext("~/Views/Home/_Overview.cshtml", 7449, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7466, 19, true);

WriteLiteral(" stroke-width=\"1.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 7466, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7485, 26, true);

WriteLiteral(" />\r\n              <circle");

EndContext("~/Views/Home/_Overview.cshtml", 7485, 26, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7511, 9, true);

WriteLiteral(" cx=\"250\"");

EndContext("~/Views/Home/_Overview.cshtml", 7511, 9, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7520, 8, true);

WriteLiteral(" cy=\"45\"");

EndContext("~/Views/Home/_Overview.cshtml", 7520, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7528, 6, true);

WriteLiteral(" r=\"4\"");

EndContext("~/Views/Home/_Overview.cshtml", 7528, 6, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7534, 15, true);

WriteLiteral(" fill=\"#00d2ff\"");

EndContext("~/Views/Home/_Overview.cshtml", 7534, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7549, 17, true);

WriteLiteral(" stroke=\"#0c1527\"");

EndContext("~/Views/Home/_Overview.cshtml", 7549, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7566, 19, true);

WriteLiteral(" stroke-width=\"1.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 7566, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7585, 24, true);

WriteLiteral(" />\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 7585, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7609, 7, true);

WriteLiteral(" x=\"40\"");

EndContext("~/Views/Home/_Overview.cshtml", 7609, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7616, 8, true);

WriteLiteral(" y=\"112\"");

EndContext("~/Views/Home/_Overview.cshtml", 7616, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7624, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 7624, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7639, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 7639, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7653, 21, true);

WriteLiteral(" text-anchor=\"middle\"");

EndContext("~/Views/Home/_Overview.cshtml", 7653, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7674, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 7674, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7708, 34, true);

WriteLiteral(">07:00</text>\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 7708, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7742, 8, true);

WriteLiteral(" x=\"110\"");

EndContext("~/Views/Home/_Overview.cshtml", 7742, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7750, 8, true);

WriteLiteral(" y=\"112\"");

EndContext("~/Views/Home/_Overview.cshtml", 7750, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7758, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 7758, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7773, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 7773, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7787, 21, true);

WriteLiteral(" text-anchor=\"middle\"");

EndContext("~/Views/Home/_Overview.cshtml", 7787, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7808, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 7808, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7842, 34, true);

WriteLiteral(">10:00</text>\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 7842, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7876, 8, true);

WriteLiteral(" x=\"180\"");

EndContext("~/Views/Home/_Overview.cshtml", 7876, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7884, 8, true);

WriteLiteral(" y=\"112\"");

EndContext("~/Views/Home/_Overview.cshtml", 7884, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7892, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 7892, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7907, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 7907, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7921, 21, true);

WriteLiteral(" text-anchor=\"middle\"");

EndContext("~/Views/Home/_Overview.cshtml", 7921, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7942, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 7942, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 7976, 34, true);

WriteLiteral(">13:00</text>\r\n              <text");

EndContext("~/Views/Home/_Overview.cshtml", 7976, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8010, 8, true);

WriteLiteral(" x=\"250\"");

EndContext("~/Views/Home/_Overview.cshtml", 8010, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8018, 8, true);

WriteLiteral(" y=\"112\"");

EndContext("~/Views/Home/_Overview.cshtml", 8018, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8026, 15, true);

WriteLiteral(" fill=\"#4e5b6e\"");

EndContext("~/Views/Home/_Overview.cshtml", 8026, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8041, 14, true);

WriteLiteral(" font-size=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 8041, 14, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8055, 21, true);

WriteLiteral(" text-anchor=\"middle\"");

EndContext("~/Views/Home/_Overview.cshtml", 8055, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8076, 34, true);

WriteLiteral(" font-family=\"\'Inter\', sans-serif\"");

EndContext("~/Views/Home/_Overview.cshtml", 8076, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8110, 79, true);

WriteLiteral(">16:00</text>\r\n            </svg>\r\n          </div>\r\n          \r\n          <div");

EndContext("~/Views/Home/_Overview.cshtml", 8110, 79, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8189, 23, true);

WriteLiteral(" class=\"perf-boxes-row\"");

EndContext("~/Views/Home/_Overview.cshtml", 8189, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8212, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Home/_Overview.cshtml", 8212, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8231, 17, true);

WriteLiteral(" class=\"perf-box\"");

EndContext("~/Views/Home/_Overview.cshtml", 8231, 17, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8248, 21, true);

WriteLiteral(">\r\n              <div");

EndContext("~/Views/Home/_Overview.cshtml", 8248, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8269, 25, true);

WriteLiteral(" class=\"perf-box-details\"");

EndContext("~/Views/Home/_Overview.cshtml", 8269, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8294, 24, true);

WriteLiteral(">\r\n                <span");

EndContext("~/Views/Home/_Overview.cshtml", 8294, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8318, 21, true);

WriteLiteral(" class=\"perf-box-lbl\"");

EndContext("~/Views/Home/_Overview.cshtml", 8318, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8339, 33, true);

WriteLiteral(" data-i18n=\"perf_time_efficiency\"");

EndContext("~/Views/Home/_Overview.cshtml", 8339, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8372, 55, true);

WriteLiteral(">HIỆU SUẤT THỜI GIAN (TB)</span>\r\n                <span");

EndContext("~/Views/Home/_Overview.cshtml", 8372, 55, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8427, 21, true);

WriteLiteral(" class=\"perf-box-val\"");

EndContext("~/Views/Home/_Overview.cshtml", 8427, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8448, 34, true);

WriteLiteral(" id=\"overview-time-efficiency-avg\"");

EndContext("~/Views/Home/_Overview.cshtml", 8448, 34, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8482, 36, true);

WriteLiteral(">64.6%</span>\r\n                <span");

EndContext("~/Views/Home/_Overview.cshtml", 8482, 36, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8518, 21, true);

WriteLiteral(" class=\"perf-box-sub\"");

EndContext("~/Views/Home/_Overview.cshtml", 8518, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8539, 195, true);

WriteLiteral(">= Thời gian máy chạy / Thời gian ca</span>\r\n              </div>\r\n            </" +
"div>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n    \r\n    <!--" +
" Row 2: Machine Grid -->\r\n    <div");

EndContext("~/Views/Home/_Overview.cshtml", 8539, 195, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8734, 31, true);

WriteLiteral(" class=\"machine-grid-container\"");

EndContext("~/Views/Home/_Overview.cshtml", 8734, 31, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8765, 28, true);

WriteLiteral(" id=\"machine-grid-container\"");

EndContext("~/Views/Home/_Overview.cshtml", 8765, 28, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8793, 13, true);

WriteLiteral(">\r\n      <div");

EndContext("~/Views/Home/_Overview.cshtml", 8793, 13, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8806, 21, true);

WriteLiteral(" class=\"machine-grid\"");

EndContext("~/Views/Home/_Overview.cshtml", 8806, 21, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8827, 27, true);

WriteLiteral(" id=\"overview-machine-grid\"");

EndContext("~/Views/Home/_Overview.cshtml", 8827, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8854, 125, true);

WriteLiteral(">\r\n        <!-- Will be dynamically populated via JS -->\r\n      </div>\r\n\r\n      <" +
"!-- Dòng thông tin hướng dẫn -->\r\n      <div");

EndContext("~/Views/Home/_Overview.cshtml", 8854, 125, true);

BeginContext("~/Views/Home/_Overview.cshtml", 8979, 25, true);

WriteLiteral(" class=\"grid-helper-text\"");

EndContext("~/Views/Home/_Overview.cshtml", 8979, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9004, 15, true);

WriteLiteral(">\r\n        <svg");

EndContext("~/Views/Home/_Overview.cshtml", 9004, 15, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9019, 25, true);

WriteLiteral(" class=\"helper-info-icon\"");

EndContext("~/Views/Home/_Overview.cshtml", 9019, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9044, 20, true);

WriteLiteral(" viewBox=\"0 0 24 24\"");

EndContext("~/Views/Home/_Overview.cshtml", 9044, 20, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9064, 12, true);

WriteLiteral(" fill=\"none\"");

EndContext("~/Views/Home/_Overview.cshtml", 9064, 12, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9076, 22, true);

WriteLiteral(" stroke=\"currentColor\"");

EndContext("~/Views/Home/_Overview.cshtml", 9076, 22, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9098, 19, true);

WriteLiteral(" stroke-width=\"2.5\"");

EndContext("~/Views/Home/_Overview.cshtml", 9098, 19, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9117, 23, true);

WriteLiteral(" stroke-linecap=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 9117, 23, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9140, 24, true);

WriteLiteral(" stroke-linejoin=\"round\"");

EndContext("~/Views/Home/_Overview.cshtml", 9140, 24, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9164, 20, true);

WriteLiteral(">\r\n          <circle");

EndContext("~/Views/Home/_Overview.cshtml", 9164, 20, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9184, 8, true);

WriteLiteral(" cx=\"12\"");

EndContext("~/Views/Home/_Overview.cshtml", 9184, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9192, 8, true);

WriteLiteral(" cy=\"12\"");

EndContext("~/Views/Home/_Overview.cshtml", 9192, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9200, 7, true);

WriteLiteral(" r=\"10\"");

EndContext("~/Views/Home/_Overview.cshtml", 9200, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9207, 27, true);

WriteLiteral("></circle>\r\n          <line");

EndContext("~/Views/Home/_Overview.cshtml", 9207, 27, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9234, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Overview.cshtml", 9234, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9242, 8, true);

WriteLiteral(" y1=\"16\"");

EndContext("~/Views/Home/_Overview.cshtml", 9242, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9250, 8, true);

WriteLiteral(" x2=\"12\"");

EndContext("~/Views/Home/_Overview.cshtml", 9250, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9258, 8, true);

WriteLiteral(" y2=\"12\"");

EndContext("~/Views/Home/_Overview.cshtml", 9258, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9266, 25, true);

WriteLiteral("></line>\r\n          <line");

EndContext("~/Views/Home/_Overview.cshtml", 9266, 25, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9291, 8, true);

WriteLiteral(" x1=\"12\"");

EndContext("~/Views/Home/_Overview.cshtml", 9291, 8, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9299, 7, true);

WriteLiteral(" y1=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 9299, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9306, 11, true);

WriteLiteral(" x2=\"12.01\"");

EndContext("~/Views/Home/_Overview.cshtml", 9306, 11, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9317, 7, true);

WriteLiteral(" y2=\"8\"");

EndContext("~/Views/Home/_Overview.cshtml", 9317, 7, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9324, 39, true);

WriteLiteral("></line>\r\n        </svg>\r\n        <span");

EndContext("~/Views/Home/_Overview.cshtml", 9324, 39, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9363, 33, true);

WriteLiteral(" data-i18n=\"overview_grid_helper\"");

EndContext("~/Views/Home/_Overview.cshtml", 9363, 33, true);

BeginContext("~/Views/Home/_Overview.cshtml", 9396, 119, true);

WriteLiteral(">Nhấn vào từng máy để xem chi tiết</span>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</" +
"section>\r\n\r\n<!-- 2. VIEW MÁY DẬP -->\r\n");

EndContext("~/Views/Home/_Overview.cshtml", 9396, 119, true);

        }
    }
}
